<a href="https://colab.research.google.com/github/majorquev/DBDC_202604_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/Clase3/Clase3_01_manipulacion_de_tablas_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 2: Manipulación de tablas en R (Parte I)


**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales<br>
**E-mail ayudante:** rumorale1@gmail.com

## 1. Instalación de librerías

En esta sección aprenderemos a realizar operaciones simples de manipulación de tablas en R. Para ello trabajaremos con la librería _dplyr_, la cual cuenta con una gran variedad de funciones para manipular tablas, entre otras.


Una manera de instalar librerías en R es me diante la función `install.packages()`, la cual recibe como argunmento principal el nombre (enre comillas) de la librería que se desea cargar.

Una vez instalada la librería la debemos cargar en la sesión de trbajao, para lo cual podemos utilizar la función `library()` la cual recibe como argumento el nombre de la librería que se quiere cargar.

In [ ]:
install.packages("dplyr")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [ ]:
glimpse(list(1))

ERROR: Error in glimpse(list(1)): could not find function "glimpse"

In [1]:
# 1. Instalación de package
# install.packages("dplyr") # No instalaremos la librería pues ya viene cargada en los notebooks de azure.Probablemente sea necesario hacerlo en su entorno local.
# Para cargar la librería
library("dplyr") # sin comillas también funciona

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

## 2. Funciones básicas en dplyr

En todo proyecto analítico es necesario procesar, limpar y unificar disntintas fuentes de información para poder generar los análisis requeridos. Para dichas tareas, en la librería _dplyr_ contamos con funciones que nos permitirán filtrar datos, crear columnas, agrupar tablas, y cruzar tablas.

A continuación trabajaremos con la siguientes funciones:<br>

   `filter()`                        : Para filtrar los datos (por filas).<br>
   `arrange()`                       : Para ordenar un dataset.<br>
   `select()`                        : Para seleccionar y renombrar columnas.<br>
   `mutate()`                        : Para crear (o modificar) nuevas columnas basadas en columnas existentes.<br>
   `group_by()`                     : Para agrupar tablas.<br>
   `sample_n()` and `sample_frac()`  : Para generar muestras aleatorias<br>
   
   
Para entender el funcionamiento de estas funciones trabjaremos con el set de datos _nycflights13_, el cual contiene la información de los vuelos con salida en los aeropuertos de Nueva York en el año 2013.

## 3. Carga de datos

En R es posible cargar datos provenientes de archivos de texto plano. Un ejemplo de ellos son los de extensión *.csv (comma separated values). Para cargar los datos a la sesión, lo podemos realizar a través de la función `read.csv()`, la cual recibe como argumento principal la ruta del archivo a cargar.

In [ ]:
getwd()
# setwd(la ruta que desean)

[1] "/content"

In [3]:
# Carga de datos ------
# Usaremos la función read.csv para cargar el archivo Datasets_flights.csv ubicado en "./Datasets/", y lo guardamos en una variable llamada vuelo.

#vuelos <- read.csv("flights.csv", header = T, sep = ",", dec = "." )
vuelos <- read.csv("https://raw.githubusercontent.com/majorquev/DBDC_202604_Programacion_en_R_para_ciencia_de_datos/refs/heads/main/Clases/Clase3/Datasets/flights.csv", header = T, sep = ",", dec = "." )

In [ ]:
test <- read.csv("/content/sample_data/mnist_test.csv") # Debemos indicar la ruta completa si el archivo no está en el WD (directorio de trabajo)

In [ ]:
# Podemos inspeccionar los datos cargados
# Para ello son de utilidad las funciones head() y tail()
head(vuelos,3)
tail(vuelos,3)

  year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     1   517      515            2         830      819
2 2013 1     1   533      529            4         850      830
3 2013 1     1   542      540            2         923      850
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1 11        UA      1545   N14228  EWR    IAH  227      1400     5    15
2 20        UA      1714   N24211  LGA    IAH  227      1416     5    29
3 33        AA      1141   N619AA  JFK    MIA  160      1089     5    40
  time_hour
1 2013-01-01 05:00:00
2 2013-01-01 05:00:00
3 2013-01-01 05:00:00

       year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
336774 2013 9     30  NA       1210           NA        NA       1330
336775 2013 9     30  NA       1159           NA        NA       1344
336776 2013 9     30  NA        840           NA        NA       1020
       arr_delay carrier flight tailnum origin dest air_time distance hour
336774 NA        MQ      3461   N535MQ  LGA    BNA  NA       764      12
336775 NA        MQ      3572   N511MQ  LGA    CLE  NA       419      11
336776 NA        MQ      3531   N839MQ  LGA    RDU  NA       431       8
       minute time_hour
336774 10     2013-09-30 12:00:00
336775 59     2013-09-30 11:00:00
336776 40     2013-09-30 08:00:00

In [5]:
# Filas, summary() y otros...
# ¿Cuántos registros tienen las tablas?
class(vuelos)
dim(vuelos)
nrow(vuelos)

[1] "data.frame"

[1] 336776     19

[1] 336776

In [ ]:
summary(vuelos)

      year          month             day           dep_time    sched_dep_time
 Min.   :2013   Min.   : 1.000   Min.   : 1.00   Min.   :   1   Min.   : 106
 1st Qu.:2013   1st Qu.: 4.000   1st Qu.: 8.00   1st Qu.: 907   1st Qu.: 906
 Median :2013   Median : 7.000   Median :16.00   Median :1401   Median :1359
 Mean   :2013   Mean   : 6.549   Mean   :15.71   Mean   :1349   Mean   :1344
 3rd Qu.:2013   3rd Qu.:10.000   3rd Qu.:23.00   3rd Qu.:1744   3rd Qu.:1729
 Max.   :2013   Max.   :12.000   Max.   :31.00   Max.   :2400   Max.   :2359
                                                 NA's   :8255
   dep_delay          arr_time    sched_arr_time   arr_delay
 Min.   : -43.00   Min.   :   1   Min.   :   1   Min.   : -86.000
 1st Qu.:  -5.00   1st Qu.:1104   1st Qu.:1124   1st Qu.: -17.000
 Median :  -2.00   Median :1535   Median :1556   Median :  -5.000
 Mean   :  12.64   Mean   :1502   Mean   :1536   Mean   :   6.895
 3rd Qu.:  11.00   3rd Qu.:1940   3rd Qu.:1945   3rd Qu.:  14.000
 Max.   :1301.00   Max.   :2400   Max.   :2359   Max.   :1272.000
 NA's   :8255      NA's   :8713                  NA's   :9430
   carrier              flight       tailnum             origin
 Length:336776      Min.   :   1   Length:336776      Length:336776
 Class :character   1st Qu.: 553   Class :character   Class :character
 Mode  :character   Median :1496   Mode  :character   Mode  :character
                    Mean   :1972
                    3rd Qu.:3465
                    Max.   :8500

     dest              air_time        distance         hour
 Length:336776      Min.   : 20.0   Min.   :  17   Min.   : 1.00
 Class :character   1st Qu.: 82.0   1st Qu.: 502   1st Qu.: 9.00
 Mode  :character   Median :129.0   Median : 872   Median :13.00
                    Mean   :150.7   Mean   :1040   Mean   :13.18
                    3rd Qu.:192.0   3rd Qu.:1389   3rd Qu.:17.00
                    Max.   :695.0   Max.   :4983   Max.   :23.00
                    NA's   :9430
     minute       time_hour
 Min.   : 0.00   Length:336776
 1st Qu.: 8.00   Class :character
 Median :29.00   Mode  :character
 Mean   :26.23
 3rd Qu.:44.00
 Max.   :59.00

## NOTA: factores

In [ ]:
vuelos$carrier <- as.factor(vuelos$carrier)

In [ ]:
summary(vuelos)

      year          month             day           dep_time    sched_dep_time
 Min.   :2013   Min.   : 1.000   Min.   : 1.00   Min.   :   1   Min.   : 106
 1st Qu.:2013   1st Qu.: 4.000   1st Qu.: 8.00   1st Qu.: 907   1st Qu.: 906
 Median :2013   Median : 7.000   Median :16.00   Median :1401   Median :1359
 Mean   :2013   Mean   : 6.549   Mean   :15.71   Mean   :1349   Mean   :1344
 3rd Qu.:2013   3rd Qu.:10.000   3rd Qu.:23.00   3rd Qu.:1744   3rd Qu.:1729
 Max.   :2013   Max.   :12.000   Max.   :31.00   Max.   :2400   Max.   :2359
                                                 NA's   :8255
   dep_delay          arr_time    sched_arr_time   arr_delay
 Min.   : -43.00   Min.   :   1   Min.   :   1   Min.   : -86.000
 1st Qu.:  -5.00   1st Qu.:1104   1st Qu.:1124   1st Qu.: -17.000
 Median :  -2.00   Median :1535   Median :1556   Median :  -5.000
 Mean   :  12.64   Mean   :1502   Mean   :1536   Mean   :   6.895
 3rd Qu.:  11.00   3rd Qu.:1940   3rd Qu.:1945   3rd Qu.:  14.000
 Max.   :1301.00   Max.   :2400   Max.   :2359   Max.   :1272.000
 NA's   :8255      NA's   :8713                  NA's   :9430
    carrier          flight       tailnum             origin
 UA     :58665   Min.   :   1   Length:336776      Length:336776
 B6     :54635   1st Qu.: 553   Class :character   Class :character
 EV     :54173   Median :1496   Mode  :character   Mode  :character
 DL     :48110   Mean   :1972
 AA     :32729   3rd Qu.:3465
 MQ     :26397   Max.   :8500
 (Other):62067
     dest              air_time        distance         hour
 Length:336776      Min.   : 20.0   Min.   :  17   Min.   : 1.00
 Class :character   1st Qu.: 82.0   1st Qu.: 502   1st Qu.: 9.00
 Mode  :character   Median :129.0   Median : 872   Median :13.00
                    Mean   :150.7   Mean   :1040   Mean   :13.18
                    3rd Qu.:192.0   3rd Qu.:1389   3rd Qu.:17.00
                    Max.   :695.0   Max.   :4983   Max.   :23.00
                    NA's   :9430
     minute       time_hour
 Min.   : 0.00   Length:336776
 1st Qu.: 8.00   Class :character
 Median :29.00   Mode  :character
 Mean   :26.23
 3rd Qu.:44.00
 Max.   :59.00

In [ ]:
head(vuelos)

  year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     1   517      515             2         830      819
2 2013 1     1   533      529             4         850      830
3 2013 1     1   542      540             2         923      850
4 2013 1     1   544      545            -1        1004     1022
5 2013 1     1   554      600            -6         812      837
6 2013 1     1   554      558            -4         740      728
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  11       UA      1545   N14228  EWR    IAH  227      1400     5    15
2  20       UA      1714   N24211  LGA    IAH  227      1416     5    29
3  33       AA      1141   N619AA  JFK    MIA  160      1089     5    40
4 -18       B6       725   N804JB  JFK    BQN  183      1576     5    45
5 -25       DL       461   N668DN  LGA    ATL  116       762     6     0
6  12       UA      1696   N39463  EWR    ORD  150       719     5    58
  time_hour
1 2013-01-01 05:00:00
2 2013-01-01 05:00:00
3 2013-01-01 05:00:00
4 2013-01-01 05:00:00
5 2013-01-01 06:00:00
6 2013-01-01 05:00:00

In [ ]:
vuelos$carrier <- as.character(vuelos$carrier)

In [ ]:
summary(vuelos)

      year          month             day           dep_time    sched_dep_time
 Min.   :2013   Min.   : 1.000   Min.   : 1.00   Min.   :   1   Min.   : 106
 1st Qu.:2013   1st Qu.: 4.000   1st Qu.: 8.00   1st Qu.: 907   1st Qu.: 906
 Median :2013   Median : 7.000   Median :16.00   Median :1401   Median :1359
 Mean   :2013   Mean   : 6.549   Mean   :15.71   Mean   :1349   Mean   :1344
 3rd Qu.:2013   3rd Qu.:10.000   3rd Qu.:23.00   3rd Qu.:1744   3rd Qu.:1729
 Max.   :2013   Max.   :12.000   Max.   :31.00   Max.   :2400   Max.   :2359
                                                 NA's   :8255
   dep_delay          arr_time    sched_arr_time   arr_delay
 Min.   : -43.00   Min.   :   1   Min.   :   1   Min.   : -86.000
 1st Qu.:  -5.00   1st Qu.:1104   1st Qu.:1124   1st Qu.: -17.000
 Median :  -2.00   Median :1535   Median :1556   Median :  -5.000
 Mean   :  12.64   Mean   :1502   Mean   :1536   Mean   :   6.895
 3rd Qu.:  11.00   3rd Qu.:1940   3rd Qu.:1945   3rd Qu.:  14.000
 Max.   :1301.00   Max.   :2400   Max.   :2359   Max.   :1272.000
 NA's   :8255      NA's   :8713                  NA's   :9430
   carrier              flight       tailnum             origin
 Length:336776      Min.   :   1   Length:336776      Length:336776
 Class :character   1st Qu.: 553   Class :character   Class :character
 Mode  :character   Median :1496   Mode  :character   Mode  :character
                    Mean   :1972
                    3rd Qu.:3465
                    Max.   :8500

     dest              air_time        distance         hour
 Length:336776      Min.   : 20.0   Min.   :  17   Min.   : 1.00
 Class :character   1st Qu.: 82.0   1st Qu.: 502   1st Qu.: 9.00
 Mode  :character   Median :129.0   Median : 872   Median :13.00
                    Mean   :150.7   Mean   :1040   Mean   :13.18
                    3rd Qu.:192.0   3rd Qu.:1389   3rd Qu.:17.00
                    Max.   :695.0   Max.   :4983   Max.   :23.00
                    NA's   :9430
     minute       time_hour
 Min.   : 0.00   Length:336776
 1st Qu.: 8.00   Class :character
 Median :29.00   Mode  :character
 Mean   :26.23
 3rd Qu.:44.00
 Max.   :59.00

In [ ]:
#glimpse() o str()
glimpse(vuelos)

Rows: 336,776
Columns: 19
$ year           <int> 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2…
$ month          <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ day            <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ dep_time       <int> 517, 533, 542, 544, 554, 554, 555, 557, 557, 558, 558, …
$ sched_dep_time <int> 515, 529, 540, 545, 600, 558, 600, 600, 600, 600, 600, …
$ dep_delay      <int> 2, 4, 2, -1, -6, -4, -5, -3, -3, -2, -2, -2, -2, -2, -1…
$ arr_time       <int> 830, 850, 923, 1004, 812, 740, 913, 709, 838, 753, 849,…
$ sched_arr_time <int> 819, 830, 850, 1022, 837, 728, 854, 723, 846, 745, 851,…
$ arr_delay      <int> 11, 20, 33, -18, -25, 12, 19, -14, -8, 8, -2, -3, 7, -1…
$ carrier        <chr> "UA", "UA", "AA", "B6", "DL", "UA", "B6", "EV", "B6", "…
$ flight         <int> 1545, 1714, 1141, 725, 461, 1696, 507, 5708, 79, 301, 4…
$ tailnum        <chr> "N14228", "N24211", "N619AA", "N804JB", "N668DN", "N394…
$ origin         <chr> "EWR", "LGA", "JFK", "JFK", "LGA", "EWR", "EWR", "LGA",…
$ dest           <chr> "IAH", "IAH", "MIA", "BQN", "ATL", "ORD", "FLL", "IAD",…
$ air_time       <int> 227, 227, 160, 183, 116, 150, 158, 53, 140, 138, 149, 1…
$ distance       <int> 1400, 1416, 1089, 1576, 762, 719, 1065, 229, 944, 733, …
$ hour           <int> 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6…
$ minute         <int> 15, 29, 40, 45, 0, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 59, 0…
$ time_hour      <chr> "2013-01-01 05:00:00", "2013-01-01 05:00:00", "2013-01-…

## 4. Funciones básicas de dplyr

A continuación exploraremos los datos de vuelos utilizando la librería dplyr.

### 4.1 Función filter()

La función filter() de dplyr es el equivalente a la sentencia where de sql.

In [ ]:
# filter() # where de sql----------------------------------------------------------------
# Registros que tengan fecha 31 de diciembre
# Antes
vuelos[(vuelos$month == 12) & (vuelos$day == 31), ] #776 registros (vuelos) el 31 de diciembre

       year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
110521 2013 12    31   13      2359            14        439      437
110522 2013 12    31   18      2359            19        449      444
110523 2013 12    31   26      2245           101        129     2353
110524 2013 12    31  459       500            -1        655      651
110525 2013 12    31  514       515            -1        814      812
110526 2013 12    31  549       551            -2        925      900
110527 2013 12    31  550       600           -10        725      745
110528 2013 12    31  552       600            -8        811      826
110529 2013 12    31  553       600            -7        741      754
110530 2013 12    31  554       550             4       1024     1027
110531 2013 12    31  555       600            -5        901      849
110532 2013 12    31  555       600            -5        835      831
110533 2013 12    31  555       551             4        853      851
110534 2013 12    31  556       600            -4        909      846
110535 2013 12    31  556       605            -9        808      814
110536 2013 12    31  557       603            -6        719      719
110537 2013 12    31  558       600            -2        919      905
110538 2013 12    31  559       600            -1        917      855
110539 2013 12    31  600       540            20        928      850
110540 2013 12    31  602       605            -3        744      805
110541 2013 12    31  602       605            -3        708      723
110542 2013 12    31  603       611            -8       1045     1055
110543 2013 12    31  607       600             7        848      825
110544 2013 12    31  608       615            -7        812      818
110545 2013 12    31  609       610            -1        911      915
110546 2013 12    31  609       615            -6        848      850
110547 2013 12    31  609       614            -5        755      751
110548 2013 12    31  610       615            -5        828      849
110549 2013 12    31  616       611             5        933      912
110550 2013 12    31  616       630           -14        922      919
⋮      ⋮    ⋮     ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
111267 2013 12    31  2155     2039            76        253     2355
111268 2013 12    31  2155     2150             5        110       51
111269 2013 12    31  2159     2155             4         55       46
111270 2013 12    31  2206     2110            56         44     2339
111271 2013 12    31  2211     2159            12        100       45
111272 2013 12    31  2218     2219            -1        315      304
111273 2013 12    31  2235     2245           -10       2351     2355
111274 2013 12    31  2245     2250            -5       2359     2356
111275 2013 12    31  2310     2255            15          7     2356
111276 2013 12    31  2321     2250            31         46        8
111277 2013 12    31  2328     2330            -2        412      409
111278 2013 12    31  2332     2245            47         58        3
111279 2013 12    31  2355     2359            -4        430      440
111280 2013 12    31  2356     2359            -3        436      445
111281 2013 12    31    NA     1520            NA         NA     1705
111282 2013 12    31    NA     2025            NA         NA     2205
111283 2013 12    31    NA     1932            NA         NA     2305
111284 2013 12    31    NA     1505            NA         NA     1725
111285 2013 12    31    NA     1000            NA         NA     1252
111286 2013 12    31    NA      840            NA         NA     1205
111287 2013 12    31    NA      754            NA         NA     1118
111288 2013 12    31    NA     2000            NA         NA     2146
111289 2013 12    31    NA     1500            NA         NA     1817
111290 2013 12    31    NA     1430            NA         NA     1750
111291 2013 12    31    NA      855            NA         NA     1142
111292 2013 12    31    NA      705            NA         NA      931
111293 2013 12    31    NA      825            NA         NA     1029
111294 2013 12    31    NA     1615            NA         NA     1800
111295 2013 12    31    NA      600            NA         NA      735
111296 2013 12    31    NA      830            NA         NA     1154
       arr_delay carrier flight tailnum origin dest air_time distance hour
110521   2       B6       839   N566JB  JFK    BQN  189      1576     23
110522   5       DL       412   N713TW  JFK    SJU  192      1598     23
110523  96       B6       108   N374JB  JFK    PWM   50       273     22
110524   4       US      1895   N557UW  EWR    CLT   95       529      5
110525   2       UA       700   N470UA  EWR    IAH  223      1400      5
110526  25       UA       274   N577UA  EWR    LAX  346      2454      5
110527 -20       AA       301   N3CXAA  LGA    ORD  127       733      6
110528 -15       EV      3825   N14916  EWR    IND  118       645      6
110529 -13       DL       731   N333NB  LGA    DTW   86       502      6
110530  -3       B6       939   N552JB  JFK    BQN  195      1576      5
110531  12       B6       353   N746JB  JFK    PBI  167      1028      6
110532   4       DL       904   N3741S  LGA    ATL  137       762      6
110533   2       UA       566   N491UA  EWR    TPA  164       997      5
110534  23       B6       583   N715JB  JFK    MCO  162       944      6
110535  -6       DL      1919   N958DL  LGA    MSP  160      1020      6
110536   0       EV      4241   N15574  EWR    DCA   45       199      6
110537  14       AA      1175   N3JEAA  LGA    MIA  173      1096      6
110538  22       B6       605   N597JB  EWR    FLL  167      1065      6
110539  38       AA      2243   N5EMAA  JFK    MIA  171      1089      5
110540 -21       DL      2505   N358NB  EWR    DTW   87       488      6
110541 -15       EV      6177   N14543  EWR    IAD   45       212      6
110542 -10       B6      1403   N547JB  JFK    SJU  198      1598      6
110543  23       WN      1716   N7740A  LGA    ATL  137       762      6
110544  -6       US      1963   N192UW  EWR    CLT  106       529      6
110545  -4       AA      1205   N5DHAA  EWR    MIA  163      1085      6
110546  -2       DL       404   N392DA  JFK    ATL  133       760      6
110547   4       EV      3812   N13994  EWR    RDU   81       416      6
110548 -21       DL       479   N3766   JFK    ATL  119       760      6
110549  21       B6       601   N643JB  JFK    FLL  173      1069      6
110550   3       B6      1099   N563JB  LGA    MCO  159       950      6
⋮      ⋮         ⋮       ⋮      ⋮       ⋮      ⋮    ⋮        ⋮        ⋮
111267  NA       B6      1205   N627JB  JFK    PDX   NA      2454     20
111268  19       B6      1901   N729JB  JFK    FLL  164      1069     21
111269   9       B6      2053   N593JB  JFK    PBI  155      1028     21
111270  65       B6       775   N184JB  JFK    MSY  195      1182     21
111271  15       B6      1183   N715JB  JFK    MCO  148       944     21
111272  11       B6      1203   N625JB  JFK    SJU  202      1598     22
111273  -4       B6       234   N355JB  JFK    BTV   49       266     22
111274   3       B6      1816   N318JB  JFK    SYR   51       209     22
111275  11       B6       718   N279JB  JFK    BOS   40       187     22
111276  38       B6      2002   N179JB  JFK    BUF   66       301     22
111277   3       B6      1389   N651JB  EWR    SJU  198      1608     23
111278  55       B6       486   N334JB  JFK    ROC   60       264     22
111279 -10       B6      1503   N509JB  JFK    SJU  195      1598     23
111280  -9       B6       745   N665JB  JFK    PSE  200      1617     23
111281  NA       AA       341   N568AA  LGA    ORD   NA       733     15
111282  NA       AA       371   N482AA  LGA    ORD   NA       733     20
111283  NA       B6       161   N516JB  JFK    SMF   NA      2521     19
111284  NA       EV      4181   N24103  EWR    MCI   NA      1092     15
111285  NA       UA      1124   NA      EWR    EGE   NA      1725     10
111286  NA       UA      1151   NA      EWR    SEA   NA      2402      8
111287  NA       UA      1455   NA      EWR    LAX   NA      2454      7
111288  NA       UA      1482   NA      EWR    ORD   NA       719     20
111289  NA       UA      1483   NA      EWR    AUS   NA      1504     15
111290  NA       UA      1493   NA      EWR    LAX   NA      2454     14
111291  NA       UA      1506   NA      EWR    JAC   NA      1874      8
111292  NA       UA      1729   NA      EWR    DEN   NA      1605      7
111293  NA       US      1831   NA      JFK    CLT   NA       541      8
111294  NA       MQ      3301   N844MQ  LGA    RDU   NA       431     16
111295  NA       UA       219   NA      EWR    ORD   NA       719      6
111296  NA       UA       443   NA      JFK    LAX   NA      2475      8
       minute time_hour
110521 59     2013-12-31 23:00:00
110522 59     2013-12-31 23:00:00
110523 45     2013-12-31 22:00:00
110524  0     2013-12-31 05:00:00
110525 15     2013-12-31 05:00:00
110526 51     2013-12-31 05:00:00
110527  0     2013-12-31 06:00:00
110528  0     2013-12-31 06:00:00
110529  0     2013-12-31 06:00:00
110530 50     2013-12-31 05:00:00
110531  0     2013-12-31 06:00:00
110532  0     2013-12-31 06:00:00
110533 51     2013-12-31 05:00:00
110534  0     2013-12-31 06:00:00
110535  5     2013-12-31 06:00:00
110536  3     2013-12-31 06:00:00
110537  0     2013-12-31 06:00:00
110538  0     2013-12-31 06:00:00
110539 40     2013-12-31 05:00:00
110540  5     2013-12-31 06:00:00
110541  5     2013-12-31 06:00:00
110542 11     2013-12-31 06:00:00
110543  0     2013-12-31 06:00:00
110544 15     2013-12-31 06:00:00
110545 10     2013-12-31 06:00:00
110546 15     2013-12-31 06:00:00
110547 14     2013-12-31 06:00:00
110548 15     2013-12-31 06:00:00
110549 11     2013-12-31 06:00:00
110550 30     2013-12-31 06:00:00
⋮      ⋮      ⋮
111267 39     2013-12-31 20:00:00
111268 50     2013-12-31 21:00:00
111269 55     2013-12-31 21:00:00
111270 10     2013-12-31 21:00:00
111271 59     2013-12-31 21:00:00
111272 19     2013-12-31 22:00:00
111273 45     2013-12-31 22:00:00
111274 50     2013-12-31 22:00:00
111275 55     2013-12-31 22:00:00
111276 50     2013-12-31 22:00:00
111277 30     2013-12-31 23:00:00
111278 45     2013-12-31 22:00:00
111279 59     2013-12-31 23:00:00
111280 59     2013-12-31 23:00:00
111281 20     2013-12-31 15:00:00
111282 25     2013-12-31 20:00:00
111283 32     2013-12-31 19:00:00
111284  5     2013-12-31 15:00:00
111285  0     2013-12-31 10:00:00
111286 40     2013-12-31 08:00:00
111287 54     2013-12-31 07:00:00
111288  0     2013-12-31 20:00:00
111289  0     2013-12-31 15:00:00
111290 30     2013-12-31 14:00:00
111291 55     2013-12-31 08:00:00
111292  5     2013-12-31 07:00:00
111293 25     2013-12-31 08:00:00
111294 15     2013-12-31 16:00:00
111295  0     2013-12-31 06:00:00
111296 30     2013-12-31 08:00:00

In [ ]:
# Ahora
filter(vuelos, month == 12 & day == 31)

    year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1   2013 12    31   13      2359            14        439      437
2   2013 12    31   18      2359            19        449      444
3   2013 12    31   26      2245           101        129     2353
4   2013 12    31  459       500            -1        655      651
5   2013 12    31  514       515            -1        814      812
6   2013 12    31  549       551            -2        925      900
7   2013 12    31  550       600           -10        725      745
8   2013 12    31  552       600            -8        811      826
9   2013 12    31  553       600            -7        741      754
10  2013 12    31  554       550             4       1024     1027
11  2013 12    31  555       600            -5        901      849
12  2013 12    31  555       600            -5        835      831
13  2013 12    31  555       551             4        853      851
14  2013 12    31  556       600            -4        909      846
15  2013 12    31  556       605            -9        808      814
16  2013 12    31  557       603            -6        719      719
17  2013 12    31  558       600            -2        919      905
18  2013 12    31  559       600            -1        917      855
19  2013 12    31  600       540            20        928      850
20  2013 12    31  602       605            -3        744      805
21  2013 12    31  602       605            -3        708      723
22  2013 12    31  603       611            -8       1045     1055
23  2013 12    31  607       600             7        848      825
24  2013 12    31  608       615            -7        812      818
25  2013 12    31  609       610            -1        911      915
26  2013 12    31  609       615            -6        848      850
27  2013 12    31  609       614            -5        755      751
28  2013 12    31  610       615            -5        828      849
29  2013 12    31  616       611             5        933      912
30  2013 12    31  616       630           -14        922      919
⋮   ⋮    ⋮     ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
747 2013 12    31  2155     2039            76        253     2355
748 2013 12    31  2155     2150             5        110       51
749 2013 12    31  2159     2155             4         55       46
750 2013 12    31  2206     2110            56         44     2339
751 2013 12    31  2211     2159            12        100       45
752 2013 12    31  2218     2219            -1        315      304
753 2013 12    31  2235     2245           -10       2351     2355
754 2013 12    31  2245     2250            -5       2359     2356
755 2013 12    31  2310     2255            15          7     2356
756 2013 12    31  2321     2250            31         46        8
757 2013 12    31  2328     2330            -2        412      409
758 2013 12    31  2332     2245            47         58        3
759 2013 12    31  2355     2359            -4        430      440
760 2013 12    31  2356     2359            -3        436      445
761 2013 12    31    NA     1520            NA         NA     1705
762 2013 12    31    NA     2025            NA         NA     2205
763 2013 12    31    NA     1932            NA         NA     2305
764 2013 12    31    NA     1505            NA         NA     1725
765 2013 12    31    NA     1000            NA         NA     1252
766 2013 12    31    NA      840            NA         NA     1205
767 2013 12    31    NA      754            NA         NA     1118
768 2013 12    31    NA     2000            NA         NA     2146
769 2013 12    31    NA     1500            NA         NA     1817
770 2013 12    31    NA     1430            NA         NA     1750
771 2013 12    31    NA      855            NA         NA     1142
772 2013 12    31    NA      705            NA         NA      931
773 2013 12    31    NA      825            NA         NA     1029
774 2013 12    31    NA     1615            NA         NA     1800
775 2013 12    31    NA      600            NA         NA      735
776 2013 12    31    NA      830            NA         NA     1154
    arr_delay carrier flight tailnum origin dest air_time distance hour minute
1     2       B6       839   N566JB  JFK    BQN  189      1576     23   59
2     5       DL       412   N713TW  JFK    SJU  192      1598     23   59
3    96       B6       108   N374JB  JFK    PWM   50       273     22   45
4     4       US      1895   N557UW  EWR    CLT   95       529      5    0
5     2       UA       700   N470UA  EWR    IAH  223      1400      5   15
6    25       UA       274   N577UA  EWR    LAX  346      2454      5   51
7   -20       AA       301   N3CXAA  LGA    ORD  127       733      6    0
8   -15       EV      3825   N14916  EWR    IND  118       645      6    0
9   -13       DL       731   N333NB  LGA    DTW   86       502      6    0
10   -3       B6       939   N552JB  JFK    BQN  195      1576      5   50
11   12       B6       353   N746JB  JFK    PBI  167      1028      6    0
12    4       DL       904   N3741S  LGA    ATL  137       762      6    0
13    2       UA       566   N491UA  EWR    TPA  164       997      5   51
14   23       B6       583   N715JB  JFK    MCO  162       944      6    0
15   -6       DL      1919   N958DL  LGA    MSP  160      1020      6    5
16    0       EV      4241   N15574  EWR    DCA   45       199      6    3
17   14       AA      1175   N3JEAA  LGA    MIA  173      1096      6    0
18   22       B6       605   N597JB  EWR    FLL  167      1065      6    0
19   38       AA      2243   N5EMAA  JFK    MIA  171      1089      5   40
20  -21       DL      2505   N358NB  EWR    DTW   87       488      6    5
21  -15       EV      6177   N14543  EWR    IAD   45       212      6    5
22  -10       B6      1403   N547JB  JFK    SJU  198      1598      6   11
23   23       WN      1716   N7740A  LGA    ATL  137       762      6    0
24   -6       US      1963   N192UW  EWR    CLT  106       529      6   15
25   -4       AA      1205   N5DHAA  EWR    MIA  163      1085      6   10
26   -2       DL       404   N392DA  JFK    ATL  133       760      6   15
27    4       EV      3812   N13994  EWR    RDU   81       416      6   14
28  -21       DL       479   N3766   JFK    ATL  119       760      6   15
29   21       B6       601   N643JB  JFK    FLL  173      1069      6   11
30    3       B6      1099   N563JB  LGA    MCO  159       950      6   30
⋮   ⋮         ⋮       ⋮      ⋮       ⋮      ⋮    ⋮        ⋮        ⋮    ⋮
747  NA       B6      1205   N627JB  JFK    PDX   NA      2454     20   39
748  19       B6      1901   N729JB  JFK    FLL  164      1069     21   50
749   9       B6      2053   N593JB  JFK    PBI  155      1028     21   55
750  65       B6       775   N184JB  JFK    MSY  195      1182     21   10
751  15       B6      1183   N715JB  JFK    MCO  148       944     21   59
752  11       B6      1203   N625JB  JFK    SJU  202      1598     22   19
753  -4       B6       234   N355JB  JFK    BTV   49       266     22   45
754   3       B6      1816   N318JB  JFK    SYR   51       209     22   50
755  11       B6       718   N279JB  JFK    BOS   40       187     22   55
756  38       B6      2002   N179JB  JFK    BUF   66       301     22   50
757   3       B6      1389   N651JB  EWR    SJU  198      1608     23   30
758  55       B6       486   N334JB  JFK    ROC   60       264     22   45
759 -10       B6      1503   N509JB  JFK    SJU  195      1598     23   59
760  -9       B6       745   N665JB  JFK    PSE  200      1617     23   59
761  NA       AA       341   N568AA  LGA    ORD   NA       733     15   20
762  NA       AA       371   N482AA  LGA    ORD   NA       733     20   25
763  NA       B6       161   N516JB  JFK    SMF   NA      2521     19   32
764  NA       EV      4181   N24103  EWR    MCI   NA      1092     15    5
765  NA       UA      1124   NA      EWR    EGE   NA      1725     10    0
766  NA       UA      1151   NA      EWR    SEA   NA      2402      8   40
767  NA       UA      1455   NA      EWR    LAX   NA      2454      7   54
768  NA       UA      1482   NA      EWR    ORD   NA       719     20    0
769  NA       UA      1483   NA      EWR    AUS   NA      1504     15    0
770  NA       UA      1493   NA      EWR    LAX   NA      2454     14   30
771  NA       UA      1506   NA      EWR    JAC   NA      1874      8   55
772  NA       UA      1729   NA      EWR    DEN   NA      1605      7    5
773  NA       US      1831   NA      JFK    CLT   NA       541      8   25
774  NA       MQ      3301   N844MQ  LGA    RDU   NA       431     16   15
775  NA       UA       219   NA      EWR    ORD   NA       719      6    0
776  NA       UA       443   NA      JFK    LAX   NA      2475      8   30
    time_hour
1   2013-12-31 23:00:00
2   2013-12-31 23:00:00
3   2013-12-31 22:00:00
4   2013-12-31 05:00:00
5   2013-12-31 05:00:00
6   2013-12-31 05:00:00
7   2013-12-31 06:00:00
8   2013-12-31 06:00:00
9   2013-12-31 06:00:00
10  2013-12-31 05:00:00
11  2013-12-31 06:00:00
12  2013-12-31 06:00:00
13  2013-12-31 05:00:00
14  2013-12-31 06:00:00
15  2013-12-31 06:00:00
16  2013-12-31 06:00:00
17  2013-12-31 06:00:00
18  2013-12-31 06:00:00
19  2013-12-31 05:00:00
20  2013-12-31 06:00:00
21  2013-12-31 06:00:00
22  2013-12-31 06:00:00
23  2013-12-31 06:00:00
24  2013-12-31 06:00:00
25  2013-12-31 06:00:00
26  2013-12-31 06:00:00
27  2013-12-31 06:00:00
28  2013-12-31 06:00:00
29  2013-12-31 06:00:00
30  2013-12-31 06:00:00
⋮   ⋮
747 2013-12-31 20:00:00
748 2013-12-31 21:00:00
749 2013-12-31 21:00:00
750 2013-12-31 21:00:00
751 2013-12-31 21:00:00
752 2013-12-31 22:00:00
753 2013-12-31 22:00:00
754 2013-12-31 22:00:00
755 2013-12-31 22:00:00
756 2013-12-31 22:00:00
757 2013-12-31 23:00:00
758 2013-12-31 22:00:00
759 2013-12-31 23:00:00
760 2013-12-31 23:00:00
761 2013-12-31 15:00:00
762 2013-12-31 20:00:00
763 2013-12-31 19:00:00
764 2013-12-31 15:00:00
765 2013-12-31 10:00:00
766 2013-12-31 08:00:00
767 2013-12-31 07:00:00
768 2013-12-31 20:00:00
769 2013-12-31 15:00:00
770 2013-12-31 14:00:00
771 2013-12-31 08:00:00
772 2013-12-31 07:00:00
773 2013-12-31 08:00:00
774 2013-12-31 16:00:00
775 2013-12-31 06:00:00
776 2013-12-31 08:00:00

### 4.2 Función count()

Como su nombre lo indica, esta función nos permite contar registros de una tabla. Es de suma utilidad cuando se utiliza dentro de agrupaciones de tablas. Estas últimas las veremos más adelante.

Alternativamente, en la librería _dplyr_, contamos con la función `N()` la cual también retorna el conteo de registros.

In [ ]:
# Ej. Cuántos vuelos hay por aeropuerto de origen
count(vuelos, origin)

  origin n
1 EWR    120835
2 JFK    111279
3 LGA    104662

In [ ]:
# Total de vuelos por (año) mes y día
count(vuelos, year, month, day)

    year month day n
1   2013 1      1  842
2   2013 1      2  943
3   2013 1      3  914
4   2013 1      4  915
5   2013 1      5  720
6   2013 1      6  832
7   2013 1      7  933
8   2013 1      8  899
9   2013 1      9  902
10  2013 1     10  932
11  2013 1     11  930
12  2013 1     12  690
13  2013 1     13  828
14  2013 1     14  928
15  2013 1     15  894
16  2013 1     16  901
17  2013 1     17  927
18  2013 1     18  924
19  2013 1     19  674
20  2013 1     20  786
21  2013 1     21  912
22  2013 1     22  890
23  2013 1     23  897
24  2013 1     24  925
25  2013 1     25  922
26  2013 1     26  680
27  2013 1     27  823
28  2013 1     28  923
29  2013 1     29  890
30  2013 1     30  900
⋮   ⋮    ⋮     ⋮   ⋮
336 2013 12     2  1004
337 2013 12     3   973
338 2013 12     4   958
339 2013 12     5   969
340 2013 12     6   970
341 2013 12     7   691
342 2013 12     8   875
343 2013 12     9   962
344 2013 12    10   943
345 2013 12    11   954
346 2013 12    12   968
347 2013 12    13   970
348 2013 12    14   692
349 2013 12    15   880
350 2013 12    16   964
351 2013 12    17   949
352 2013 12    18   956
353 2013 12    19   974
354 2013 12    20   980
355 2013 12    21   811
356 2013 12    22   895
357 2013 12    23   985
358 2013 12    24   761
359 2013 12    25   719
360 2013 12    26   936
361 2013 12    27   963
362 2013 12    28   814
363 2013 12    29   888
364 2013 12    30   968
365 2013 12    31   776

In [ ]:
# count() y N() ----------------------------------------------------------------
# ¿Cuántos vuelos hay registrados para el 25 de dic?¿y el primero de enero?
filter(count(vuelos, year, month, day), (day == 25 & month == 12) | (day == 1 & month == 1) )
# El 25 de dic, se registraron 719 vuelos y 842 el 1 de enero.-

  year month day n
1 2013  1     1  842
2 2013 12    25  719

In [7]:
getwd()

[1] "/content"

In [6]:
#si quisiéramos guardar resgidtros en el disco, una manera es usando write.csv()
resumen_diario <- count(vuelos, year, month, day)
write.csv(resumen_diario, file = "vuelos_diarios.csv", row.names = F)

In [8]:
str(vuelos)

'data.frame':	336776 obs. of  19 variables:
 $ year          : int  2013 2013 2013 2013 2013 2013 2013 2013 2013 2013 ...
 $ month         : int  1 1 1 1 1 1 1 1 1 1 ...
 $ day           : int  1 1 1 1 1 1 1 1 1 1 ...
 $ dep_time      : int  517 533 542 544 554 554 555 557 557 558 ...
 $ sched_dep_time: int  515 529 540 545 600 558 600 600 600 600 ...
 $ dep_delay     : int  2 4 2 -1 -6 -4 -5 -3 -3 -2 ...
 $ arr_time      : int  830 850 923 1004 812 740 913 709 838 753 ...
 $ sched_arr_time: int  819 830 850 1022 837 728 854 723 846 745 ...
 $ arr_delay     : int  11 20 33 -18 -25 12 19 -14 -8 8 ...
 $ carrier       : chr  "UA" "UA" "AA" "B6" ...
 $ flight        : int  1545 1714 1141 725 461 1696 507 5708 79 301 ...
 $ tailnum       : chr  "N14228" "N24211" "N619AA" "N804JB" ...
 $ origin        : chr  "EWR" "LGA" "JFK" "JFK" ...
 $ dest          : chr  "IAH" "IAH" "MIA" "BQN" ...
 $ air_time      : int  227 227 160 183 116 150 158 53 140 138 ...
 $ distance      : int  1400 1416 1089 1576 762 719 1065 229 944 733 ...
 $ hour          : int  5 5 5 5 6 5 6 6 6 6 ...
 $ minute        : int  15 29 40 45 0 58 0 0 0 0 ...
 $ time_hour     : chr  "2013-01-01 05:00:00" "2013-01-01 05:00:00" "2013-01-01 05:00:00" "2013-01-01 05:00:00" ...

In [12]:
# ¿Cuántos vuelos hay registrados entre noviembre y diciembre?¿A qué porcentaje del total corresponde?
total_nove_dic <- nrow(filter(vuelos, month >= 11))
nrow(filter(vuelos, month %in% c(11,12)))

[1] 55403

In [16]:
paste0(100*round(total_nove_dic / nrow(vuelos),2) ,"%")

[1] "16%"

In [ ]:
# ¿Qué porcentaje de vuelos tienen un retraso  (de salida o llegada) mayor a una hora?

#columnas arr_delay o dep_delay

In [ ]:
# ¿Cuántos vuelos llegaron con al menos dos horas de retraso pero no se retrasaron al partir?

### 4.3 Función arrange()

Esta función nos permite ordernar registros basándose en la indexación de alguna columna. Es el equivalente a la sentencia `order by` en sql.
Esta función recibe como argumento principal un dataset a ordenar, y los nombres de las columnas por las cuales se quiere ordenar. Para más información consultar la ayuda de esta función (?arrange)

In [17]:
# arrange() ----------------------------------------------------------------
# Ejemplo, podemos ordenar la data flights por mes y arr_delay
arrange(vuelos, month, arr_delay) # El ordenamiento es ascendente por defecto (de menor a mayor)

       year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1      2013 1      4  1026     1030            -4       1305     1415
2      2013 1      3   941      945            -4       1153     1258
3      2013 1     14  1840     1845            -5       2117     2221
4      2013 1      3  1153     1200            -7       1442     1545
5      2013 1      3  1228     1235            -7       1503     1606
6      2013 1     27  1845     1850            -5       2110     2212
7      2013 1      3  1605     1610            -5       1816     1917
8      2013 1      3  1857     1900            -3       2200     2301
9      2013 1      4  1219     1221            -2       1454     1555
10     2013 1      6   812      819            -7       1102     1203
11     2013 1     12   913      920            -7       1347     1448
12     2013 1      3  1920     1920             0       2158     2258
13     2013 1      2   654      700            -6        946     1045
14     2013 1      3  1626     1630            -4       1853     1952
15     2013 1     27  1839     1845            -6       2038     2137
16     2013 1     26  1651     1659            -8       1946     2044
17     2013 1      2   857      900            -3       1130     1227
18     2013 1      3  1957     1945            12       2232     2329
19     2013 1      4   650      655            -5        933     1030
20     2013 1      4   829      830            -1       1113     1210
21     2013 1      4  1657     1700            -3       1952     2049
22     2013 1     30  1915     1915             0       2133     2230
23     2013 1      3  1806     1810            -4       2036     2132
24     2013 1      3  1919     1920            -1       2219     2315
25     2013 1     14  1838     1850           -12       2116     2212
26     2013 1      2  1240     1245            -5       1521     1616
27     2013 1      4  1118     1130           -12       1350     1445
28     2013 1      8  1847     1850            -3       2117     2212
29     2013 1     11  1845     1850            -5       2117     2212
30     2013 1     13   723      730            -7       1020     1115
⋮      ⋮    ⋮     ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
336747 2013 12    30    NA     1635           NA         NA      1825
336748 2013 12    30    NA      600           NA         NA       855
336749 2013 12    30    NA     1430           NA         NA      1626
336750 2013 12    30    NA     1350           NA         NA      1602
336751 2013 12    30    NA     1452           NA         NA      1559
336752 2013 12    30    NA     1935           NA         NA      2055
336753 2013 12    30    NA     1011           NA         NA      1134
336754 2013 12    30    NA      605           NA         NA       723
336755 2013 12    30    NA     1505           NA         NA      1759
336756 2013 12    30    NA     1355           NA         NA      1535
336757 2013 12    30    NA     2100           NA         NA        48
336758 2013 12    30    NA     1221           NA         NA      1545
336759 2013 12    30    NA      855           NA         NA      1142
336760 2013 12    31  2155     2039           76        253      2355
336761 2013 12    31    NA     1520           NA         NA      1705
336762 2013 12    31    NA     2025           NA         NA      2205
336763 2013 12    31    NA     1932           NA         NA      2305
336764 2013 12    31    NA     1505           NA         NA      1725
336765 2013 12    31    NA     1000           NA         NA      1252
336766 2013 12    31    NA      840           NA         NA      1205
336767 2013 12    31    NA      754           NA         NA      1118
336768 2013 12    31    NA     2000           NA         NA      2146
336769 2013 12    31    NA     1500           NA         NA      1817
336770 2013 12    31    NA     1430           NA         NA      1750
336771 2013 12    31    NA      855           NA         NA      1142
336772 2013 12    31    NA      705           NA         NA       931
336773 2013 12    31    NA      825           NA         NA      1029
336774 2013 12    31    NA     1615           NA         NA      1800
336775 2013 12    31    NA      600           NA         NA       735
336776 2013 12    31    NA      830           NA         NA      1154
       arr_delay carrier flight tailnum origin dest air_time distance hour
1      -70       VX        23   N855VA  JFK    SFO  324      2586     10
2      -65       B6       679   N789JB  JFK    LAX  297      2475      9
3      -64       DL      2190   N324US  JFK    MIA  146      1089     18
4      -63       VX        25   N847VA  JFK    SFO  333      2586     12
5      -63       DL      2174   N389DA  JFK    SLC  260      1990     12
6      -62       DL      2159   N398DA  JFK    MCO  127       944     18
7      -61       DL        91   N3740C  JFK    LAS  282      2248     16
8      -61       DL      1465   N722TW  JFK    SFO  329      2586     19
9      -61       UA       551   N830UA  EWR    SFO  313      2565     12
10     -61       UA       665   N805UA  EWR    SFO  336      2565      8
11     -61       DL       675   N711ZX  JFK    STT  181      1623      9
12     -60       DL         6   N3768   JFK    SLC  250      1990     19
13     -59       DL      1865   N711ZX  JFK    SFO  323      2586      7
14     -59       B6       675   N652JB  JFK    LAX  301      2475     16
15     -59       9E      3369   N919XJ  JFK    MSY  166      1182     18
16     -58       9E      3375   N930XJ  JFK    SAT  214      1587     16
17     -57       DL       120   N710TW  JFK    LAX  310      2475      9
18     -57       B6       645   N793JB  JFK    SFO  315      2586     19
19     -57       DL      1415   N397DA  JFK    SLC  265      1990      6
20     -57       UA      1480   N36207  EWR    SFO  326      2565      8
21     -57       DL        31   N722TW  JFK    SFO  326      2586     17
22     -57       DL      1729   N3754A  JFK    LAS  294      2248     19
23     -56       B6       217   N559JB  JFK    LGB  293      2465     18
24     -56       DL      1345   N3769L  JFK    PHX  273      2153     19
25     -56       DL      2159   N384DA  JFK    MCO  135       944     18
26     -55       DL      2174   N3751B  JFK    SLC  264      1990     12
27     -55       UA       703   N512UA  JFK    LAX  309      2475     11
28     -55       DL      2159   N386DA  JFK    MCO  132       944     18
29     -55       DL      2159   N3768   JFK    MCO  125       944     18
30     -55       VX        11   N841VA  JFK    SFO  339      2586      7
⋮      ⋮         ⋮       ⋮      ⋮       ⋮      ⋮    ⋮        ⋮        ⋮
336747 NA        AA       343   N4XVAA  LGA    ORD  NA        733     16
336748 NA        B6       605   N708JB  EWR    FLL  NA       1065      6
336749 NA        EV      4261   N27200  LGA    CLE  NA        419     14
336750 NA        EV      4193   N36915  EWR    MSP  NA       1008     13
336751 NA        EV      4372   N14573  EWR    DCA  NA        199     14
336752 NA        EV      5714   N832AS  JFK    IAD  NA        228     19
336753 NA        EV      6054   N16919  EWR    IAD  NA        212     10
336754 NA        EV      6177   N13553  EWR    IAD  NA        212      6
336755 NA        UA       321   NA      EWR    MCO  NA        937     15
336756 NA        MQ      3305   N821MQ  LGA    RDU  NA        431     13
336757 NA        UA      1081   NA      EWR    SFO  NA       2565     21
336758 NA        UA      1297   NA      EWR    SNA  NA       2434     12
336759 NA        UA      1506   NA      EWR    JAC  NA       1874      8
336760 NA        B6      1205   N627JB  JFK    PDX  NA       2454     20
336761 NA        AA       341   N568AA  LGA    ORD  NA        733     15
336762 NA        AA       371   N482AA  LGA    ORD  NA        733     20
336763 NA        B6       161   N516JB  JFK    SMF  NA       2521     19
336764 NA        EV      4181   N24103  EWR    MCI  NA       1092     15
336765 NA        UA      1124   NA      EWR    EGE  NA       1725     10
336766 NA        UA      1151   NA      EWR    SEA  NA       2402      8
336767 NA        UA      1455   NA      EWR    LAX  NA       2454      7
336768 NA        UA      1482   NA      EWR    ORD  NA        719     20
336769 NA        UA      1483   NA      EWR    AUS  NA       1504     15
336770 NA        UA      1493   NA      EWR    LAX  NA       2454     14
336771 NA        UA      1506   NA      EWR    JAC  NA       1874      8
336772 NA        UA      1729   NA      EWR    DEN  NA       1605      7
336773 NA        US      1831   NA      JFK    CLT  NA        541      8
336774 NA        MQ      3301   N844MQ  LGA    RDU  NA        431     16
336775 NA        UA       219   NA      EWR    ORD  NA        719      6
336776 NA        UA       443   NA      JFK    LAX  NA       2475      8
       minute time_hour
1      30     2013-01-04 10:00:00
2      45     2013-01-03 09:00:00
3      45     2013-01-14 18:00:00
4       0     2013-01-03 12:00:00
5      35     2013-01-03 12:00:00
6      50     2013-01-27 18:00:00
7      10     2013-01-03 16:00:00
8       0     2013-01-03 19:00:00
9      21     2013-01-04 12:00:00
10     19     2013-01-06 08:00:00
11     20     2013-01-12 09:00:00
12     20     2013-01-03 19:00:00
13      0     2013-01-02 07:00:00
14     30     2013-01-03 16:00:00
15     45     2013-01-27 18:00:00
16     59     2013-01-26 16:00:00
17      0     2013-01-02 09:00:00
18     45     2013-01-03 19:00:00
19     55     2013-01-04 06:00:00
20     30     2013-01-04 08:00:00
21      0     2013-01-04 17:00:00
22     15     2013-01-30 19:00:00
23     10     2013-01-03 18:00:00
24     20     2013-01-03 19:00:00
25     50     2013-01-14 18:00:00
26     45     2013-01-02 12:00:00
27     30     2013-01-04 11:00:00
28     50     2013-01-08 18:00:00
29     50     2013-01-11 18:00:00
30     30     2013-01-13 07:00:00
⋮      ⋮      ⋮
336747 35     2013-12-30 16:00:00
336748  0     2013-12-30 06:00:00
336749 30     2013-12-30 14:00:00
336750 50     2013-12-30 13:00:00
336751 52     2013-12-30 14:00:00
336752 35     2013-12-30 19:00:00
336753 11     2013-12-30 10:00:00
336754  5     2013-12-30 06:00:00
336755  5     2013-12-30 15:00:00
336756 55     2013-12-30 13:00:00
336757  0     2013-12-30 21:00:00
336758 21     2013-12-30 12:00:00
336759 55     2013-12-30 08:00:00
336760 39     2013-12-31 20:00:00
336761 20     2013-12-31 15:00:00
336762 25     2013-12-31 20:00:00
336763 32     2013-12-31 19:00:00
336764  5     2013-12-31 15:00:00
336765  0     2013-12-31 10:00:00
336766 40     2013-12-31 08:00:00
336767 54     2013-12-31 07:00:00
336768  0     2013-12-31 20:00:00
336769  0     2013-12-31 15:00:00
336770 30     2013-12-31 14:00:00
336771 55     2013-12-31 08:00:00
336772  5     2013-12-31 07:00:00
336773 25     2013-12-31 08:00:00
336774 15     2013-12-31 16:00:00
336775  0     2013-12-31 06:00:00
336776 30     2013-12-31 08:00:00

In [18]:
arrange(vuelos, month, desc(arr_delay) ) # Ordena de menor a mayor por month y de mayor a menor por arr_delay

       year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1      2013 1      9   641      900           1301      1242     1530
2      2013 1     10  1121     1635           1126      1239     1810
3      2013 1      1   848     1835            853      1001     1950
4      2013 1     13  1809      810            599      2054     1042
5      2013 1     16  1622      800            502      1911     1054
6      2013 1     23  1551      753            478      1812     1006
7      2013 1      1  2343     1724            379       314     1938
8      2013 1     10  1525      900            385      1713     1039
9      2013 1     25    15     1815            360       208     1958
10     2013 1      2  1607     1030            337      2003     1355
11     2013 1      7  2021     1415            366      2332     1724
12     2013 1     25  2020     1527            293      2304     1700
13     2013 1      2  2131     1512            379      2340     1741
14     2013 1     26  1409      820            349      1528      937
15     2013 1     11  1310      710            360      1438      850
16     2013 1     24  2051     1522            329      2307     1727
17     2013 1      1  1815     1325            290      2120     1542
18     2013 1     25  2203     1635            328        34     1856
19     2013 1     31  1837     1350            287      2159     1624
20     2013 1     25    26     1850            336       225     2055
21     2013 1     14  2229     1655            334       157     2029
22     2013 1     25   123     2000            323       229     2101
23     2013 1     25  2036     1610            266      2257     1732
24     2013 1      2  1412      838            334      1710     1147
25     2013 1      5  1344      817            327      1635     1127
26     2013 1     16  2013     1505            308      2136     1637
27     2013 1     25  1755     1341            254        34     1935
28     2013 1     13   115     2000            315       409     2312
29     2013 1     28  1857     1429            268      2136     1642
30     2013 1     10  2137     1630            307        17     1925
⋮      ⋮    ⋮     ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
336747 2013 12    30    NA     1635           NA         NA      1825
336748 2013 12    30    NA      600           NA         NA       855
336749 2013 12    30    NA     1430           NA         NA      1626
336750 2013 12    30    NA     1350           NA         NA      1602
336751 2013 12    30    NA     1452           NA         NA      1559
336752 2013 12    30    NA     1935           NA         NA      2055
336753 2013 12    30    NA     1011           NA         NA      1134
336754 2013 12    30    NA      605           NA         NA       723
336755 2013 12    30    NA     1505           NA         NA      1759
336756 2013 12    30    NA     1355           NA         NA      1535
336757 2013 12    30    NA     2100           NA         NA        48
336758 2013 12    30    NA     1221           NA         NA      1545
336759 2013 12    30    NA      855           NA         NA      1142
336760 2013 12    31  2155     2039           76        253      2355
336761 2013 12    31    NA     1520           NA         NA      1705
336762 2013 12    31    NA     2025           NA         NA      2205
336763 2013 12    31    NA     1932           NA         NA      2305
336764 2013 12    31    NA     1505           NA         NA      1725
336765 2013 12    31    NA     1000           NA         NA      1252
336766 2013 12    31    NA      840           NA         NA      1205
336767 2013 12    31    NA      754           NA         NA      1118
336768 2013 12    31    NA     2000           NA         NA      2146
336769 2013 12    31    NA     1500           NA         NA      1817
336770 2013 12    31    NA     1430           NA         NA      1750
336771 2013 12    31    NA      855           NA         NA      1142
336772 2013 12    31    NA      705           NA         NA       931
336773 2013 12    31    NA      825           NA         NA      1029
336774 2013 12    31    NA     1615           NA         NA      1800
336775 2013 12    31    NA      600           NA         NA       735
336776 2013 12    31    NA      830           NA         NA      1154
       arr_delay carrier flight tailnum origin dest air_time distance hour
1      1272      HA        51   N384HA  JFK    HNL  640      4983      9
2      1109      MQ      3695   N517MQ  EWR    ORD  111       719     16
3       851      MQ      3944   N942MQ  JFK    BWI   41       184     18
4       612      DL       269   N322NB  JFK    ATL  116       760      8
5       497      B6       517   N661JB  EWR    MCO  144       937      8
6       486      DL      2119   N326NB  LGA    MSP  166      1020      7
7       456      EV      4321   N21197  EWR    MCI  222      1092     17
8       394      UA       544   N419UA  LGA    ORD  123       733      9
9       370      9E      4019   N8646A  JFK    RIC   56       288     18
10      368      AA       179   N324AA  JFK    SFO  346      2586     10
11      368      B6       377   N789JB  LGA    FLL  153      1076     14
12      364      EV      3835   N14920  EWR    BNA  124       748     15
13      359      UA       488   N593UA  LGA    DEN  228      1620     15
14      351      9E      4051   N8444F  JFK    BWI   37       184      8
15      348      MQ      3737   N509MQ  EWR    ORD  116       719      7
16      340      EV      4576   N21144  EWR    GRR  107       605     15
17      338      EV      4417   N17185  EWR    OMA  213      1134     13
18      338      EV      3805   N18102  EWR    SAV  107       708     16
19      335      B6       615   N281JB  JFK    JAX  150       828     13
20      330      US      1491   N181UW  LGA    CLT   82       544     18
21      328      DL       706   N370NW  JFK    AUS  243      1521     16
22      328      EV      4309   N13908  EWR    ALB   30       143     20
23      325      9E      3689   N8913A  JFK    PHL   27        94     16
24      323      UA       468   N474UA  EWR    MCO  150       937      8
25      308      DL      1109   N309US  LGA    TPA  158      1010      8
26      299      9E      3393   N920XJ  JFK    DCA   51       213     15
27      299      UA        15   N76065  EWR    HNL  648      4963     13
28      297      B6       801   N552JB  JFK    FLL  143      1069     20
29      294      DL      1819   N911DA  LGA    MSP  162      1020     14
30      292      UA      1178   N75435  EWR    IAH  197      1400     16
⋮      ⋮         ⋮       ⋮      ⋮       ⋮      ⋮    ⋮        ⋮        ⋮
336747 NA        AA       343   N4XVAA  LGA    ORD  NA        733     16
336748 NA        B6       605   N708JB  EWR    FLL  NA       1065      6
336749 NA        EV      4261   N27200  LGA    CLE  NA        419     14
336750 NA        EV      4193   N36915  EWR    MSP  NA       1008     13
336751 NA        EV      4372   N14573  EWR    DCA  NA        199     14
336752 NA        EV      5714   N832AS  JFK    IAD  NA        228     19
336753 NA        EV      6054   N16919  EWR    IAD  NA        212     10
336754 NA        EV      6177   N13553  EWR    IAD  NA        212      6
336755 NA        UA       321   NA      EWR    MCO  NA        937     15
336756 NA        MQ      3305   N821MQ  LGA    RDU  NA        431     13
336757 NA        UA      1081   NA      EWR    SFO  NA       2565     21
336758 NA        UA      1297   NA      EWR    SNA  NA       2434     12
336759 NA        UA      1506   NA      EWR    JAC  NA       1874      8
336760 NA        B6      1205   N627JB  JFK    PDX  NA       2454     20
336761 NA        AA       341   N568AA  LGA    ORD  NA        733     15
336762 NA        AA       371   N482AA  LGA    ORD  NA        733     20
336763 NA        B6       161   N516JB  JFK    SMF  NA       2521     19
336764 NA        EV      4181   N24103  EWR    MCI  NA       1092     15
336765 NA        UA      1124   NA      EWR    EGE  NA       1725     10
336766 NA        UA      1151   NA      EWR    SEA  NA       2402      8
336767 NA        UA      1455   NA      EWR    LAX  NA       2454      7
336768 NA        UA      1482   NA      EWR    ORD  NA        719     20
336769 NA        UA      1483   NA      EWR    AUS  NA       1504     15
336770 NA        UA      1493   NA      EWR    LAX  NA       2454     14
336771 NA        UA      1506   NA      EWR    JAC  NA       1874      8
336772 NA        UA      1729   NA      EWR    DEN  NA       1605      7
336773 NA        US      1831   NA      JFK    CLT  NA        541      8
336774 NA        MQ      3301   N844MQ  LGA    RDU  NA        431     16
336775 NA        UA       219   NA      EWR    ORD  NA        719      6
336776 NA        UA       443   NA      JFK    LAX  NA       2475      8
       minute time_hour
1       0     2013-01-09 09:00:00
2      35     2013-01-10 16:00:00
3      35     2013-01-01 18:00:00
4      10     2013-01-13 08:00:00
5       0     2013-01-16 08:00:00
6      53     2013-01-23 07:00:00
7      24     2013-01-01 17:00:00
8       0     2013-01-10 09:00:00
9      15     2013-01-25 18:00:00
10     30     2013-01-02 10:00:00
11     15     2013-01-07 14:00:00
12     27     2013-01-25 15:00:00
13     12     2013-01-02 15:00:00
14     20     2013-01-26 08:00:00
15     10     2013-01-11 07:00:00
16     22     2013-01-24 15:00:00
17     25     2013-01-01 13:00:00
18     35     2013-01-25 16:00:00
19     50     2013-01-31 13:00:00
20     50     2013-01-25 18:00:00
21     55     2013-01-14 16:00:00
22      0     2013-01-25 20:00:00
23     10     2013-01-25 16:00:00
24     38     2013-01-02 08:00:00
25     17     2013-01-05 08:00:00
26      5     2013-01-16 15:00:00
27     41     2013-01-25 13:00:00
28      0     2013-01-13 20:00:00
29     29     2013-01-28 14:00:00
30     30     2013-01-10 16:00:00
⋮      ⋮      ⋮
336747 35     2013-12-30 16:00:00
336748  0     2013-12-30 06:00:00
336749 30     2013-12-30 14:00:00
336750 50     2013-12-30 13:00:00
336751 52     2013-12-30 14:00:00
336752 35     2013-12-30 19:00:00
336753 11     2013-12-30 10:00:00
336754  5     2013-12-30 06:00:00
336755  5     2013-12-30 15:00:00
336756 55     2013-12-30 13:00:00
336757  0     2013-12-30 21:00:00
336758 21     2013-12-30 12:00:00
336759 55     2013-12-30 08:00:00
336760 39     2013-12-31 20:00:00
336761 20     2013-12-31 15:00:00
336762 25     2013-12-31 20:00:00
336763 32     2013-12-31 19:00:00
336764  5     2013-12-31 15:00:00
336765  0     2013-12-31 10:00:00
336766 40     2013-12-31 08:00:00
336767 54     2013-12-31 07:00:00
336768  0     2013-12-31 20:00:00
336769  0     2013-12-31 15:00:00
336770 30     2013-12-31 14:00:00
336771 55     2013-12-31 08:00:00
336772  5     2013-12-31 07:00:00
336773 25     2013-12-31 08:00:00
336774 15     2013-12-31 16:00:00
336775  0     2013-12-31 06:00:00
336776 30     2013-12-31 08:00:00

### 4.3 Funciones select() y rename()

La con la función `select` podemos seleccionar un subconjunto de columas de la tabla original. A difernecia de SQL en esta sentencia no podremos crear nuevas columnas, sólo renombrarlas en algunos casos. Notar que (obviamente) no se mantienen las columnas que no ingresan como argumento a la función.

La función rename() permite renombrar columnas existentes, manteniendo las columnas que no se están renombrando.

In [19]:
# select() y rename() ----------------------------------------------------------------
# Ejemplo: Podemos seleccionar las columnas year, month, day, origin, dest

# Cómo lo haríamos con la sintaxis básica? (recorr como acceder a través del nombre a un vector, matrix, lista, o data.frame)
vuelos[, c("year", "month", "day", "origin", "dest")] # Pensando como una matriz
vuelos[c("year", "month", "day", "origin", "dest")] # Pensando como una lista

       year month day origin dest
1      2013 1     1   EWR    IAH
2      2013 1     1   LGA    IAH
3      2013 1     1   JFK    MIA
4      2013 1     1   JFK    BQN
5      2013 1     1   LGA    ATL
6      2013 1     1   EWR    ORD
7      2013 1     1   EWR    FLL
8      2013 1     1   LGA    IAD
9      2013 1     1   JFK    MCO
10     2013 1     1   LGA    ORD
11     2013 1     1   JFK    PBI
12     2013 1     1   JFK    TPA
13     2013 1     1   JFK    LAX
14     2013 1     1   EWR    SFO
15     2013 1     1   LGA    DFW
16     2013 1     1   JFK    BOS
17     2013 1     1   EWR    LAS
18     2013 1     1   LGA    FLL
19     2013 1     1   LGA    ATL
20     2013 1     1   EWR    PBI
21     2013 1     1   LGA    MSP
22     2013 1     1   LGA    DTW
23     2013 1     1   EWR    MIA
24     2013 1     1   JFK    ATL
25     2013 1     1   EWR    MIA
26     2013 1     1   EWR    ORD
27     2013 1     1   JFK    SFO
28     2013 1     1   JFK    RSW
29     2013 1     1   JFK    SJU
30     2013 1     1   EWR    ATL
⋮      ⋮    ⋮     ⋮   ⋮      ⋮
336747 2013 9     30  LGA    CHO
336748 2013 9     30  EWR    CLT
336749 2013 9     30  JFK    DEN
336750 2013 9     30  LGA    RIC
336751 2013 9     30  JFK    DCA
336752 2013 9     30  JFK    LAX
336753 2013 9     30  EWR    PWM
336754 2013 9     30  JFK    SJU
336755 2013 9     30  LGA    FLL
336756 2013 9     30  EWR    BOS
336757 2013 9     30  EWR    MHT
336758 2013 9     30  JFK    BUF
336759 2013 9     30  LGA    BGR
336760 2013 9     30  LGA    BNA
336761 2013 9     30  EWR    STL
336762 2013 9     30  JFK    PWM
336763 2013 9     30  EWR    SFO
336764 2013 9     30  JFK    MCO
336765 2013 9     30  JFK    BTV
336766 2013 9     30  JFK    SYR
336767 2013 9     30  JFK    BUF
336768 2013 9     30  JFK    ROC
336769 2013 9     30  JFK    BOS
336770 2013 9     30  JFK    PSE
336771 2013 9     30  LGA    BNA
336772 2013 9     30  JFK    DCA
336773 2013 9     30  LGA    SYR
336774 2013 9     30  LGA    BNA
336775 2013 9     30  LGA    CLE
336776 2013 9     30  LGA    RDU

       year month day origin dest
1      2013 1     1   EWR    IAH
2      2013 1     1   LGA    IAH
3      2013 1     1   JFK    MIA
4      2013 1     1   JFK    BQN
5      2013 1     1   LGA    ATL
6      2013 1     1   EWR    ORD
7      2013 1     1   EWR    FLL
8      2013 1     1   LGA    IAD
9      2013 1     1   JFK    MCO
10     2013 1     1   LGA    ORD
11     2013 1     1   JFK    PBI
12     2013 1     1   JFK    TPA
13     2013 1     1   JFK    LAX
14     2013 1     1   EWR    SFO
15     2013 1     1   LGA    DFW
16     2013 1     1   JFK    BOS
17     2013 1     1   EWR    LAS
18     2013 1     1   LGA    FLL
19     2013 1     1   LGA    ATL
20     2013 1     1   EWR    PBI
21     2013 1     1   LGA    MSP
22     2013 1     1   LGA    DTW
23     2013 1     1   EWR    MIA
24     2013 1     1   JFK    ATL
25     2013 1     1   EWR    MIA
26     2013 1     1   EWR    ORD
27     2013 1     1   JFK    SFO
28     2013 1     1   JFK    RSW
29     2013 1     1   JFK    SJU
30     2013 1     1   EWR    ATL
⋮      ⋮    ⋮     ⋮   ⋮      ⋮
336747 2013 9     30  LGA    CHO
336748 2013 9     30  EWR    CLT
336749 2013 9     30  JFK    DEN
336750 2013 9     30  LGA    RIC
336751 2013 9     30  JFK    DCA
336752 2013 9     30  JFK    LAX
336753 2013 9     30  EWR    PWM
336754 2013 9     30  JFK    SJU
336755 2013 9     30  LGA    FLL
336756 2013 9     30  EWR    BOS
336757 2013 9     30  EWR    MHT
336758 2013 9     30  JFK    BUF
336759 2013 9     30  LGA    BGR
336760 2013 9     30  LGA    BNA
336761 2013 9     30  EWR    STL
336762 2013 9     30  JFK    PWM
336763 2013 9     30  EWR    SFO
336764 2013 9     30  JFK    MCO
336765 2013 9     30  JFK    BTV
336766 2013 9     30  JFK    SYR
336767 2013 9     30  JFK    BUF
336768 2013 9     30  JFK    ROC
336769 2013 9     30  JFK    BOS
336770 2013 9     30  JFK    PSE
336771 2013 9     30  LGA    BNA
336772 2013 9     30  JFK    DCA
336773 2013 9     30  LGA    SYR
336774 2013 9     30  LGA    BNA
336775 2013 9     30  LGA    CLE
336776 2013 9     30  LGA    RDU

In [20]:
# Ahora con dplyr
select(vuelos, year, month, day, origin, dest)

       year month day origin dest
1      2013 1     1   EWR    IAH
2      2013 1     1   LGA    IAH
3      2013 1     1   JFK    MIA
4      2013 1     1   JFK    BQN
5      2013 1     1   LGA    ATL
6      2013 1     1   EWR    ORD
7      2013 1     1   EWR    FLL
8      2013 1     1   LGA    IAD
9      2013 1     1   JFK    MCO
10     2013 1     1   LGA    ORD
11     2013 1     1   JFK    PBI
12     2013 1     1   JFK    TPA
13     2013 1     1   JFK    LAX
14     2013 1     1   EWR    SFO
15     2013 1     1   LGA    DFW
16     2013 1     1   JFK    BOS
17     2013 1     1   EWR    LAS
18     2013 1     1   LGA    FLL
19     2013 1     1   LGA    ATL
20     2013 1     1   EWR    PBI
21     2013 1     1   LGA    MSP
22     2013 1     1   LGA    DTW
23     2013 1     1   EWR    MIA
24     2013 1     1   JFK    ATL
25     2013 1     1   EWR    MIA
26     2013 1     1   EWR    ORD
27     2013 1     1   JFK    SFO
28     2013 1     1   JFK    RSW
29     2013 1     1   JFK    SJU
30     2013 1     1   EWR    ATL
⋮      ⋮    ⋮     ⋮   ⋮      ⋮
336747 2013 9     30  LGA    CHO
336748 2013 9     30  EWR    CLT
336749 2013 9     30  JFK    DEN
336750 2013 9     30  LGA    RIC
336751 2013 9     30  JFK    DCA
336752 2013 9     30  JFK    LAX
336753 2013 9     30  EWR    PWM
336754 2013 9     30  JFK    SJU
336755 2013 9     30  LGA    FLL
336756 2013 9     30  EWR    BOS
336757 2013 9     30  EWR    MHT
336758 2013 9     30  JFK    BUF
336759 2013 9     30  LGA    BGR
336760 2013 9     30  LGA    BNA
336761 2013 9     30  EWR    STL
336762 2013 9     30  JFK    PWM
336763 2013 9     30  EWR    SFO
336764 2013 9     30  JFK    MCO
336765 2013 9     30  JFK    BTV
336766 2013 9     30  JFK    SYR
336767 2013 9     30  JFK    BUF
336768 2013 9     30  JFK    ROC
336769 2013 9     30  JFK    BOS
336770 2013 9     30  JFK    PSE
336771 2013 9     30  LGA    BNA
336772 2013 9     30  JFK    DCA
336773 2013 9     30  LGA    SYR
336774 2013 9     30  LGA    BNA
336775 2013 9     30  LGA    CLE
336776 2013 9     30  LGA    RDU

In [21]:
str(vuelos)

'data.frame':	336776 obs. of  19 variables:
 $ year          : int  2013 2013 2013 2013 2013 2013 2013 2013 2013 2013 ...
 $ month         : int  1 1 1 1 1 1 1 1 1 1 ...
 $ day           : int  1 1 1 1 1 1 1 1 1 1 ...
 $ dep_time      : int  517 533 542 544 554 554 555 557 557 558 ...
 $ sched_dep_time: int  515 529 540 545 600 558 600 600 600 600 ...
 $ dep_delay     : int  2 4 2 -1 -6 -4 -5 -3 -3 -2 ...
 $ arr_time      : int  830 850 923 1004 812 740 913 709 838 753 ...
 $ sched_arr_time: int  819 830 850 1022 837 728 854 723 846 745 ...
 $ arr_delay     : int  11 20 33 -18 -25 12 19 -14 -8 8 ...
 $ carrier       : chr  "UA" "UA" "AA" "B6" ...
 $ flight        : int  1545 1714 1141 725 461 1696 507 5708 79 301 ...
 $ tailnum       : chr  "N14228" "N24211" "N619AA" "N804JB" ...
 $ origin        : chr  "EWR" "LGA" "JFK" "JFK" ...
 $ dest          : chr  "IAH" "IAH" "MIA" "BQN" ...
 $ air_time      : int  227 227 160 183 116 150 158 53 140 138 ...
 $ distance      : int  1400 1416 1089 1576 762 719 1065 229 944 733 ...
 $ hour          : int  5 5 5 5 6 5 6 6 6 6 ...
 $ minute        : int  15 29 40 45 0 58 0 0 0 0 ...
 $ time_hour     : chr  "2013-01-01 05:00:00" "2013-01-01 05:00:00" "2013-01-01 05:00:00" "2013-01-01 05:00:00" ...

In [23]:
#Existe gran variedad (pueden consultar la documentación respectiva)  de otras funciones dentro del package dplyr, por ejemplo: Seleccionar solo las variables que comiencen con "d"
# para su estudio
select(vuelos,1, 2, 3, 13, 14)
select(vuelos,"year", "month", "day", "origin", "dest")

       year month day origin dest
1      2013 1     1   EWR    IAH
2      2013 1     1   LGA    IAH
3      2013 1     1   JFK    MIA
4      2013 1     1   JFK    BQN
5      2013 1     1   LGA    ATL
6      2013 1     1   EWR    ORD
7      2013 1     1   EWR    FLL
8      2013 1     1   LGA    IAD
9      2013 1     1   JFK    MCO
10     2013 1     1   LGA    ORD
11     2013 1     1   JFK    PBI
12     2013 1     1   JFK    TPA
13     2013 1     1   JFK    LAX
14     2013 1     1   EWR    SFO
15     2013 1     1   LGA    DFW
16     2013 1     1   JFK    BOS
17     2013 1     1   EWR    LAS
18     2013 1     1   LGA    FLL
19     2013 1     1   LGA    ATL
20     2013 1     1   EWR    PBI
21     2013 1     1   LGA    MSP
22     2013 1     1   LGA    DTW
23     2013 1     1   EWR    MIA
24     2013 1     1   JFK    ATL
25     2013 1     1   EWR    MIA
26     2013 1     1   EWR    ORD
27     2013 1     1   JFK    SFO
28     2013 1     1   JFK    RSW
29     2013 1     1   JFK    SJU
30     2013 1     1   EWR    ATL
⋮      ⋮    ⋮     ⋮   ⋮      ⋮
336747 2013 9     30  LGA    CHO
336748 2013 9     30  EWR    CLT
336749 2013 9     30  JFK    DEN
336750 2013 9     30  LGA    RIC
336751 2013 9     30  JFK    DCA
336752 2013 9     30  JFK    LAX
336753 2013 9     30  EWR    PWM
336754 2013 9     30  JFK    SJU
336755 2013 9     30  LGA    FLL
336756 2013 9     30  EWR    BOS
336757 2013 9     30  EWR    MHT
336758 2013 9     30  JFK    BUF
336759 2013 9     30  LGA    BGR
336760 2013 9     30  LGA    BNA
336761 2013 9     30  EWR    STL
336762 2013 9     30  JFK    PWM
336763 2013 9     30  EWR    SFO
336764 2013 9     30  JFK    MCO
336765 2013 9     30  JFK    BTV
336766 2013 9     30  JFK    SYR
336767 2013 9     30  JFK    BUF
336768 2013 9     30  JFK    ROC
336769 2013 9     30  JFK    BOS
336770 2013 9     30  JFK    PSE
336771 2013 9     30  LGA    BNA
336772 2013 9     30  JFK    DCA
336773 2013 9     30  LGA    SYR
336774 2013 9     30  LGA    BNA
336775 2013 9     30  LGA    CLE
336776 2013 9     30  LGA    RDU

       year month day origin dest
1      2013 1     1   EWR    IAH
2      2013 1     1   LGA    IAH
3      2013 1     1   JFK    MIA
4      2013 1     1   JFK    BQN
5      2013 1     1   LGA    ATL
6      2013 1     1   EWR    ORD
7      2013 1     1   EWR    FLL
8      2013 1     1   LGA    IAD
9      2013 1     1   JFK    MCO
10     2013 1     1   LGA    ORD
11     2013 1     1   JFK    PBI
12     2013 1     1   JFK    TPA
13     2013 1     1   JFK    LAX
14     2013 1     1   EWR    SFO
15     2013 1     1   LGA    DFW
16     2013 1     1   JFK    BOS
17     2013 1     1   EWR    LAS
18     2013 1     1   LGA    FLL
19     2013 1     1   LGA    ATL
20     2013 1     1   EWR    PBI
21     2013 1     1   LGA    MSP
22     2013 1     1   LGA    DTW
23     2013 1     1   EWR    MIA
24     2013 1     1   JFK    ATL
25     2013 1     1   EWR    MIA
26     2013 1     1   EWR    ORD
27     2013 1     1   JFK    SFO
28     2013 1     1   JFK    RSW
29     2013 1     1   JFK    SJU
30     2013 1     1   EWR    ATL
⋮      ⋮    ⋮     ⋮   ⋮      ⋮
336747 2013 9     30  LGA    CHO
336748 2013 9     30  EWR    CLT
336749 2013 9     30  JFK    DEN
336750 2013 9     30  LGA    RIC
336751 2013 9     30  JFK    DCA
336752 2013 9     30  JFK    LAX
336753 2013 9     30  EWR    PWM
336754 2013 9     30  JFK    SJU
336755 2013 9     30  LGA    FLL
336756 2013 9     30  EWR    BOS
336757 2013 9     30  EWR    MHT
336758 2013 9     30  JFK    BUF
336759 2013 9     30  LGA    BGR
336760 2013 9     30  LGA    BNA
336761 2013 9     30  EWR    STL
336762 2013 9     30  JFK    PWM
336763 2013 9     30  EWR    SFO
336764 2013 9     30  JFK    MCO
336765 2013 9     30  JFK    BTV
336766 2013 9     30  JFK    SYR
336767 2013 9     30  JFK    BUF
336768 2013 9     30  JFK    ROC
336769 2013 9     30  JFK    BOS
336770 2013 9     30  JFK    PSE
336771 2013 9     30  LGA    BNA
336772 2013 9     30  JFK    DCA
336773 2013 9     30  LGA    SYR
336774 2013 9     30  LGA    BNA
336775 2013 9     30  LGA    CLE
336776 2013 9     30  LGA    RDU

In [24]:
select(vuelos, ends_with("_delay"))

       dep_delay arr_delay
1       2         11
2       4         20
3       2         33
4      -1        -18
5      -6        -25
6      -4         12
7      -5         19
8      -3        -14
9      -3         -8
10     -2          8
11     -2         -2
12     -2         -3
13     -2          7
14     -2        -14
15     -1         31
16      0         -4
17     -1         -8
18      0         -7
19      0         12
20      1         -6
21     -8         -8
22     -3         16
23     -4        -12
24     -4         -8
25      0        -17
26      8         32
27     11         14
28      3          4
29      0        -21
30      0         -9
⋮      ⋮         ⋮
336747  -2       -24
336748  -2        -9
336749  -2       -31
336750  30        -2
336751  -9       -30
336752   0       -30
336753  13        11
336754   0       -25
336755  10         3
336756  -7       -23
336757  -9       -16
336758 194       194
336759  -2         8
336760  27         7
336761  72        57
336762 -14       -21
336763  80        42
336764 154       130
336765  -8        -8
336766  -5       -17
336767 -10       -20
336768  -5       -16
336769  12         1
336770 -10       -25
336771  NA        NA
336772  NA        NA
336773  NA        NA
336774  NA        NA
336775  NA        NA
336776  NA        NA

In [25]:
names(vuelos)

 [1] "year"           "month"          "day"            "dep_time"
 [5] "sched_dep_time" "dep_delay"      "arr_time"       "sched_arr_time"
 [9] "arr_delay"      "carrier"        "flight"         "tailnum"
[13] "origin"         "dest"           "air_time"       "distance"
[17] "hour"           "minute"         "time_hour"

In [26]:
select(vuelos, dep_delay:carrier)

       dep_delay arr_time sched_arr_time arr_delay carrier
1       2         830      819            11       UA
2       4         850      830            20       UA
3       2         923      850            33       AA
4      -1        1004     1022           -18       B6
5      -6         812      837           -25       DL
6      -4         740      728            12       UA
7      -5         913      854            19       B6
8      -3         709      723           -14       EV
9      -3         838      846            -8       B6
10     -2         753      745             8       AA
11     -2         849      851            -2       B6
12     -2         853      856            -3       B6
13     -2         924      917             7       UA
14     -2         923      937           -14       UA
15     -1         941      910            31       AA
16      0         702      706            -4       B6
17     -1         854      902            -8       UA
18      0         851      858            -7       B6
19      0         837      825            12       MQ
20      1         844      850            -6       B6
21     -8         812      820            -8       DL
22     -3         821      805            16       MQ
23     -4         858      910           -12       AA
24     -4         837      845            -8       DL
25      0         858      915           -17       UA
26      8         807      735            32       MQ
27     11         945      931            14       UA
28      3         925      921             4       B6
29      0        1039     1100           -21       B6
30      0         833      842            -9       DL
⋮      ⋮         ⋮        ⋮              ⋮         ⋮
336747  -2       2223     2247           -24       EV
336748  -2       2314     2323            -9       EV
336749  -2       2328     2359           -31       B6
336750  30       2230     2232            -2       EV
336751  -9       2225     2255           -30       MQ
336752   0         10       40           -30       AA
336753  13       2250     2239            11       EV
336754   0        115      140           -25       B6
336755  10         30       27             3       B6
336756  -7       2245     2308           -23       UA
336757  -9       2250     2306           -16       EV
336758 194       2344     2030           194       9E
336759  -2       2339     2331             8       EV
336760  27       2257     2250             7       MQ
336761  72       2339     2242            57       EV
336762 -14       2335     2356           -21       B6
336763  80        112       30            42       UA
336764 154         59     2249           130       B6
336765  -8       2345     2353            -8       B6
336766  -5       2334     2351           -17       B6
336767 -10       2347        7           -20       B6
336768  -5       2345        1           -16       B6
336769  12       2359     2358             1       B6
336770 -10        325      350           -25       B6
336771  NA         NA     2019            NA       EV
336772  NA         NA     1634            NA       9E
336773  NA         NA     2312            NA       9E
336774  NA         NA     1330            NA       MQ
336775  NA         NA     1344            NA       MQ
336776  NA         NA     1020            NA       MQ

In [29]:
# podemos renombrar la columna year
rename(vuelos,
       anio = year,
       mes = month,
       dia = day)

       anio mes dia dep_time sched_dep_time dep_delay arr_time sched_arr_time
1      2013 1   1   517      515             2         830      819
2      2013 1   1   533      529             4         850      830
3      2013 1   1   542      540             2         923      850
4      2013 1   1   544      545            -1        1004     1022
5      2013 1   1   554      600            -6         812      837
6      2013 1   1   554      558            -4         740      728
7      2013 1   1   555      600            -5         913      854
8      2013 1   1   557      600            -3         709      723
9      2013 1   1   557      600            -3         838      846
10     2013 1   1   558      600            -2         753      745
11     2013 1   1   558      600            -2         849      851
12     2013 1   1   558      600            -2         853      856
13     2013 1   1   558      600            -2         924      917
14     2013 1   1   558      600            -2         923      937
15     2013 1   1   559      600            -1         941      910
16     2013 1   1   559      559             0         702      706
17     2013 1   1   559      600            -1         854      902
18     2013 1   1   600      600             0         851      858
19     2013 1   1   600      600             0         837      825
20     2013 1   1   601      600             1         844      850
21     2013 1   1   602      610            -8         812      820
22     2013 1   1   602      605            -3         821      805
23     2013 1   1   606      610            -4         858      910
24     2013 1   1   606      610            -4         837      845
25     2013 1   1   607      607             0         858      915
26     2013 1   1   608      600             8         807      735
27     2013 1   1   611      600            11         945      931
28     2013 1   1   613      610             3         925      921
29     2013 1   1   615      615             0        1039     1100
30     2013 1   1   615      615             0         833      842
⋮      ⋮    ⋮   ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
336747 2013 9   30  2123     2125            -2       2223     2247
336748 2013 9   30  2127     2129            -2       2314     2323
336749 2013 9   30  2128     2130            -2       2328     2359
336750 2013 9   30  2129     2059            30       2230     2232
336751 2013 9   30  2131     2140            -9       2225     2255
336752 2013 9   30  2140     2140             0         10       40
336753 2013 9   30  2142     2129            13       2250     2239
336754 2013 9   30  2145     2145             0        115      140
336755 2013 9   30  2147     2137            10         30       27
336756 2013 9   30  2149     2156            -7       2245     2308
336757 2013 9   30  2150     2159            -9       2250     2306
336758 2013 9   30  2159     1845           194       2344     2030
336759 2013 9   30  2203     2205            -2       2339     2331
336760 2013 9   30  2207     2140            27       2257     2250
336761 2013 9   30  2211     2059            72       2339     2242
336762 2013 9   30  2231     2245           -14       2335     2356
336763 2013 9   30  2233     2113            80        112       30
336764 2013 9   30  2235     2001           154         59     2249
336765 2013 9   30  2237     2245            -8       2345     2353
336766 2013 9   30  2240     2245            -5       2334     2351
336767 2013 9   30  2240     2250           -10       2347        7
336768 2013 9   30  2241     2246            -5       2345        1
336769 2013 9   30  2307     2255            12       2359     2358
336770 2013 9   30  2349     2359           -10        325      350
336771 2013 9   30    NA     1842            NA         NA     2019
336772 2013 9   30    NA     1455            NA         NA     1634
336773 2013 9   30    NA     2200            NA         NA     2312
336774 2013 9   30    NA     1210            NA         NA     1330
336775 2013 9   30    NA     1159            NA         NA     1344
336776 2013 9   30    NA      840            NA         NA     1020
       arr_delay carrier flight tailnum origin dest air_time distance hour
1       11       UA      1545   N14228  EWR    IAH  227      1400     5
2       20       UA      1714   N24211  LGA    IAH  227      1416     5
3       33       AA      1141   N619AA  JFK    MIA  160      1089     5
4      -18       B6       725   N804JB  JFK    BQN  183      1576     5
5      -25       DL       461   N668DN  LGA    ATL  116       762     6
6       12       UA      1696   N39463  EWR    ORD  150       719     5
7       19       B6       507   N516JB  EWR    FLL  158      1065     6
8      -14       EV      5708   N829AS  LGA    IAD   53       229     6
9       -8       B6        79   N593JB  JFK    MCO  140       944     6
10       8       AA       301   N3ALAA  LGA    ORD  138       733     6
11      -2       B6        49   N793JB  JFK    PBI  149      1028     6
12      -3       B6        71   N657JB  JFK    TPA  158      1005     6
13       7       UA       194   N29129  JFK    LAX  345      2475     6
14     -14       UA      1124   N53441  EWR    SFO  361      2565     6
15      31       AA       707   N3DUAA  LGA    DFW  257      1389     6
16      -4       B6      1806   N708JB  JFK    BOS   44       187     5
17      -8       UA      1187   N76515  EWR    LAS  337      2227     6
18      -7       B6       371   N595JB  LGA    FLL  152      1076     6
19      12       MQ      4650   N542MQ  LGA    ATL  134       762     6
20      -6       B6       343   N644JB  EWR    PBI  147      1023     6
21      -8       DL      1919   N971DL  LGA    MSP  170      1020     6
22      16       MQ      4401   N730MQ  LGA    DTW  105       502     6
23     -12       AA      1895   N633AA  EWR    MIA  152      1085     6
24      -8       DL      1743   N3739P  JFK    ATL  128       760     6
25     -17       UA      1077   N53442  EWR    MIA  157      1085     6
26      32       MQ      3768   N9EAMQ  EWR    ORD  139       719     6
27      14       UA       303   N532UA  JFK    SFO  366      2586     6
28       4       B6       135   N635JB  JFK    RSW  175      1074     6
29     -21       B6       709   N794JB  JFK    SJU  182      1598     6
30      -9       DL       575   N326NB  EWR    ATL  120       746     6
⋮      ⋮         ⋮       ⋮      ⋮       ⋮      ⋮    ⋮        ⋮        ⋮
336747 -24       EV      5489   N712EV  LGA    CHO   45       305     21
336748  -9       EV      3833   N16546  EWR    CLT   72       529     21
336749 -31       B6        97   N807JB  JFK    DEN  213      1626     21
336750  -2       EV      5048   N751EV  LGA    RIC   45       292     20
336751 -30       MQ      3621   N807MQ  JFK    DCA   36       213     21
336752 -30       AA       185   N335AA  JFK    LAX  298      2475     21
336753  11       EV      4509   N12957  EWR    PWM   47       284     21
336754 -25       B6      1103   N633JB  JFK    SJU  192      1598     21
336755   3       B6      1371   N627JB  LGA    FLL  139      1076     21
336756 -23       UA       523   N813UA  EWR    BOS   37       200     21
336757 -16       EV      3842   N10575  EWR    MHT   39       209     21
336758 194       9E      3320   N906XJ  JFK    BUF   50       301     18
336759   8       EV      5311   N722EV  LGA    BGR   61       378     22
336760   7       MQ      3660   N532MQ  LGA    BNA   97       764     21
336761  57       EV      4672   N12145  EWR    STL  120       872     20
336762 -21       B6       108   N193JB  JFK    PWM   48       273     22
336763  42       UA       471   N578UA  EWR    SFO  318      2565     21
336764 130       B6      1083   N804JB  JFK    MCO  123       944     20
336765  -8       B6       234   N318JB  JFK    BTV   43       266     22
336766 -17       B6      1816   N354JB  JFK    SYR   41       209     22
336767 -20       B6      2002   N281JB  JFK    BUF   52       301     22
336768 -16       B6       486   N346JB  JFK    ROC   47       264     22
336769   1       B6       718   N565JB  JFK    BOS   33       187     22
336770 -25       B6       745   N516JB  JFK    PSE  196      1617     23
336771  NA       EV      5274   N740EV  LGA    BNA   NA       764     18
336772  NA       9E      3393   NA      JFK    DCA   NA       213     14
336773  NA       9E      3525   NA      LGA    SYR   NA       198     22
336774  NA       MQ      3461   N535MQ  LGA    BNA   NA       764     12
336775  NA       MQ      3572   N511MQ  LGA    CLE   NA       419     11
336776  NA       MQ      3531   N839MQ  LGA    RDU   NA       431      8
       minute time_hour
1      15     2013-01-01 05:00:00
2      29     2013-01-01 05:00:00
3      40     2013-01-01 05:00:00
4      45     2013-01-01 05:00:00
5       0     2013-01-01 06:00:00
6      58     2013-01-01 05:00:00
7       0     2013-01-01 06:00:00
8       0     2013-01-01 06:00:00
9       0     2013-01-01 06:00:00
10      0     2013-01-01 06:00:00
11      0     2013-01-01 06:00:00
12      0     2013-01-01 06:00:00
13      0     2013-01-01 06:00:00
14      0     2013-01-01 06:00:00
15      0     2013-01-01 06:00:00
16     59     2013-01-01 05:00:00
17      0     2013-01-01 06:00:00
18      0     2013-01-01 06:00:00
19      0     2013-01-01 06:00:00
20      0     2013-01-01 06:00:00
21     10     2013-01-01 06:00:00
22      5     2013-01-01 06:00:00
23     10     2013-01-01 06:00:00
24     10     2013-01-01 06:00:00
25      7     2013-01-01 06:00:00
26      0     2013-01-01 06:00:00
27      0     2013-01-01 06:00:00
28     10     2013-01-01 06:00:00
29     15     2013-01-01 06:00:00
30     15     2013-01-01 06:00:00
⋮      ⋮      ⋮
336747 25     2013-09-30 21:00:00
336748 29     2013-09-30 21:00:00
336749 30     2013-09-30 21:00:00
336750 59     2013-09-30 20:00:00
336751 40     2013-09-30 21:00:00
336752 40     2013-09-30 21:00:00
336753 29     2013-09-30 21:00:00
336754 45     2013-09-30 21:00:00
336755 37     2013-09-30 21:00:00
336756 56     2013-09-30 21:00:00
336757 59     2013-09-30 21:00:00
336758 45     2013-09-30 18:00:00
336759  5     2013-09-30 22:00:00
336760 40     2013-09-30 21:00:00
336761 59     2013-09-30 20:00:00
336762 45     2013-09-30 22:00:00
336763 13     2013-09-30 21:00:00
336764  1     2013-09-30 20:00:00
336765 45     2013-09-30 22:00:00
336766 45     2013-09-30 22:00:00
336767 50     2013-09-30 22:00:00
336768 46     2013-09-30 22:00:00
336769 55     2013-09-30 22:00:00
336770 59     2013-09-30 23:00:00
336771 42     2013-09-30 18:00:00
336772 55     2013-09-30 14:00:00
336773  0     2013-09-30 22:00:00
336774 10     2013-09-30 12:00:00
336775 59     2013-09-30 11:00:00
336776 40     2013-09-30 08:00:00

In [31]:
# NOTA: esto no modifica el dataset original
head(vuelos)
# Si queremos que el cambio permanezca...
vuelos <- rename(vuelos,
       anio = year,
       mes = month,
       dia = day)

  year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     1   517      515             2         830      819
2 2013 1     1   533      529             4         850      830
3 2013 1     1   542      540             2         923      850
4 2013 1     1   544      545            -1        1004     1022
5 2013 1     1   554      600            -6         812      837
6 2013 1     1   554      558            -4         740      728
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  11       UA      1545   N14228  EWR    IAH  227      1400     5    15
2  20       UA      1714   N24211  LGA    IAH  227      1416     5    29
3  33       AA      1141   N619AA  JFK    MIA  160      1089     5    40
4 -18       B6       725   N804JB  JFK    BQN  183      1576     5    45
5 -25       DL       461   N668DN  LGA    ATL  116       762     6     0
6  12       UA      1696   N39463  EWR    ORD  150       719     5    58
  time_hour
1 2013-01-01 05:00:00
2 2013-01-01 05:00:00
3 2013-01-01 05:00:00
4 2013-01-01 05:00:00
5 2013-01-01 06:00:00
6 2013-01-01 05:00:00

In [32]:
head(vuelos)

  anio mes dia dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1   1   517      515             2         830      819
2 2013 1   1   533      529             4         850      830
3 2013 1   1   542      540             2         923      850
4 2013 1   1   544      545            -1        1004     1022
5 2013 1   1   554      600            -6         812      837
6 2013 1   1   554      558            -4         740      728
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  11       UA      1545   N14228  EWR    IAH  227      1400     5    15
2  20       UA      1714   N24211  LGA    IAH  227      1416     5    29
3  33       AA      1141   N619AA  JFK    MIA  160      1089     5    40
4 -18       B6       725   N804JB  JFK    BQN  183      1576     5    45
5 -25       DL       461   N668DN  LGA    ATL  116       762     6     0
6  12       UA      1696   N39463  EWR    ORD  150       719     5    58
  time_hour
1 2013-01-01 05:00:00
2 2013-01-01 05:00:00
3 2013-01-01 05:00:00
4 2013-01-01 05:00:00
5 2013-01-01 06:00:00
6 2013-01-01 05:00:00

### 4.4 Función mutate()

Una de las funciones más útiles de dplyr es la función mutate(), la cual permite crear nuevas columnas, o modificar las existentes.

In [39]:
# mutate() ----------------------------------------------------------------
# Crear una nueva columna llamada retraso_neto, que contenga la suma de arr_delay y dep_delay

#antes
vuelos$retraso_neto <- vuelos$arr_delay + vuelos$dep_delay # altera directamente el dataframe
#ahora
mutate(vuelos, retraso_neto2 = arr_delay + dep_delay)

       anio mes dia dep_time sched_dep_time dep_delay arr_time sched_arr_time
1      2013 1   1   517      515             2         830      819
2      2013 1   1   533      529             4         850      830
3      2013 1   1   542      540             2         923      850
4      2013 1   1   544      545            -1        1004     1022
5      2013 1   1   554      600            -6         812      837
6      2013 1   1   554      558            -4         740      728
7      2013 1   1   555      600            -5         913      854
8      2013 1   1   557      600            -3         709      723
9      2013 1   1   557      600            -3         838      846
10     2013 1   1   558      600            -2         753      745
11     2013 1   1   558      600            -2         849      851
12     2013 1   1   558      600            -2         853      856
13     2013 1   1   558      600            -2         924      917
14     2013 1   1   558      600            -2         923      937
15     2013 1   1   559      600            -1         941      910
16     2013 1   1   559      559             0         702      706
17     2013 1   1   559      600            -1         854      902
18     2013 1   1   600      600             0         851      858
19     2013 1   1   600      600             0         837      825
20     2013 1   1   601      600             1         844      850
21     2013 1   1   602      610            -8         812      820
22     2013 1   1   602      605            -3         821      805
23     2013 1   1   606      610            -4         858      910
24     2013 1   1   606      610            -4         837      845
25     2013 1   1   607      607             0         858      915
26     2013 1   1   608      600             8         807      735
27     2013 1   1   611      600            11         945      931
28     2013 1   1   613      610             3         925      921
29     2013 1   1   615      615             0        1039     1100
30     2013 1   1   615      615             0         833      842
⋮      ⋮    ⋮   ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
336747 2013 9   30  2123     2125            -2       2223     2247
336748 2013 9   30  2127     2129            -2       2314     2323
336749 2013 9   30  2128     2130            -2       2328     2359
336750 2013 9   30  2129     2059            30       2230     2232
336751 2013 9   30  2131     2140            -9       2225     2255
336752 2013 9   30  2140     2140             0         10       40
336753 2013 9   30  2142     2129            13       2250     2239
336754 2013 9   30  2145     2145             0        115      140
336755 2013 9   30  2147     2137            10         30       27
336756 2013 9   30  2149     2156            -7       2245     2308
336757 2013 9   30  2150     2159            -9       2250     2306
336758 2013 9   30  2159     1845           194       2344     2030
336759 2013 9   30  2203     2205            -2       2339     2331
336760 2013 9   30  2207     2140            27       2257     2250
336761 2013 9   30  2211     2059            72       2339     2242
336762 2013 9   30  2231     2245           -14       2335     2356
336763 2013 9   30  2233     2113            80        112       30
336764 2013 9   30  2235     2001           154         59     2249
336765 2013 9   30  2237     2245            -8       2345     2353
336766 2013 9   30  2240     2245            -5       2334     2351
336767 2013 9   30  2240     2250           -10       2347        7
336768 2013 9   30  2241     2246            -5       2345        1
336769 2013 9   30  2307     2255            12       2359     2358
336770 2013 9   30  2349     2359           -10        325      350
336771 2013 9   30    NA     1842            NA         NA     2019
336772 2013 9   30    NA     1455            NA         NA     1634
336773 2013 9   30    NA     2200            NA         NA     2312
336774 2013 9   30    NA     1210            NA         NA     1330
336775 2013 9   30    NA     1159            NA         NA     1344
336776 2013 9   30    NA      840            NA         NA     1020
       arr_delay carrier ⋯ tailnum origin dest air_time distance hour minute
1       11       UA      ⋯ N14228  EWR    IAH  227      1400     5    15
2       20       UA      ⋯ N24211  LGA    IAH  227      1416     5    29
3       33       AA      ⋯ N619AA  JFK    MIA  160      1089     5    40
4      -18       B6      ⋯ N804JB  JFK    BQN  183      1576     5    45
5      -25       DL      ⋯ N668DN  LGA    ATL  116       762     6     0
6       12       UA      ⋯ N39463  EWR    ORD  150       719     5    58
7       19       B6      ⋯ N516JB  EWR    FLL  158      1065     6     0
8      -14       EV      ⋯ N829AS  LGA    IAD   53       229     6     0
9       -8       B6      ⋯ N593JB  JFK    MCO  140       944     6     0
10       8       AA      ⋯ N3ALAA  LGA    ORD  138       733     6     0
11      -2       B6      ⋯ N793JB  JFK    PBI  149      1028     6     0
12      -3       B6      ⋯ N657JB  JFK    TPA  158      1005     6     0
13       7       UA      ⋯ N29129  JFK    LAX  345      2475     6     0
14     -14       UA      ⋯ N53441  EWR    SFO  361      2565     6     0
15      31       AA      ⋯ N3DUAA  LGA    DFW  257      1389     6     0
16      -4       B6      ⋯ N708JB  JFK    BOS   44       187     5    59
17      -8       UA      ⋯ N76515  EWR    LAS  337      2227     6     0
18      -7       B6      ⋯ N595JB  LGA    FLL  152      1076     6     0
19      12       MQ      ⋯ N542MQ  LGA    ATL  134       762     6     0
20      -6       B6      ⋯ N644JB  EWR    PBI  147      1023     6     0
21      -8       DL      ⋯ N971DL  LGA    MSP  170      1020     6    10
22      16       MQ      ⋯ N730MQ  LGA    DTW  105       502     6     5
23     -12       AA      ⋯ N633AA  EWR    MIA  152      1085     6    10
24      -8       DL      ⋯ N3739P  JFK    ATL  128       760     6    10
25     -17       UA      ⋯ N53442  EWR    MIA  157      1085     6     7
26      32       MQ      ⋯ N9EAMQ  EWR    ORD  139       719     6     0
27      14       UA      ⋯ N532UA  JFK    SFO  366      2586     6     0
28       4       B6      ⋯ N635JB  JFK    RSW  175      1074     6    10
29     -21       B6      ⋯ N794JB  JFK    SJU  182      1598     6    15
30      -9       DL      ⋯ N326NB  EWR    ATL  120       746     6    15
⋮      ⋮         ⋮       ⋱ ⋮       ⋮      ⋮    ⋮        ⋮        ⋮    ⋮
336747 -24       EV      ⋯ N712EV  LGA    CHO   45       305     21   25
336748  -9       EV      ⋯ N16546  EWR    CLT   72       529     21   29
336749 -31       B6      ⋯ N807JB  JFK    DEN  213      1626     21   30
336750  -2       EV      ⋯ N751EV  LGA    RIC   45       292     20   59
336751 -30       MQ      ⋯ N807MQ  JFK    DCA   36       213     21   40
336752 -30       AA      ⋯ N335AA  JFK    LAX  298      2475     21   40
336753  11       EV      ⋯ N12957  EWR    PWM   47       284     21   29
336754 -25       B6      ⋯ N633JB  JFK    SJU  192      1598     21   45
336755   3       B6      ⋯ N627JB  LGA    FLL  139      1076     21   37
336756 -23       UA      ⋯ N813UA  EWR    BOS   37       200     21   56
336757 -16       EV      ⋯ N10575  EWR    MHT   39       209     21   59
336758 194       9E      ⋯ N906XJ  JFK    BUF   50       301     18   45
336759   8       EV      ⋯ N722EV  LGA    BGR   61       378     22    5
336760   7       MQ      ⋯ N532MQ  LGA    BNA   97       764     21   40
336761  57       EV      ⋯ N12145  EWR    STL  120       872     20   59
336762 -21       B6      ⋯ N193JB  JFK    PWM   48       273     22   45
336763  42       UA      ⋯ N578UA  EWR    SFO  318      2565     21   13
336764 130       B6      ⋯ N804JB  JFK    MCO  123       944     20    1
336765  -8       B6      ⋯ N318JB  JFK    BTV   43       266     22   45
336766 -17       B6      ⋯ N354JB  JFK    SYR   41       209     22   45
336767 -20       B6      ⋯ N281JB  JFK    BUF   52       301     22   50
336768 -16       B6      ⋯ N346JB  JFK    ROC   47       264     22   46
336769   1       B6      ⋯ N565JB  JFK    BOS   33       187     22   55
336770 -25       B6      ⋯ N516JB  JFK    PSE  196      1617     23   59
336771  NA       EV      ⋯ N740EV  LGA    BNA   NA       764     18   42
336772  NA       9E      ⋯ NA      JFK    DCA   NA       213     14   55
336773  NA       9E      ⋯ NA      LGA    SYR   NA       198     22    0
336774  NA       MQ      ⋯ N535MQ  LGA    BNA   NA       764     12   10
336775  NA       MQ      ⋯ N511MQ  LGA    CLE   NA       419     11   59
336776  NA       MQ      ⋯ N839MQ  LGA    RDU   NA       431      8   40
       time_hour           retraso_neto retraso_neto2
1      2013-01-01 05:00:00  13           13
2      2013-01-01 05:00:00  24           24
3      2013-01-01 05:00:00  35           35
4      2013-01-01 05:00:00 -19          -19
5      2013-01-01 06:00:00 -31          -31
6      2013-01-01 05:00:00   8            8
7      2013-01-01 06:00:00  14           14
8      2013-01-01 06:00:00 -17          -17
9      2013-01-01 06:00:00 -11          -11
10     2013-01-01 06:00:00   6            6
11     2013-01-01 06:00:00  -4           -4
12     2013-01-01 06:00:00  -5           -5
13     2013-01-01 06:00:00   5            5
14     2013-01-01 06:00:00 -16          -16
15     2013-01-01 06:00:00  30           30
16     2013-01-01 05:00:00  -4           -4
17     2013-01-01 06:00:00  -9           -9
18     2013-01-01 06:00:00  -7           -7
19     2013-01-01 06:00:00  12           12
20     2013-01-01 06:00:00  -5           -5
21     2013-01-01 06:00:00 -16          -16
22     2013-01-01 06:00:00  13           13
23     2013-01-01 06:00:00 -16          -16
24     2013-01-01 06:00:00 -12          -12
25     2013-01-01 06:00:00 -17          -17
26     2013-01-01 06:00:00  40           40
27     2013-01-01 06:00:00  25           25
28     2013-01-01 06:00:00   7            7
29     2013-01-01 06:00:00 -21          -21
30     2013-01-01 06:00:00  -9           -9
⋮      ⋮                   ⋮            ⋮
336747 2013-09-30 21:00:00 -26          -26
336748 2013-09-30 21:00:00 -11          -11
336749 2013-09-30 21:00:00 -33          -33
336750 2013-09-30 20:00:00  28           28
336751 2013-09-30 21:00:00 -39          -39
336752 2013-09-30 21:00:00 -30          -30
336753 2013-09-30 21:00:00  24           24
336754 2013-09-30 21:00:00 -25          -25
336755 2013-09-30 21:00:00  13           13
336756 2013-09-30 21:00:00 -30          -30
336757 2013-09-30 21:00:00 -25          -25
336758 2013-09-30 18:00:00 388          388
336759 2013-09-30 22:00:00   6            6
336760 2013-09-30 21:00:00  34           34
336761 2013-09-30 20:00:00 129          129
336762 2013-09-30 22:00:00 -35          -35
336763 2013-09-30 21:00:00 122          122
336764 2013-09-30 20:00:00 284          284
336765 2013-09-30 22:00:00 -16          -16
336766 2013-09-30 22:00:00 -22          -22
336767 2013-09-30 22:00:00 -30          -30
336768 2013-09-30 22:00:00 -21          -21
336769 2013-09-30 22:00:00  13           13
336770 2013-09-30 23:00:00 -35          -35
336771 2013-09-30 18:00:00  NA           NA
336772 2013-09-30 14:00:00  NA           NA
336773 2013-09-30 22:00:00  NA           NA
336774 2013-09-30 12:00:00  NA           NA
336775 2013-09-30 11:00:00  NA           NA
336776 2013-09-30 08:00:00  NA           NA

In [41]:
# Recordar que esta nueva columna solo existe en la ejecución y no se ha modificado el dataset original.
head(vuelos)
vuelos <- mutate(vuelos, retraso_neto2 = arr_delay + dep_delay)

  anio mes dia dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1   1   517      515             2         830      819
2 2013 1   1   533      529             4         850      830
3 2013 1   1   542      540             2         923      850
4 2013 1   1   544      545            -1        1004     1022
5 2013 1   1   554      600            -6         812      837
6 2013 1   1   554      558            -4         740      728
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  11       UA      1545   N14228  EWR    IAH  227      1400     5    15
2  20       UA      1714   N24211  LGA    IAH  227      1416     5    29
3  33       AA      1141   N619AA  JFK    MIA  160      1089     5    40
4 -18       B6       725   N804JB  JFK    BQN  183      1576     5    45
5 -25       DL       461   N668DN  LGA    ATL  116       762     6     0
6  12       UA      1696   N39463  EWR    ORD  150       719     5    58
  time_hour           retraso_neto
1 2013-01-01 05:00:00  13
2 2013-01-01 05:00:00  24
3 2013-01-01 05:00:00  35
4 2013-01-01 05:00:00 -19
5 2013-01-01 06:00:00 -31
6 2013-01-01 05:00:00   8

In [43]:
head(vuelos)

  anio mes dia dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1   1   517      515             2         830      819
2 2013 1   1   533      529             4         850      830
3 2013 1   1   542      540             2         923      850
4 2013 1   1   544      545            -1        1004     1022
5 2013 1   1   554      600            -6         812      837
6 2013 1   1   554      558            -4         740      728
  arr_delay carrier ⋯ tailnum origin dest air_time distance hour minute
1  11       UA      ⋯ N14228  EWR    IAH  227      1400     5    15
2  20       UA      ⋯ N24211  LGA    IAH  227      1416     5    29
3  33       AA      ⋯ N619AA  JFK    MIA  160      1089     5    40
4 -18       B6      ⋯ N804JB  JFK    BQN  183      1576     5    45
5 -25       DL      ⋯ N668DN  LGA    ATL  116       762     6     0
6  12       UA      ⋯ N39463  EWR    ORD  150       719     5    58
  time_hour           retraso_neto retraso_neto2
1 2013-01-01 05:00:00  13           13
2 2013-01-01 05:00:00  24           24
3 2013-01-01 05:00:00  35           35
4 2013-01-01 05:00:00 -19          -19
5 2013-01-01 06:00:00 -31          -31
6 2013-01-01 05:00:00   8            8

In [36]:
head(vuelos)

  anio mes dia dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1   1   517      515             2         830      819
2 2013 1   1   533      529             4         850      830
3 2013 1   1   542      540             2         923      850
4 2013 1   1   544      545            -1        1004     1022
5 2013 1   1   554      600            -6         812      837
6 2013 1   1   554      558            -4         740      728
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  11       UA      1545   N14228  EWR    IAH  227      1400     5    15
2  20       UA      1714   N24211  LGA    IAH  227      1416     5    29
3  33       AA      1141   N619AA  JFK    MIA  160      1089     5    40
4 -18       B6       725   N804JB  JFK    BQN  183      1576     5    45
5 -25       DL       461   N668DN  LGA    ATL  116       762     6     0
6  12       UA      1696   N39463  EWR    ORD  150       719     5    58
  time_hour           retraso_neto
1 2013-01-01 05:00:00  13
2 2013-01-01 05:00:00  24
3 2013-01-01 05:00:00  35
4 2013-01-01 05:00:00 -19
5 2013-01-01 06:00:00 -31
6 2013-01-01 05:00:00   8

In [55]:
# Primero defina una nueva data llamada muestra_fl que contenga la fecha, los retrasos, la distancia, y el tiempo de vuelo
muestra_fl <- select(vuelos,anio,mes,dia, arr_delay, dep_delay, distance, air_time)
head(muestra_fl)

  anio mes dia arr_delay dep_delay distance air_time
1 2013 1   1    11        2        1400     227
2 2013 1   1    20        4        1416     227
3 2013 1   1    33        2        1089     160
4 2013 1   1   -18       -1        1576     183
5 2013 1   1   -25       -6         762     116
6 2013 1   1    12       -4         719     150

In [56]:
# Cree una columna llamada gain que contenga la diferenecia entre arr_delay y dep_delay, y otra llamada speed que mida la velocidad en horas (distancia / tiempo de vuelo * 60)
mutate(muestra_fl,
       gain = arr_delay - dep_delay,
       speed = 60*distance/air_time,
       gain_abs = abs(gain),
       arr_delay = arr_delay -5) # Podemos modificar columnas existentes
# NOTA: No hemos modificado aun el dataset original (muestra_fl)

       anio mes dia arr_delay dep_delay distance air_time gain speed
1      2013 1   1     6        2        1400     227        9  370.0441
2      2013 1   1    15        4        1416     227       16  374.2731
3      2013 1   1    28        2        1089     160       31  408.3750
4      2013 1   1   -23       -1        1576     183      -17  516.7213
5      2013 1   1   -30       -6         762     116      -19  394.1379
6      2013 1   1     7       -4         719     150       16  287.6000
7      2013 1   1    14       -5        1065     158       24  404.4304
8      2013 1   1   -19       -3         229      53      -11  259.2453
9      2013 1   1   -13       -3         944     140       -5  404.5714
10     2013 1   1     3       -2         733     138       10  318.6957
11     2013 1   1    -7       -2        1028     149        0  413.9597
12     2013 1   1    -8       -2        1005     158       -1  381.6456
13     2013 1   1     2       -2        2475     345        9  430.4348
14     2013 1   1   -19       -2        2565     361      -12  426.3158
15     2013 1   1    26       -1        1389     257       32  324.2802
16     2013 1   1    -9        0         187      44       -4  255.0000
17     2013 1   1   -13       -1        2227     337       -7  396.4985
18     2013 1   1   -12        0        1076     152       -7  424.7368
19     2013 1   1     7        0         762     134       12  341.1940
20     2013 1   1   -11        1        1023     147       -7  417.5510
21     2013 1   1   -13       -8        1020     170        0  360.0000
22     2013 1   1    11       -3         502     105       19  286.8571
23     2013 1   1   -17       -4        1085     152       -8  428.2895
24     2013 1   1   -13       -4         760     128       -4  356.2500
25     2013 1   1   -22        0        1085     157      -17  414.6497
26     2013 1   1    27        8         719     139       24  310.3597
27     2013 1   1     9       11        2586     366        3  423.9344
28     2013 1   1    -1        3        1074     175        1  368.2286
29     2013 1   1   -26        0        1598     182      -21  526.8132
30     2013 1   1   -14        0         746     120       -9  373.0000
⋮      ⋮    ⋮   ⋮   ⋮         ⋮         ⋮        ⋮        ⋮    ⋮
336747 2013 9   30  -29        -2        305      45      -22  406.6667
336748 2013 9   30  -14        -2        529      72       -7  440.8333
336749 2013 9   30  -36        -2       1626     213      -29  458.0282
336750 2013 9   30   -7        30        292      45      -32  389.3333
336751 2013 9   30  -35        -9        213      36      -21  355.0000
336752 2013 9   30  -35         0       2475     298      -30  498.3221
336753 2013 9   30    6        13        284      47       -2  362.5532
336754 2013 9   30  -30         0       1598     192      -25  499.3750
336755 2013 9   30   -2        10       1076     139       -7  464.4604
336756 2013 9   30  -28        -7        200      37      -16  324.3243
336757 2013 9   30  -21        -9        209      39       -7  321.5385
336758 2013 9   30  189       194        301      50        0  361.2000
336759 2013 9   30    3        -2        378      61       10  371.8033
336760 2013 9   30    2        27        764      97      -20  472.5773
336761 2013 9   30   52        72        872     120      -15  436.0000
336762 2013 9   30  -26       -14        273      48       -7  341.2500
336763 2013 9   30   37        80       2565     318      -38  483.9623
336764 2013 9   30  125       154        944     123      -24  460.4878
336765 2013 9   30  -13        -8        266      43        0  371.1628
336766 2013 9   30  -22        -5        209      41      -12  305.8537
336767 2013 9   30  -25       -10        301      52      -10  347.3077
336768 2013 9   30  -21        -5        264      47      -11  337.0213
336769 2013 9   30   -4        12        187      33      -11  340.0000
336770 2013 9   30  -30       -10       1617     196      -15  495.0000
336771 2013 9   30   NA        NA        764      NA       NA        NA
336772 2013 9   30   NA        NA        213      NA       NA        NA
336773 2013 9   30   NA        NA        198      NA       NA        NA
336774 2013 9   30   NA        NA        764      NA       NA        NA
336775 2013 9   30   NA        NA        419      NA       NA        NA
336776 2013 9   30   NA        NA        431      NA       NA        NA
       gain_abs
1       9
2      16
3      31
4      17
5      19
6      16
7      24
8      11
9       5
10     10
11      0
12      1
13      9
14     12
15     32
16      4
17      7
18      7
19     12
20      7
21      0
22     19
23      8
24      4
25     17
26     24
27      3
28      1
29     21
30      9
⋮      ⋮
336747 22
336748  7
336749 29
336750 32
336751 21
336752 30
336753  2
336754 25
336755  7
336756 16
336757  7
336758  0
336759 10
336760 20
336761 15
336762  7
336763 38
336764 24
336765  0
336766 12
336767 10
336768 11
336769 11
336770 15
336771 NA
336772 NA
336773 NA
336774 NA
336775 NA
336776 NA

In [58]:
head(muestra_fl)
#si queremos que permanezcan ls cambios, redefinimos con "<-"
muestra_fl <- mutate(muestra_fl,
                        gain = arr_delay - dep_delay,
                        speed = 60*distance/air_time,
                        gain_abs = abs(gain),
                        arr_delay = arr_delay -5)

  anio mes dia arr_delay dep_delay distance air_time
1 2013 1   1    11        2        1400     227
2 2013 1   1    20        4        1416     227
3 2013 1   1    33        2        1089     160
4 2013 1   1   -18       -1        1576     183
5 2013 1   1   -25       -6         762     116
6 2013 1   1    12       -4         719     150

In [59]:
head(muestra_fl)

  anio mes dia arr_delay dep_delay distance air_time gain speed    gain_abs
1 2013 1   1     6        2        1400     227        9  370.0441  9
2 2013 1   1    15        4        1416     227       16  374.2731 16
3 2013 1   1    28        2        1089     160       31  408.3750 31
4 2013 1   1   -23       -1        1576     183      -17  516.7213 17
5 2013 1   1   -30       -6         762     116      -19  394.1379 19
6 2013 1   1     7       -4         719     150       16  287.6000 16

### Operador `%>%` o  `|>`

El operador estrella de dplyr. Funciona como una composición de funciones, y nos permite generar _pipe-lines_, permitiendo  que la generación  del código sea más ordenada, y con ello, su lectura más sencilla.

Este operdaor actua de la sifuiente manera, <br>

    x %>% f(y) , es equivalente a,  f(x,y)

In [61]:
# Operador %>% ----------------------------------------------------------------
# Ejemplo sencillo

# head(vuelos)


# Utilizando %>%
vuelos %>% head(3)

  anio mes dia dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1   1   517      515            2         830      819
2 2013 1   1   533      529            4         850      830
3 2013 1   1   542      540            2         923      850
  arr_delay carrier ⋯ tailnum origin dest air_time distance hour minute
1 11        UA      ⋯ N14228  EWR    IAH  227      1400     5    15
2 20        UA      ⋯ N24211  LGA    IAH  227      1416     5    29
3 33        AA      ⋯ N619AA  JFK    MIA  160      1089     5    40
  time_hour           retraso_neto retraso_neto2
1 2013-01-01 05:00:00 13           13
2 2013-01-01 05:00:00 24           24
3 2013-01-01 05:00:00 35           35

In [111]:
# Genere el conteo de vuelos por mes y día,
# luego filtre por aquellos registros donde el día es 1,
# ordene de manera descendente por n,
# finalmente muestra la cabecera del dataset resultante.
# NUEVO: antes de filtrar, luego del count, agregar una columna que repita el total de vuelos de todo el dataframe, llamada "total" (suma de todos los n)
## ANTES
head(arrange(filter(mutate(count(vuelos,mes,dia, name = "conteo"), total_vuelos = sum(conteo)), dia == 1), desc(conteo)))

  mes dia conteo total_vuelos
1  8  1   1000   336776
2 12  1    987   336776
3 11  1    986   336776
4  4  1    970   336776
5  7  1    966   336776
6 10  1    965   336776

In [104]:
?count

In [112]:
# Genere el conteo de vuelos por mes y día,
# luego filtre por aquellos registros donde el día es 1,
# ordene de manera descendente por n,
# finalmente muestra la cabecera del dataset resultante.
# NUEVO: antes de filtrar, luego del count, agregar una columna que repita el total de vuelos de todo el dataframe, llamada "total" (suma de todos los n)
## AHORA
vuelos |>
  count(mes,dia, name = "conteo") |>
  mutate(total_vuelos = sum(conteo)) |>
  filter(dia == 1) |>
  arrange(desc(conteo)) |>
  head()

  mes dia conteo total_vuelos
1  8  1   1000   336776
2 12  1    987   336776
3 11  1    986   336776
4  4  1    970   336776
5  7  1    966   336776
6 10  1    965   336776

In [113]:
# A la onsulta anterior podríamos agregar una nueva columna indicando con un "A" si el conteo vuelos es mayor a 970, y un "B" si no.
vuelos |>
  count(mes,dia, name = "conteo") |>
  mutate(total_vuelos = sum(conteo),
         cat_vuelos = ifelse(conteo > 970, "A","B") ) |>
  filter(dia == 1) |>
  arrange(desc(conteo)) |>
  head()

  mes dia conteo total_vuelos cat_vuelos
1  8  1   1000   336776       A
2 12  1    987   336776       A
3 11  1    986   336776       A
4  4  1    970   336776       B
5  7  1    966   336776       B
6 10  1    965   336776       B

In [114]:
#Alternativamente: case_when()
# Incluir el nombre del mes. Si mes = 1 , colocar "ene", es 2, colocar "feb",....
vuelos |>
  count(mes,dia, name = "conteo") |>
  mutate(total_vuelos = sum(conteo),
         cat_vuelos = ifelse(conteo > 970, "A","B") ,
         mes_str = case_when(mes == 1 ~ "ene",
                             mes == 2 ~ "feb",
                             mes == 3 ~ "mar",
                             mes == 4 ~ "abr",
                             mes == 5 ~ "may",
                             mes == 6 ~ "jun",
                             mes == 7 ~ "jul",
                             mes == 8 ~ "ago",
                             mes == 9 ~ "sep",
                             mes == 10 ~ "oct",
                             mes == 11 ~ "nov",
                             TRUE ~ "dic" ) ) |>
  filter(dia == 1) |>
  arrange(desc(conteo)) |>
  head()

  mes dia conteo total_vuelos cat_vuelos mes_str
1  8  1   1000   336776       A          ago
2 12  1    987   336776       A          dic
3 11  1    986   336776       A          nov
4  4  1    970   336776       B          abr
5  7  1    966   336776       B          jul
6 10  1    965   336776       B          oct

In [115]:
head(vuelos)

  anio mes dia dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1   1   517      515             2         830      819
2 2013 1   1   533      529             4         850      830
3 2013 1   1   542      540             2         923      850
4 2013 1   1   544      545            -1        1004     1022
5 2013 1   1   554      600            -6         812      837
6 2013 1   1   554      558            -4         740      728
  arr_delay carrier ⋯ tailnum origin dest air_time distance hour minute
1  11       UA      ⋯ N14228  EWR    IAH  227      1400     5    15
2  20       UA      ⋯ N24211  LGA    IAH  227      1416     5    29
3  33       AA      ⋯ N619AA  JFK    MIA  160      1089     5    40
4 -18       B6      ⋯ N804JB  JFK    BQN  183      1576     5    45
5 -25       DL      ⋯ N668DN  LGA    ATL  116       762     6     0
6  12       UA      ⋯ N39463  EWR    ORD  150       719     5    58
  time_hour           retraso_neto retraso_neto2
1 2013-01-01 05:00:00  13           13
2 2013-01-01 05:00:00  24           24
3 2013-01-01 05:00:00  35           35
4 2013-01-01 05:00:00 -19          -19
5 2013-01-01 06:00:00 -31          -31
6 2013-01-01 05:00:00   8            8

In [ ]:
# Genere una nueva variable llamada day2 que pegue un "0"
# a la variable day si es que esta contiene un dígito del 1 al 9.
# Para pegar cadena de caracteres sin espacios puede utilizar
# la función paste0

#?paste0, ?nchar

In [118]:
# Con esta variable genere un entero llamado fecha, que concatena year,month y day 2.
vuelos %>%
  mutate(fecha = as.Date(paste(anio,mes,dia,sep = "-")))

       anio mes dia dep_time sched_dep_time dep_delay arr_time sched_arr_time
1      2013 1   1   517      515             2         830      819
2      2013 1   1   533      529             4         850      830
3      2013 1   1   542      540             2         923      850
4      2013 1   1   544      545            -1        1004     1022
5      2013 1   1   554      600            -6         812      837
6      2013 1   1   554      558            -4         740      728
7      2013 1   1   555      600            -5         913      854
8      2013 1   1   557      600            -3         709      723
9      2013 1   1   557      600            -3         838      846
10     2013 1   1   558      600            -2         753      745
11     2013 1   1   558      600            -2         849      851
12     2013 1   1   558      600            -2         853      856
13     2013 1   1   558      600            -2         924      917
14     2013 1   1   558      600            -2         923      937
15     2013 1   1   559      600            -1         941      910
16     2013 1   1   559      559             0         702      706
17     2013 1   1   559      600            -1         854      902
18     2013 1   1   600      600             0         851      858
19     2013 1   1   600      600             0         837      825
20     2013 1   1   601      600             1         844      850
21     2013 1   1   602      610            -8         812      820
22     2013 1   1   602      605            -3         821      805
23     2013 1   1   606      610            -4         858      910
24     2013 1   1   606      610            -4         837      845
25     2013 1   1   607      607             0         858      915
26     2013 1   1   608      600             8         807      735
27     2013 1   1   611      600            11         945      931
28     2013 1   1   613      610             3         925      921
29     2013 1   1   615      615             0        1039     1100
30     2013 1   1   615      615             0         833      842
⋮      ⋮    ⋮   ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
336747 2013 9   30  2123     2125            -2       2223     2247
336748 2013 9   30  2127     2129            -2       2314     2323
336749 2013 9   30  2128     2130            -2       2328     2359
336750 2013 9   30  2129     2059            30       2230     2232
336751 2013 9   30  2131     2140            -9       2225     2255
336752 2013 9   30  2140     2140             0         10       40
336753 2013 9   30  2142     2129            13       2250     2239
336754 2013 9   30  2145     2145             0        115      140
336755 2013 9   30  2147     2137            10         30       27
336756 2013 9   30  2149     2156            -7       2245     2308
336757 2013 9   30  2150     2159            -9       2250     2306
336758 2013 9   30  2159     1845           194       2344     2030
336759 2013 9   30  2203     2205            -2       2339     2331
336760 2013 9   30  2207     2140            27       2257     2250
336761 2013 9   30  2211     2059            72       2339     2242
336762 2013 9   30  2231     2245           -14       2335     2356
336763 2013 9   30  2233     2113            80        112       30
336764 2013 9   30  2235     2001           154         59     2249
336765 2013 9   30  2237     2245            -8       2345     2353
336766 2013 9   30  2240     2245            -5       2334     2351
336767 2013 9   30  2240     2250           -10       2347        7
336768 2013 9   30  2241     2246            -5       2345        1
336769 2013 9   30  2307     2255            12       2359     2358
336770 2013 9   30  2349     2359           -10        325      350
336771 2013 9   30    NA     1842            NA         NA     2019
336772 2013 9   30    NA     1455            NA         NA     1634
336773 2013 9   30    NA     2200            NA         NA     2312
336774 2013 9   30    NA     1210            NA         NA     1330
336775 2013 9   30    NA     1159            NA         NA     1344
336776 2013 9   30    NA      840            NA         NA     1020
       arr_delay carrier ⋯ origin dest air_time distance hour minute
1       11       UA      ⋯ EWR    IAH  227      1400     5    15
2       20       UA      ⋯ LGA    IAH  227      1416     5    29
3       33       AA      ⋯ JFK    MIA  160      1089     5    40
4      -18       B6      ⋯ JFK    BQN  183      1576     5    45
5      -25       DL      ⋯ LGA    ATL  116       762     6     0
6       12       UA      ⋯ EWR    ORD  150       719     5    58
7       19       B6      ⋯ EWR    FLL  158      1065     6     0
8      -14       EV      ⋯ LGA    IAD   53       229     6     0
9       -8       B6      ⋯ JFK    MCO  140       944     6     0
10       8       AA      ⋯ LGA    ORD  138       733     6     0
11      -2       B6      ⋯ JFK    PBI  149      1028     6     0
12      -3       B6      ⋯ JFK    TPA  158      1005     6     0
13       7       UA      ⋯ JFK    LAX  345      2475     6     0
14     -14       UA      ⋯ EWR    SFO  361      2565     6     0
15      31       AA      ⋯ LGA    DFW  257      1389     6     0
16      -4       B6      ⋯ JFK    BOS   44       187     5    59
17      -8       UA      ⋯ EWR    LAS  337      2227     6     0
18      -7       B6      ⋯ LGA    FLL  152      1076     6     0
19      12       MQ      ⋯ LGA    ATL  134       762     6     0
20      -6       B6      ⋯ EWR    PBI  147      1023     6     0
21      -8       DL      ⋯ LGA    MSP  170      1020     6    10
22      16       MQ      ⋯ LGA    DTW  105       502     6     5
23     -12       AA      ⋯ EWR    MIA  152      1085     6    10
24      -8       DL      ⋯ JFK    ATL  128       760     6    10
25     -17       UA      ⋯ EWR    MIA  157      1085     6     7
26      32       MQ      ⋯ EWR    ORD  139       719     6     0
27      14       UA      ⋯ JFK    SFO  366      2586     6     0
28       4       B6      ⋯ JFK    RSW  175      1074     6    10
29     -21       B6      ⋯ JFK    SJU  182      1598     6    15
30      -9       DL      ⋯ EWR    ATL  120       746     6    15
⋮      ⋮         ⋮       ⋱ ⋮      ⋮    ⋮        ⋮        ⋮    ⋮
336747 -24       EV      ⋯ LGA    CHO   45       305     21   25
336748  -9       EV      ⋯ EWR    CLT   72       529     21   29
336749 -31       B6      ⋯ JFK    DEN  213      1626     21   30
336750  -2       EV      ⋯ LGA    RIC   45       292     20   59
336751 -30       MQ      ⋯ JFK    DCA   36       213     21   40
336752 -30       AA      ⋯ JFK    LAX  298      2475     21   40
336753  11       EV      ⋯ EWR    PWM   47       284     21   29
336754 -25       B6      ⋯ JFK    SJU  192      1598     21   45
336755   3       B6      ⋯ LGA    FLL  139      1076     21   37
336756 -23       UA      ⋯ EWR    BOS   37       200     21   56
336757 -16       EV      ⋯ EWR    MHT   39       209     21   59
336758 194       9E      ⋯ JFK    BUF   50       301     18   45
336759   8       EV      ⋯ LGA    BGR   61       378     22    5
336760   7       MQ      ⋯ LGA    BNA   97       764     21   40
336761  57       EV      ⋯ EWR    STL  120       872     20   59
336762 -21       B6      ⋯ JFK    PWM   48       273     22   45
336763  42       UA      ⋯ EWR    SFO  318      2565     21   13
336764 130       B6      ⋯ JFK    MCO  123       944     20    1
336765  -8       B6      ⋯ JFK    BTV   43       266     22   45
336766 -17       B6      ⋯ JFK    SYR   41       209     22   45
336767 -20       B6      ⋯ JFK    BUF   52       301     22   50
336768 -16       B6      ⋯ JFK    ROC   47       264     22   46
336769   1       B6      ⋯ JFK    BOS   33       187     22   55
336770 -25       B6      ⋯ JFK    PSE  196      1617     23   59
336771  NA       EV      ⋯ LGA    BNA   NA       764     18   42
336772  NA       9E      ⋯ JFK    DCA   NA       213     14   55
336773  NA       9E      ⋯ LGA    SYR   NA       198     22    0
336774  NA       MQ      ⋯ LGA    BNA   NA       764     12   10
336775  NA       MQ      ⋯ LGA    CLE   NA       419     11   59
336776  NA       MQ      ⋯ LGA    RDU   NA       431      8   40
       time_hour           retraso_neto retraso_neto2 fecha
1      2013-01-01 05:00:00  13           13           2013-01-01
2      2013-01-01 05:00:00  24           24           2013-01-01
3      2013-01-01 05:00:00  35           35           2013-01-01
4      2013-01-01 05:00:00 -19          -19           2013-01-01
5      2013-01-01 06:00:00 -31          -31           2013-01-01
6      2013-01-01 05:00:00   8            8           2013-01-01
7      2013-01-01 06:00:00  14           14           2013-01-01
8      2013-01-01 06:00:00 -17          -17           2013-01-01
9      2013-01-01 06:00:00 -11          -11           2013-01-01
10     2013-01-01 06:00:00   6            6           2013-01-01
11     2013-01-01 06:00:00  -4           -4           2013-01-01
12     2013-01-01 06:00:00  -5           -5           2013-01-01
13     2013-01-01 06:00:00   5            5           2013-01-01
14     2013-01-01 06:00:00 -16          -16           2013-01-01
15     2013-01-01 06:00:00  30           30           2013-01-01
16     2013-01-01 05:00:00  -4           -4           2013-01-01
17     2013-01-01 06:00:00  -9           -9           2013-01-01
18     2013-01-01 06:00:00  -7           -7           2013-01-01
19     2013-01-01 06:00:00  12           12           2013-01-01
20     2013-01-01 06:00:00  -5           -5           2013-01-01
21     2013-01-01 06:00:00 -16          -16           2013-01-01
22     2013-01-01 06:00:00  13           13           2013-01-01
23     2013-01-01 06:00:00 -16          -16           2013-01-01
24     2013-01-01 06:00:00 -12          -12           2013-01-01
25     2013-01-01 06:00:00 -17          -17           2013-01-01
26     2013-01-01 06:00:00  40           40           2013-01-01
27     2013-01-01 06:00:00  25           25           2013-01-01
28     2013-01-01 06:00:00   7            7           2013-01-01
29     2013-01-01 06:00:00 -21          -21           2013-01-01
30     2013-01-01 06:00:00  -9           -9           2013-01-01
⋮      ⋮                   ⋮            ⋮             ⋮
336747 2013-09-30 21:00:00 -26          -26           2013-09-30
336748 2013-09-30 21:00:00 -11          -11           2013-09-30
336749 2013-09-30 21:00:00 -33          -33           2013-09-30
336750 2013-09-30 20:00:00  28           28           2013-09-30
336751 2013-09-30 21:00:00 -39          -39           2013-09-30
336752 2013-09-30 21:00:00 -30          -30           2013-09-30
336753 2013-09-30 21:00:00  24           24           2013-09-30
336754 2013-09-30 21:00:00 -25          -25           2013-09-30
336755 2013-09-30 21:00:00  13           13           2013-09-30
336756 2013-09-30 21:00:00 -30          -30           2013-09-30
336757 2013-09-30 21:00:00 -25          -25           2013-09-30
336758 2013-09-30 18:00:00 388          388           2013-09-30
336759 2013-09-30 22:00:00   6            6           2013-09-30
336760 2013-09-30 21:00:00  34           34           2013-09-30
336761 2013-09-30 20:00:00 129          129           2013-09-30
336762 2013-09-30 22:00:00 -35          -35           2013-09-30
336763 2013-09-30 21:00:00 122          122           2013-09-30
336764 2013-09-30 20:00:00 284          284           2013-09-30
336765 2013-09-30 22:00:00 -16          -16           2013-09-30
336766 2013-09-30 22:00:00 -22          -22           2013-09-30
336767 2013-09-30 22:00:00 -30          -30           2013-09-30
336768 2013-09-30 22:00:00 -21          -21           2013-09-30
336769 2013-09-30 22:00:00  13           13           2013-09-30
336770 2013-09-30 23:00:00 -35          -35           2013-09-30
336771 2013-09-30 18:00:00  NA           NA           2013-09-30
336772 2013-09-30 14:00:00  NA           NA           2013-09-30
336773 2013-09-30 22:00:00  NA           NA           2013-09-30
336774 2013-09-30 12:00:00  NA           NA           2013-09-30
336775 2013-09-30 11:00:00  NA           NA           2013-09-30
336776 2013-09-30 08:00:00  NA           NA           2013-09-30

### 4.5 Función group_by() y summarise()

La función `summarise()` calcula medidas agregadas sobre columnas, mientras que la función `group_by`, genera un data.frame "en bloques" dados por la(s) columna(s) ingresadas como parámetros en la función.

In [119]:
# group_by() y summarise() ----------------------------------------------------------------
# Ejemplo sencillo
exam2 <- data.frame(
  x = c(1:5),
  y = c(7:11),
  z = c("A", "B", "A", "B", "C")
)
exam2

  x y  z
1 1  7 A
2 2  8 B
3 3  9 A
4 4 10 B
5 5 11 C

In [120]:
group_by(exam2, z)
# exam2 %>% group_by(z)

  x y  z
1 1  7 A
2 2  8 B
3 3  9 A
4 4 10 B
5 5 11 C

In [121]:
exam2 %>%
  mutate(tot_y = sum(y))

  x y  z tot_y
1 1  7 A 45
2 2  8 B 45
3 3  9 A 45
4 4 10 B 45
5 5 11 C 45

In [122]:

 exam2 %>%
  group_by(z) %>%
  mutate(tot_y = sum(y))

  x y  z tot_y
1 1  7 A 16
2 2  8 B 18
3 3  9 A 16
4 4 10 B 18
5 5 11 C 11

In [124]:
# Podemos generar un número de fila por cada grupo
 exam2 %>%
   mutate(rn = row_number())

exam2 %>%
   group_by(z) %>%
   mutate(rn = row_number())

  x y  z rn
1 1  7 A 1
2 2  8 B 2
3 3  9 A 3
4 4 10 B 4
5 5 11 C 5

  x y  z rn
1 1  7 A 1
2 2  8 B 1
3 3  9 A 2
4 4 10 B 2
5 5 11 C 1

In [127]:
# 1) Aplicar la función summarise a la columna 'y' y calcular su suma, la suma de x y el promedio de x
exam2 %>%
  summarise(tot_y = sum(y),
            tot_x = sum(x),
            mean_x = mean(x))

# 2) Generar grupos según la variable z. (a diferencia de sql, el comando group_by() no requiere de una medida agregada para que este funcione.)
exam2 %>%
  group_by(z) %>%
  summarise(tot_y = sum(y),
            tot_x = sum(x),
            mean_x = mean(x))

  tot_y tot_x mean_x
1 45    15    3

  z tot_y tot_x mean_x
1 A 16    4     2
2 B 18    6     3
3 C 11    5     5

In [128]:
# 3) Calcular media de x e y en cada valor de z.
# podemos calcular máximos y mínimos
exam2 %>%
  group_by(z) %>%
  summarise(mean_y = mean(y),
            max_x = max(x),
            mean_x = mean(x))

  z mean_y max_x mean_x
1 A  8     3     2
2 B  9     4     3
3 C 11     5     5

In [132]:
summary(vuelos)

      anio           mes              dia           dep_time    sched_dep_time
 Min.   :2013   Min.   : 1.000   Min.   : 1.00   Min.   :   1   Min.   : 106
 1st Qu.:2013   1st Qu.: 4.000   1st Qu.: 8.00   1st Qu.: 907   1st Qu.: 906
 Median :2013   Median : 7.000   Median :16.00   Median :1401   Median :1359
 Mean   :2013   Mean   : 6.549   Mean   :15.71   Mean   :1349   Mean   :1344
 3rd Qu.:2013   3rd Qu.:10.000   3rd Qu.:23.00   3rd Qu.:1744   3rd Qu.:1729
 Max.   :2013   Max.   :12.000   Max.   :31.00   Max.   :2400   Max.   :2359
                                                 NAs    :8255
   dep_delay          arr_time    sched_arr_time   arr_delay
 Min.   : -43.00   Min.   :   1   Min.   :   1   Min.   : -86.000
 1st Qu.:  -5.00   1st Qu.:1104   1st Qu.:1124   1st Qu.: -17.000
 Median :  -2.00   Median :1535   Median :1556   Median :  -5.000
 Mean   :  12.64   Mean   :1502   Mean   :1536   Mean   :   6.895
 3rd Qu.:  11.00   3rd Qu.:1940   3rd Qu.:1945   3rd Qu.:  14.000
 Max.   :1301.00   Max.   :2400   Max.   :2359   Max.   :1272.000
 NAs    :8255      NAs    :8713                  NAs    :9430
      carrier           flight          tailnum             origin
 Length   :336776   Min.   :   1   Length   :336776   Length   :336776
 N.unique :    16   1st Qu.: 553   N.unique :  4043   N.unique :     3
 N.blank  :     0   Median :1496   N.blank  :     0   N.blank  :     0
 Min.nchar:     2   Mean   :1972   Min.nchar:     5   Min.nchar:     3
 Max.nchar:     2   3rd Qu.:3465   Max.nchar:     6   Max.nchar:     3
                    Max.   :8500   NAs      :  2512

        dest           air_time        distance         hour
 Length   :336776   Min.   : 20.0   Min.   :  17   Min.   : 1.00
 N.unique :   105   1st Qu.: 82.0   1st Qu.: 502   1st Qu.: 9.00
 N.blank  :     0   Median :129.0   Median : 872   Median :13.00
 Min.nchar:     3   Mean   :150.7   Mean   :1040   Mean   :13.18
 Max.nchar:     3   3rd Qu.:192.0   3rd Qu.:1389   3rd Qu.:17.00
                    Max.   :695.0   Max.   :4983   Max.   :23.00
                    NAs    :9430
     minute          time_hour       retraso_neto     retraso_neto2
 Min.   : 0.00   Length   :336776   Min.   :-100.00   Min.   :-100.00
 1st Qu.: 8.00   N.unique :  6936   1st Qu.: -21.00   1st Qu.: -21.00
 Median :29.00   N.blank  :     0   Median :  -6.00   Median :  -6.00
 Mean   :26.23   Min.nchar:    19   Mean   :  19.45   Mean   :  19.45
 3rd Qu.:44.00   Max.nchar:    19   3rd Qu.:  22.00   3rd Qu.:  22.00
 Max.   :59.00                      Max.   :2573.00   Max.   :2573.00
                                    NAs    :9430      NAs    :9430

In [136]:
sum(c(1,2,NA,3), na.rm = T)
sum(c(1,2,3))
mean(c(1,2,NA,3), na.rm = T)
mean(c(1,2,3))

[1] 6

[1] 6

[1] 2

[1] 2

In [139]:
# promedio de retraso de llegada (arr_delay) por origen-destino
vuelos %>%
  group_by(origin, dest) %>%
  summarise(prom_arr_delay = mean(arr_delay, na.rm = T),
            total_vuelos = n()) # n() sirve para generar conteos de filas en una columna.

`summarise()` has regrouped the output.
ℹ Summaries were computed grouped by origin and dest.
ℹ Output is grouped by origin.
ℹ Use `summarise(.groups = "drop_last")` to silence this message.
ℹ Use `summarise(.by = c(origin, dest))` for per-operation grouping
  (`?dplyr::dplyr_by`) instead.

    origin dest prom_arr_delay total_vuelos
1   EWR    ALB  14.3971292      439
2   EWR    ANC  -2.5000000        8
3   EWR    ATL  13.2331829     5022
4   EWR    AUS  -0.4743992      968
5   EWR    AVL   8.8047809      265
6   EWR    BDL   7.0485437      443
7   EWR    BNA  12.7081660     2336
8   EWR    BOS   4.7836859     5327
9   EWR    BQN  10.8644068      297
10  EWR    BTV  12.1862302      931
11  EWR    BUF   9.6965812      973
12  EWR    BWI  15.0763359      545
13  EWR    BZN   7.6000000       36
14  EWR    CAE  44.5851064      104
15  EWR    CHS  16.1861504     1424
16  EWR    CLE   5.0358382     1754
17  EWR    CLT   7.7819334     5026
18  EWR    CMH   9.6020408      724
19  EWR    CVG  14.9255869     2673
20  EWR    DAY  18.3841060     1134
21  EWR    DCA  21.3139757     1719
22  EWR    DEN   9.0337478     2859
23  EWR    DFW   1.8981420     3148
24  EWR    DSM  23.5487179      411
25  EWR    DTW  10.9155866     3178
26  EWR    EGE  -5.3490566      110
27  EWR    FLL   7.7612299     3793
28  EWR    GRR  19.3706395      719
29  EWR    GSO  17.6622010     1120
30  EWR    GSP  18.1430636      745
⋮   ⋮      ⋮    ⋮              ⋮
195 LGA    MDW   11.0500736    2070
196 LGA    MEM    1.3464286     862
197 LGA    MHT   17.5277778     142
198 LGA    MIA   -0.0657664    5781
199 LGA    MKE    7.2528736    1525
200 LGA    MSN   15.2890995     218
201 LGA    MSP    6.1312155    3713
202 LGA    MSY    2.3336673    1011
203 LGA    MYR   -3.0000000       3
204 LGA    OMA   13.7362637      95
205 LGA    ORD    1.8334313    8857
206 LGA    ORF    7.7846154     206
207 LGA    PBI    6.0152326    2464
208 LGA    PHL    5.7792642     607
209 LGA    PIT    9.6343874    1067
210 LGA    PWM    1.8608059     278
211 LGA    RDU    8.4166172    3581
212 LGA    RIC    5.6424242     538
213 LGA    ROC    1.8101852     224
214 LGA    RSW    7.0611702     761
215 LGA    SAV  -10.5147059      68
216 LGA    SBN   14.5000000       6
217 LGA    SDF   -3.4428571     217
218 LGA    SRQ    4.5939643     737
219 LGA    STL    4.0882852    1822
220 LGA    SYR    9.2527881     293
221 LGA    TPA    8.2064911    2145
222 LGA    TVC   15.9726027      77
223 LGA    TYS    3.8943396     308
224 LGA    XNA    7.1142454     745

In [138]:
?summarise

In [140]:
# ¿Cuáles son los aeropuertos de destino con mayor retraso medio en su llegada?
vuelos %>%
  group_by(dest) %>%
  summarise(prom_arr_delay = mean(arr_delay, na.rm = T),
            total_vuelos = n()) %>%
  arrange(desc(prom_arr_delay))

    dest prom_arr_delay total_vuelos
1   CAE  41.76415        116
2   TUL  33.65986        315
3   OKC  30.61905        346
4   JAC  28.09524         25
5   TYS  24.06920        631
6   MSN  20.19604        572
7   RIC  20.11125       2454
8   CAK  19.69834        864
9   DSM  19.00574        569
10  GRR  18.18956        765
11  BHM  16.87732        297
12  PVD  16.23464        376
13  GSP  15.93544        849
14  CVG  15.36456       3941
15  SAV  15.12951        804
16  MHT  14.78755       1009
17  OMA  14.69890        849
18  CRW  14.67164        138
19  MCI  14.51406       2008
20  ALB  14.39713        439
21  MKE  14.16722       2802
22  GSO  14.11260       1606
23  IAD  13.86420       5700
24  TVC  12.96842        101
25  DAY  12.68049       1525
26  SDF  12.66938       1157
27  MDW  12.36422       4113
28  SMF  12.10993        284
29  JAX  11.84483       2720
30  BNA  11.81246       6333
⋮   ⋮    ⋮              ⋮
76  ILM    4.63551402     110
77  MYR    4.60344828      59
78  ABQ    4.38188976     254
79  IAH    4.24079040    7198
80  SJC    3.44817073     329
81  RSW    3.23814963    3537
82  SAN    3.13916574    2737
83  SRQ    3.08243131    1211
84  OAK    3.07766990     312
85  BOS    2.91439222   15508
86  SFO    2.67289152   13331
87  SJU    2.52052659    5819
88  HDN    2.14285714      15
89  PHX    2.09704733    4656
90  MTJ    1.78571429      15
91  LAX    0.54711094   16174
92  DFW    0.32212685    8738
93  MIA    0.29905978   11728
94  LAS    0.25772849    5997
95  SLC    0.17625459    2467
96  LGB   -0.06202723     668
97  MVY   -0.28571429     221
98  SEA   -1.09909910    3923
99  HNL   -1.36519258     707
100 ANC   -2.50000000       8
101 STT   -3.83590734     522
102 SNA   -7.86822660     825
103 PSP  -12.72222222      19
104 LEX  -22.00000000       1
105 LGA           NaN       1

In [ ]:
# los podemos remover mediante el argumento na.rm de la función mean()

In [ ]:
# si quisiéramos tratar los NA's, podemos hacerlo de la sgte. manera

#consultamos los NA en arr_delay

# Recordar que NA == NA retorna NA . is.na(NA) retorna TRUE

In [146]:
# Si queremos reemplazar los NA's por el promedio de arr_delay (?)
# Calcular el promedio general de arr_delay
(prom_arr_delay_global <- mean(vuelos$arr_delay, na.rm = T))

vuelos <- vuelos %>%
  mutate(arr_delay = ifelse(is.na(arr_delay), prom_arr_delay_global, arr_delay))

[1] 6.895377

In [147]:
vuelos %>% filter(is.na(arr_delay)) # No hay NA

Warning message in cbind(parts$left, chars$ellip_h, parts$right, deparse.level = 0L):
“number of rows of result is not a multiple of vector length (arg 2)”
Warning message in cbind(parts$left, chars$ellip_h, parts$right, deparse.level = 0L):
“number of rows of result is not a multiple of vector length (arg 2)”
Warning message in cbind(parts$left, chars$ellip_h, parts$right, deparse.level = 0L):
“number of rows of result is not a multiple of vector length (arg 2)”
Warning message in cbind(parts$left, chars$ellip_h, parts$right, deparse.level = 0L):
“number of rows of result is not a multiple of vector length (arg 2)”

     anio mes dia dep_time sched_dep_time dep_delay arr_time sched_arr_time
     arr_delay carrier ⋯ tailnum origin dest air_time distance hour minute
     time_hour retraso_neto retraso_neto2

In [ ]:
# ¿Cuál es el promedio de arr_delay y distance por cada aeropuerto de destino?¿Cuántos vuelos llegaron acada uno de los destinos?. Ayuda: Recuerde que el conteo se puede determinar de dos maneras: con la función count() o con la función n().

### 4.6 Función sample_n() y sample_frac()

Estas funciones nos permitirán extraer muestras aleatorias de nuestros conjuntos de datos. Esto será de suma importancia cuando trabajemos con modelos de ML.

In [150]:
# sample_n() y sample_frac()-------------------------------------------------------------

# muestra aleatoria de 100 registros de vuelos

vuelos %>%
  sample_n(10)

   anio mes dia dep_time sched_dep_time dep_delay arr_time sched_arr_time
1  2013 12  26  2102     2040           22        2235     2238
2  2013  6  14  1253     1300           -7        1504     1505
3  2013  8   8   825      830           -5        1021     1015
4  2013 10   3  2107     2059            8          44       58
5  2013  4   9  2112     2115           -3        2340     2356
6  2013  3  19   828      828            0        1127     1132
7  2013  5  20  1013     1009            4        1243     1308
8  2013 11  16   623      630           -7         813      805
9  2013  2  13   721      730           -9        1046     1040
10 2013 12  10  1633     1635           -2        1810     1825
   arr_delay carrier ⋯ tailnum origin dest air_time distance hour minute
1   -3       9E      ⋯ N292PQ  LGA    RDU   69       431     20   40
2   -1       MQ      ⋯ N723MQ  LGA    DTW   94       502     13    0
3    6       EV      ⋯ N14952  EWR    MEM  135       946      8   30
4  -14       DL      ⋯ N3769L  JFK    SJU  188      1598     20   59
5  -16       B6      ⋯ N564JB  EWR    MCO  124       937     21   15
6   -5       UA      ⋯ N39450  EWR    MCO  157       937      8   28
7  -25       UA      ⋯ N559UA  EWR    LAX  308      2454     10    9
8    8       AA      ⋯ N570AA  LGA    ORD  130       733      6   30
9    6       AA      ⋯ N4YFAA  EWR    DFW  217      1372      7   30
10 -15       AA      ⋯ N4YLAA  LGA    ORD  129       733     16   35
   time_hour           retraso_neto retraso_neto2
1  2013-12-26 20:00:00  19           19
2  2013-06-14 13:00:00  -8           -8
3  2013-08-08 08:00:00   1            1
4  2013-10-03 20:00:00  -6           -6
5  2013-04-09 21:00:00 -19          -19
6  2013-03-19 08:00:00  -5           -5
7  2013-05-20 10:00:00 -21          -21
8  2013-11-16 06:00:00   1            1
9  2013-02-13 07:00:00  -3           -3
10 2013-12-10 16:00:00 -17          -17

In [151]:
vuelos %>%
  sample_frac(0.01)

     anio mes dia dep_time sched_dep_time dep_delay arr_time sched_arr_time
1    2013  4   2   744      745            -1       1026     1039
2    2013  2  17   823      835           -12       1053     1134
3    2013  8   7  1000     1005            -5       1202     1120
4    2013  6  10  1347     1345             2       1521     1530
5    2013  4   1  1712     1720            -8       1910     1910
6    2013 12   5  1710     1715            -5       2044     2035
7    2013  6  19  1113     1115            -2       1259     1252
8    2013  4   5  2030     2032            -2       2337        3
9    2013  7   9  2250     1855           235        147     2215
10   2013  9  16  1155     1200            -5       1336     1334
11   2013  4  27  1726     1730            -4       1900     1919
12   2013 10   3  1702     1613            49       1811     1730
13   2013  4   9  1655     1700            -5       1937     1955
14   2013 11  30  2119     2018            61       2348     2313
15   2013  9  14  1406     1410            -4       1619     1635
16   2013  7   5  1020     1017             3       1126     1124
17   2013  4  25  2143     2145            -2         53      105
18   2013 11  20  1542     1545            -3       1646     1705
19   2013  7  20  1842     1830            12       2001     1955
20   2013  4   9  1628     1630            -2       1908     1958
21   2013  7  11  1519     1520            -1       1701     1705
22   2013  4   1  2040     2015            25         38       11
23   2013 11  24  2036     2001            35       2322     2252
24   2013 11  20   809      810            -1       1021     1034
25   2013  2  28  1424     1425            -1       1729     1750
26   2013  8  12  2019     2021            -2       2145     2200
27   2013  8   2  1450     1448             2       1741     1745
28   2013  6  21  2206     2015           111       2400     2236
29   2013  4  22   836      825            11       1149     1122
30   2013  4  20  1602     1605            -3       2026     1921
⋮    ⋮    ⋮   ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
3339 2013  8   3   600      600             0        712      725
3340 2013  4  23  1021     1030            -9       1401     1340
3341 2013  5   9  1118     1115             3       1347     1341
3342 2013 12  30  1156     1200            -4       1358     1400
3343 2013  4  11  1557     1600            -3       1708     1720
3344 2013  3  13  2051     2100            -9       2154     2215
3345 2013 10  22  2126     2015            71       2306     2153
3346 2013  4   9  2258     2120            98         31     2315
3347 2013 12  11  1728     1730            -2       2045     2112
3348 2013  6  13  1516     1344            92       1847     1621
3349 2013  7  18    NA     1000            NA         NA     1125
3350 2013  5  29   821      825            -4       1014     1023
3351 2013 10  10  1708     1642            26       1843     1837
3352 2013 10  11  2201     2113            48         45       30
3353 2013  5   7  1522     1530            -8       1829     1831
3354 2013  3   1   801      808            -7        926      923
3355 2013  3   9  1859     1855             4       2042     2049
3356 2013  6  14   755      800            -5        956      958
3357 2013 10   4  1625     1600            25       1857     1828
3358 2013  3  24  1447     1445             2       1653     1647
3359 2013  7   4   652      645             7        752      752
3360 2013  9  26   732      735            -3       1009     1031
3361 2013  4  18    NA      940            NA         NA     1114
3362 2013 11  20   827      830            -3        946     1013
3363 2013 10  15   737      749           -12       1022     1043
3364 2013  6  30  2241     2131            70         58       45
3365 2013 12   4   649      655            -6        753      804
3366 2013  3  28  1111     1050            21       1253     1250
3367 2013  4  25  1520     1525            -5       1748     1730
3368 2013  3  22  1640     1610            30       1738     1736
     arr_delay  carrier ⋯ tailnum origin dest air_time distance hour minute
1    -13        UA      ⋯ N73299  EWR    MCO  141       937      7   45
2    -41        B6      ⋯ N580JB  EWR    MCO  130       937      8   35
3     42        MQ      ⋯ N527MQ  EWR    ORD  137       719     10    5
4     -9        MQ      ⋯ N723MQ  LGA    CLE   68       419     13   45
5      0        AA      ⋯ N514AA  LGA    ORD  119       733     17   20
6      9        AA      ⋯ N3FTAA  JFK    AUS  237      1521     17   15
7      7        EV      ⋯ N723EV  LGA    PIT   56       335     11   15
8    -26        B6      ⋯ N709JB  JFK    LAX  332      2475     20   32
9    212        VX      ⋯ N634VA  JFK    SFO  339      2586     18   55
10     2        UA      ⋯ N848UA  LGA    ORD  110       733     12    0
11   -19        US      ⋯ N660AW  EWR    CLT   78       529     17   30
12    41        EV      ⋯ N14959  EWR    IAD   41       212     16   13
13   -18        AA      ⋯ N3ETAA  JFK    LAS  301      2248     17    0
14    35        B6      ⋯ N794JB  JFK    PBI  132      1028     20   18
15   -16        FL      ⋯ N956AT  LGA    ATL  103       762     14   10
16     2        B6      ⋯ N258JB  JFK    BOS   43       187     10   17
17   -12        AA      ⋯ N327AA  JFK    LAX  332      2475     21   45
18   -19        AA      ⋯ N3HKAA  JFK    BOS   35       187     15   45
19     6        MQ      ⋯ N836MQ  LGA    BNA  110       764     18   30
20   -50        B6      ⋯ N775JB  JFK    LAX  317      2475     16   30
21    -4        AA      ⋯ N425AA  LGA    STL  130       888     15   20
22    27        UA      ⋯ N73275  EWR    SJU  212      1608     20   15
23    30        B6      ⋯ N708JB  JFK    MCO  130       944     20    1
24   -13        DL      ⋯ N326NB  LGA    MSY  161      1183      8   10
25   -21        UA      ⋯ N508UA  JFK    SFO  335      2586     14   25
26   -15        UA      ⋯ N33714  EWR    CLE   67       404     20   21
27    -4        UA      ⋯ N68453  EWR    SAN  333      2425     14   48
28    84        EV      ⋯ N11165  EWR    TUL  155      1215     20   15
29    27        DL      ⋯ N970DL  JFK    MCO  151       944      8   25
30    65        DL      ⋯ N320US  JFK    MIA  211      1089     16    5
⋮    ⋮          ⋮       ⋱ ⋮       ⋮      ⋮    ⋮        ⋮        ⋮    ⋮
3339 -13.000000 UA      ⋯ N855UA  LGA    ORD  120       733      6    0
3340  21.000000 AA      ⋯ N335AA  JFK    LAX  368      2475     10   30
3341   6.000000 UA      ⋯ N437UA  LGA    DEN  219      1620     11   15
3342  -2.000000 US      ⋯ N554UW  JFK    CLT   97       541     12    0
3343 -12.000000 AA      ⋯ N3ABAA  JFK    BOS   32       187     16    0
3344 -21.000000 US      ⋯ N753US  LGA    DCA   46       214     21    0
3345  73.000000 EV      ⋯ N15910  EWR    GSO   76       445     20   15
3346  76.000000 EV      ⋯ N12167  EWR    CLT   75       529     21   20
3347 -27.000000 DL      ⋯ N703TW  JFK    SFO  351      2586     17   30
3348 146.000000 B6      ⋯ N571JB  EWR    MCO  139       937     13   44
3349   6.895377 EV      ⋯ N836AS  LGA    IAD   NA       229     10    0
3350  -9.000000 B6      ⋯ N228JB  JFK    CLT   76       541      8   25
3351   6.000000 DL      ⋯ N370NW  EWR    DTW   74       488     16   42
3352  15.000000 UA      ⋯ N567UA  EWR    SFO  322      2565     21   13
3353  -2.000000 DL      ⋯ N317US  LGA    TPA  142      1010     15   30
3354   3.000000 EV      ⋯ N19966  EWR    BTV   49       266      8    8
3355  -7.000000 9E      ⋯ N840AY  JFK    PIT   64       340     18   55
3356  -2.000000 B6      ⋯ N283JB  JFK    CHS   94       636      8    0
3357  29.000000 9E      ⋯ N914XJ  JFK    MSP  189      1029     16    0
3358   6.000000 US      ⋯ N179UW  LGA    CLT   99       544     14   45
3359   0.000000 B6      ⋯ N229JB  JFK    BOS   38       187      6   45
3360 -22.000000 DL      ⋯ N704X   JFK    SEA  319      2422      7   35
3361   6.895377 UA      ⋯ NA      EWR    ORD   NA       719      9   40
3362 -27.000000 9E      ⋯ N272PQ  JFK    ORD  117       740      8   30
3363 -21.000000 B6      ⋯ N621JB  LGA    TPA  130      1010      7   49
3364  13.000000 UA      ⋯ N76503  EWR    LAX  295      2454     21   31
3365 -11.000000 B6      ⋯ N353JB  JFK    BOS   42       187      6   55
3366   3.000000 MQ      ⋯ N501MQ  LGA    DTW   71       502     10   50
3367  18.000000 MQ      ⋯ N512MQ  LGA    CLT   86       544     15   25
3368   2.000000 9E      ⋯ N8883E  JFK    PHL   33        94     16   10
     time_hour           retraso_neto retraso_neto2
1    2013-04-02 07:00:00 -14          -14
2    2013-02-17 08:00:00 -53          -53
3    2013-08-07 10:00:00  37           37
4    2013-06-10 13:00:00  -7           -7
5    2013-04-01 17:00:00  -8           -8
6    2013-12-05 17:00:00   4            4
7    2013-06-19 11:00:00   5            5
8    2013-04-05 20:00:00 -28          -28
9    2013-07-09 18:00:00 447          447
10   2013-09-16 12:00:00  -3           -3
11   2013-04-27 17:00:00 -23          -23
12   2013-10-03 16:00:00  90           90
13   2013-04-09 17:00:00 -23          -23
14   2013-11-30 20:00:00  96           96
15   2013-09-14 14:00:00 -20          -20
16   2013-07-05 10:00:00   5            5
17   2013-04-25 21:00:00 -14          -14
18   2013-11-20 15:00:00 -22          -22
19   2013-07-20 18:00:00  18           18
20   2013-04-09 16:00:00 -52          -52
21   2013-07-11 15:00:00  -5           -5
22   2013-04-01 20:00:00  52           52
23   2013-11-24 20:00:00  65           65
24   2013-11-20 08:00:00 -14          -14
25   2013-02-28 14:00:00 -22          -22
26   2013-08-12 20:00:00 -17          -17
27   2013-08-02 14:00:00  -2           -2
28   2013-06-21 20:00:00 195          195
29   2013-04-22 08:00:00  38           38
30   2013-04-20 16:00:00  62           62
⋮    ⋮                   ⋮            ⋮
3339 2013-08-03 06:00:00 -13          -13
3340 2013-04-23 10:00:00  12           12
3341 2013-05-09 11:00:00   9            9
3342 2013-12-30 12:00:00  -6           -6
3343 2013-04-11 16:00:00 -15          -15
3344 2013-03-13 21:00:00 -30          -30
3345 2013-10-22 20:00:00 144          144
3346 2013-04-09 21:00:00 174          174
3347 2013-12-11 17:00:00 -29          -29
3348 2013-06-13 13:00:00 238          238
3349 2013-07-18 10:00:00  NA           NA
3350 2013-05-29 08:00:00 -13          -13
3351 2013-10-10 16:00:00  32           32
3352 2013-10-11 21:00:00  63           63
3353 2013-05-07 15:00:00 -10          -10
3354 2013-03-01 08:00:00  -4           -4
3355 2013-03-09 18:00:00  -3           -3
3356 2013-06-14 08:00:00  -7           -7
3357 2013-10-04 16:00:00  54           54
3358 2013-03-24 14:00:00   8            8
3359 2013-07-04 06:00:00   7            7
3360 2013-09-26 07:00:00 -25          -25
3361 2013-04-18 09:00:00  NA           NA
3362 2013-11-20 08:00:00 -30          -30
3363 2013-10-15 07:00:00 -33          -33
3364 2013-06-30 21:00:00  83           83
3365 2013-12-04 06:00:00 -17          -17
3366 2013-03-28 10:00:00  24           24
3367 2013-04-25 15:00:00  13           13
3368 2013-03-22 16:00:00  32           32