<a href="https://colab.research.google.com/github/majorquev/DBDC_202604_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/Clase3/Clase3_01_manipulacion_de_tablas_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 2: Manipulación de tablas en R (Parte I)


**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales<br>
**E-mail ayudante:** rumorale1@gmail.com

## 1. Instalación de librerías

En esta sección aprenderemos a realizar operaciones simples de manipulación de tablas en R. Para ello trabajaremos con la librería _dplyr_, la cual cuenta con una gran variedad de funciones para manipular tablas, entre otras.


Una manera de instalar librerías en R es me diante la función `install.packages()`, la cual recibe como argunmento principal el nombre (enre comillas) de la librería que se desea cargar.

Una vez instalada la librería la debemos cargar en la sesión de trbajao, para lo cual podemos utilizar la función `library()` la cual recibe como argumento el nombre de la librería que se quiere cargar.

In [1]:
install.packages("dplyr")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [2]:
glimpse(list(1))

ERROR: Error in glimpse(list(1)): could not find function "glimpse"

In [3]:
# 1. Instalación de package
# install.packages("dplyr") # No instalaremos la librería pues ya viene cargada en los notebooks de azure.Probablemente sea necesario hacerlo en su entorno local.
# Para cargar la librería
library("dplyr") # sin comillas también funciona

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

## 2. Funciones básicas en dplyr

En todo proyecto analítico es necesario procesar, limpar y unificar disntintas fuentes de información para poder generar los análisis requeridos. Para dichas tareas, en la librería _dplyr_ contamos con funciones que nos permitirán filtrar datos, crear columnas, agrupar tablas, y cruzar tablas.

A continuación trabajaremos con la siguientes funciones:<br>

   `filter()`                        : Para filtrar los datos (por filas).<br>
   `arrange()`                       : Para ordenar un dataset.<br>
   `select()`                        : Para seleccionar y renombrar columnas.<br>
   `mutate()`                        : Para crear (o modificar) nuevas columnas basadas en columnas existentes.<br>
   `group_by()`                     : Para agrupar tablas.<br>
   `sample_n()` and `sample_frac()`  : Para generar muestras aleatorias<br>
   
   
Para entender el funcionamiento de estas funciones trabjaremos con el set de datos _nycflights13_, el cual contiene la información de los vuelos con salida en los aeropuertos de Nueva York en el año 2013.

## 3. Carga de datos

En R es posible cargar datos provenientes de archivos de texto plano. Un ejemplo de ellos son los de extensión *.csv (comma separated values). Para cargar los datos a la sesión, lo podemos realizar a través de la función `read.csv()`, la cual recibe como argumento principal la ruta del archivo a cargar.

In [5]:
getwd()
# setwd(la ruta que desean)

[1] "/content"

In [7]:
# Carga de datos ------
# Usaremos la función read.csv para cargar el archivo Datasets_flights.csv ubicado en "./Datasets/", y lo guardamos en una variable llamada vuelo.

vuelos <- read.csv("flights.csv", header = T, sep = ",", dec = "." )

In [9]:
test <- read.csv("/content/sample_data/mnist_test.csv") # Debemos indicar la ruta completa si el archivo no está en el WD (directorio de trabajo)

In [8]:
vuelos

       year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1      2013 1     1   517      515             2         830      819
2      2013 1     1   533      529             4         850      830
3      2013 1     1   542      540             2         923      850
4      2013 1     1   544      545            -1        1004     1022
5      2013 1     1   554      600            -6         812      837
6      2013 1     1   554      558            -4         740      728
7      2013 1     1   555      600            -5         913      854
8      2013 1     1   557      600            -3         709      723
9      2013 1     1   557      600            -3         838      846
10     2013 1     1   558      600            -2         753      745
11     2013 1     1   558      600            -2         849      851
12     2013 1     1   558      600            -2         853      856
13     2013 1     1   558      600            -2         924      917
14     2013 1     1   558      600            -2         923      937
15     2013 1     1   559      600            -1         941      910
16     2013 1     1   559      559             0         702      706
17     2013 1     1   559      600            -1         854      902
18     2013 1     1   600      600             0         851      858
19     2013 1     1   600      600             0         837      825
20     2013 1     1   601      600             1         844      850
21     2013 1     1   602      610            -8         812      820
22     2013 1     1   602      605            -3         821      805
23     2013 1     1   606      610            -4         858      910
24     2013 1     1   606      610            -4         837      845
25     2013 1     1   607      607             0         858      915
26     2013 1     1   608      600             8         807      735
27     2013 1     1   611      600            11         945      931
28     2013 1     1   613      610             3         925      921
29     2013 1     1   615      615             0        1039     1100
30     2013 1     1   615      615             0         833      842
⋮      ⋮    ⋮     ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
336747 2013 9     30  2123     2125            -2       2223     2247
336748 2013 9     30  2127     2129            -2       2314     2323
336749 2013 9     30  2128     2130            -2       2328     2359
336750 2013 9     30  2129     2059            30       2230     2232
336751 2013 9     30  2131     2140            -9       2225     2255
336752 2013 9     30  2140     2140             0         10       40
336753 2013 9     30  2142     2129            13       2250     2239
336754 2013 9     30  2145     2145             0        115      140
336755 2013 9     30  2147     2137            10         30       27
336756 2013 9     30  2149     2156            -7       2245     2308
336757 2013 9     30  2150     2159            -9       2250     2306
336758 2013 9     30  2159     1845           194       2344     2030
336759 2013 9     30  2203     2205            -2       2339     2331
336760 2013 9     30  2207     2140            27       2257     2250
336761 2013 9     30  2211     2059            72       2339     2242
336762 2013 9     30  2231     2245           -14       2335     2356
336763 2013 9     30  2233     2113            80        112       30
336764 2013 9     30  2235     2001           154         59     2249
336765 2013 9     30  2237     2245            -8       2345     2353
336766 2013 9     30  2240     2245            -5       2334     2351
336767 2013 9     30  2240     2250           -10       2347        7
336768 2013 9     30  2241     2246            -5       2345        1
336769 2013 9     30  2307     2255            12       2359     2358
336770 2013 9     30  2349     2359           -10        325      350
336771 2013 9     30    NA     1842            NA         NA     2019
336772 2013 9     30    NA     1455            NA         NA     1634
336773 2013 9     30    NA     2200            NA         NA     2312
336774 2013 9     30    NA     1210            NA         NA     1330
336775 2013 9     30    NA     1159            NA         NA     1344
336776 2013 9     30    NA      840            NA         NA     1020
       arr_delay carrier flight tailnum origin dest air_time distance hour
1       11       UA      1545   N14228  EWR    IAH  227      1400     5
2       20       UA      1714   N24211  LGA    IAH  227      1416     5
3       33       AA      1141   N619AA  JFK    MIA  160      1089     5
4      -18       B6       725   N804JB  JFK    BQN  183      1576     5
5      -25       DL       461   N668DN  LGA    ATL  116       762     6
6       12       UA      1696   N39463  EWR    ORD  150       719     5
7       19       B6       507   N516JB  EWR    FLL  158      1065     6
8      -14       EV      5708   N829AS  LGA    IAD   53       229     6
9       -8       B6        79   N593JB  JFK    MCO  140       944     6
10       8       AA       301   N3ALAA  LGA    ORD  138       733     6
11      -2       B6        49   N793JB  JFK    PBI  149      1028     6
12      -3       B6        71   N657JB  JFK    TPA  158      1005     6
13       7       UA       194   N29129  JFK    LAX  345      2475     6
14     -14       UA      1124   N53441  EWR    SFO  361      2565     6
15      31       AA       707   N3DUAA  LGA    DFW  257      1389     6
16      -4       B6      1806   N708JB  JFK    BOS   44       187     5
17      -8       UA      1187   N76515  EWR    LAS  337      2227     6
18      -7       B6       371   N595JB  LGA    FLL  152      1076     6
19      12       MQ      4650   N542MQ  LGA    ATL  134       762     6
20      -6       B6       343   N644JB  EWR    PBI  147      1023     6
21      -8       DL      1919   N971DL  LGA    MSP  170      1020     6
22      16       MQ      4401   N730MQ  LGA    DTW  105       502     6
23     -12       AA      1895   N633AA  EWR    MIA  152      1085     6
24      -8       DL      1743   N3739P  JFK    ATL  128       760     6
25     -17       UA      1077   N53442  EWR    MIA  157      1085     6
26      32       MQ      3768   N9EAMQ  EWR    ORD  139       719     6
27      14       UA       303   N532UA  JFK    SFO  366      2586     6
28       4       B6       135   N635JB  JFK    RSW  175      1074     6
29     -21       B6       709   N794JB  JFK    SJU  182      1598     6
30      -9       DL       575   N326NB  EWR    ATL  120       746     6
⋮      ⋮         ⋮       ⋮      ⋮       ⋮      ⋮    ⋮        ⋮        ⋮
336747 -24       EV      5489   N712EV  LGA    CHO   45       305     21
336748  -9       EV      3833   N16546  EWR    CLT   72       529     21
336749 -31       B6        97   N807JB  JFK    DEN  213      1626     21
336750  -2       EV      5048   N751EV  LGA    RIC   45       292     20
336751 -30       MQ      3621   N807MQ  JFK    DCA   36       213     21
336752 -30       AA       185   N335AA  JFK    LAX  298      2475     21
336753  11       EV      4509   N12957  EWR    PWM   47       284     21
336754 -25       B6      1103   N633JB  JFK    SJU  192      1598     21
336755   3       B6      1371   N627JB  LGA    FLL  139      1076     21
336756 -23       UA       523   N813UA  EWR    BOS   37       200     21
336757 -16       EV      3842   N10575  EWR    MHT   39       209     21
336758 194       9E      3320   N906XJ  JFK    BUF   50       301     18
336759   8       EV      5311   N722EV  LGA    BGR   61       378     22
336760   7       MQ      3660   N532MQ  LGA    BNA   97       764     21
336761  57       EV      4672   N12145  EWR    STL  120       872     20
336762 -21       B6       108   N193JB  JFK    PWM   48       273     22
336763  42       UA       471   N578UA  EWR    SFO  318      2565     21
336764 130       B6      1083   N804JB  JFK    MCO  123       944     20
336765  -8       B6       234   N318JB  JFK    BTV   43       266     22
336766 -17       B6      1816   N354JB  JFK    SYR   41       209     22
336767 -20       B6      2002   N281JB  JFK    BUF   52       301     22
336768 -16       B6       486   N346JB  JFK    ROC   47       264     22
336769   1       B6       718   N565JB  JFK    BOS   33       187     22
336770 -25       B6       745   N516JB  JFK    PSE  196      1617     23
336771  NA       EV      5274   N740EV  LGA    BNA   NA       764     18
336772  NA       9E      3393   NA      JFK    DCA   NA       213     14
336773  NA       9E      3525   NA      LGA    SYR   NA       198     22
336774  NA       MQ      3461   N535MQ  LGA    BNA   NA       764     12
336775  NA       MQ      3572   N511MQ  LGA    CLE   NA       419     11
336776  NA       MQ      3531   N839MQ  LGA    RDU   NA       431      8
       minute time_hour
1      15     2013-01-01 05:00:00
2      29     2013-01-01 05:00:00
3      40     2013-01-01 05:00:00
4      45     2013-01-01 05:00:00
5       0     2013-01-01 06:00:00
6      58     2013-01-01 05:00:00
7       0     2013-01-01 06:00:00
8       0     2013-01-01 06:00:00
9       0     2013-01-01 06:00:00
10      0     2013-01-01 06:00:00
11      0     2013-01-01 06:00:00
12      0     2013-01-01 06:00:00
13      0     2013-01-01 06:00:00
14      0     2013-01-01 06:00:00
15      0     2013-01-01 06:00:00
16     59     2013-01-01 05:00:00
17      0     2013-01-01 06:00:00
18      0     2013-01-01 06:00:00
19      0     2013-01-01 06:00:00
20      0     2013-01-01 06:00:00
21     10     2013-01-01 06:00:00
22      5     2013-01-01 06:00:00
23     10     2013-01-01 06:00:00
24     10     2013-01-01 06:00:00
25      7     2013-01-01 06:00:00
26      0     2013-01-01 06:00:00
27      0     2013-01-01 06:00:00
28     10     2013-01-01 06:00:00
29     15     2013-01-01 06:00:00
30     15     2013-01-01 06:00:00
⋮      ⋮      ⋮
336747 25     2013-09-30 21:00:00
336748 29     2013-09-30 21:00:00
336749 30     2013-09-30 21:00:00
336750 59     2013-09-30 20:00:00
336751 40     2013-09-30 21:00:00
336752 40     2013-09-30 21:00:00
336753 29     2013-09-30 21:00:00
336754 45     2013-09-30 21:00:00
336755 37     2013-09-30 21:00:00
336756 56     2013-09-30 21:00:00
336757 59     2013-09-30 21:00:00
336758 45     2013-09-30 18:00:00
336759  5     2013-09-30 22:00:00
336760 40     2013-09-30 21:00:00
336761 59     2013-09-30 20:00:00
336762 45     2013-09-30 22:00:00
336763 13     2013-09-30 21:00:00
336764  1     2013-09-30 20:00:00
336765 45     2013-09-30 22:00:00
336766 45     2013-09-30 22:00:00
336767 50     2013-09-30 22:00:00
336768 46     2013-09-30 22:00:00
336769 55     2013-09-30 22:00:00
336770 59     2013-09-30 23:00:00
336771 42     2013-09-30 18:00:00
336772 55     2013-09-30 14:00:00
336773  0     2013-09-30 22:00:00
336774 10     2013-09-30 12:00:00
336775 59     2013-09-30 11:00:00
336776 40     2013-09-30 08:00:00

In [14]:
# Podemos inspeccionar los datos cargados
# Para ello son de utilidad las funciones head() y tail()
head(vuelos,3)
tail(vuelos,3)

  year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     1   517      515            2         830      819
2 2013 1     1   533      529            4         850      830
3 2013 1     1   542      540            2         923      850
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1 11        UA      1545   N14228  EWR    IAH  227      1400     5    15
2 20        UA      1714   N24211  LGA    IAH  227      1416     5    29
3 33        AA      1141   N619AA  JFK    MIA  160      1089     5    40
  time_hour
1 2013-01-01 05:00:00
2 2013-01-01 05:00:00
3 2013-01-01 05:00:00

       year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
336774 2013 9     30  NA       1210           NA        NA       1330
336775 2013 9     30  NA       1159           NA        NA       1344
336776 2013 9     30  NA        840           NA        NA       1020
       arr_delay carrier flight tailnum origin dest air_time distance hour
336774 NA        MQ      3461   N535MQ  LGA    BNA  NA       764      12
336775 NA        MQ      3572   N511MQ  LGA    CLE  NA       419      11
336776 NA        MQ      3531   N839MQ  LGA    RDU  NA       431       8
       minute time_hour
336774 10     2013-09-30 12:00:00
336775 59     2013-09-30 11:00:00
336776 40     2013-09-30 08:00:00

In [17]:
# Filas, summary() y otros...
# ¿Cuántos registros tienen las tablas?
class(vuelos)
dim(vuelos)
nrow(vuelos)

[1] "data.frame"

[1] 336776     19

[1] 336776

In [18]:
summary(vuelos)

      year          month             day           dep_time    sched_dep_time
 Min.   :2013   Min.   : 1.000   Min.   : 1.00   Min.   :   1   Min.   : 106
 1st Qu.:2013   1st Qu.: 4.000   1st Qu.: 8.00   1st Qu.: 907   1st Qu.: 906
 Median :2013   Median : 7.000   Median :16.00   Median :1401   Median :1359
 Mean   :2013   Mean   : 6.549   Mean   :15.71   Mean   :1349   Mean   :1344
 3rd Qu.:2013   3rd Qu.:10.000   3rd Qu.:23.00   3rd Qu.:1744   3rd Qu.:1729
 Max.   :2013   Max.   :12.000   Max.   :31.00   Max.   :2400   Max.   :2359
                                                 NA's   :8255
   dep_delay          arr_time    sched_arr_time   arr_delay
 Min.   : -43.00   Min.   :   1   Min.   :   1   Min.   : -86.000
 1st Qu.:  -5.00   1st Qu.:1104   1st Qu.:1124   1st Qu.: -17.000
 Median :  -2.00   Median :1535   Median :1556   Median :  -5.000
 Mean   :  12.64   Mean   :1502   Mean   :1536   Mean   :   6.895
 3rd Qu.:  11.00   3rd Qu.:1940   3rd Qu.:1945   3rd Qu.:  14.000
 Max.   :1301.00   Max.   :2400   Max.   :2359   Max.   :1272.000
 NA's   :8255      NA's   :8713                  NA's   :9430
   carrier              flight       tailnum             origin
 Length:336776      Min.   :   1   Length:336776      Length:336776
 Class :character   1st Qu.: 553   Class :character   Class :character
 Mode  :character   Median :1496   Mode  :character   Mode  :character
                    Mean   :1972
                    3rd Qu.:3465
                    Max.   :8500

     dest              air_time        distance         hour
 Length:336776      Min.   : 20.0   Min.   :  17   Min.   : 1.00
 Class :character   1st Qu.: 82.0   1st Qu.: 502   1st Qu.: 9.00
 Mode  :character   Median :129.0   Median : 872   Median :13.00
                    Mean   :150.7   Mean   :1040   Mean   :13.18
                    3rd Qu.:192.0   3rd Qu.:1389   3rd Qu.:17.00
                    Max.   :695.0   Max.   :4983   Max.   :23.00
                    NA's   :9430
     minute       time_hour
 Min.   : 0.00   Length:336776
 1st Qu.: 8.00   Class :character
 Median :29.00   Mode  :character
 Mean   :26.23
 3rd Qu.:44.00
 Max.   :59.00

## NOTA: factores

In [19]:
vuelos$carrier <- as.factor(vuelos$carrier)

In [20]:
summary(vuelos)

      year          month             day           dep_time    sched_dep_time
 Min.   :2013   Min.   : 1.000   Min.   : 1.00   Min.   :   1   Min.   : 106
 1st Qu.:2013   1st Qu.: 4.000   1st Qu.: 8.00   1st Qu.: 907   1st Qu.: 906
 Median :2013   Median : 7.000   Median :16.00   Median :1401   Median :1359
 Mean   :2013   Mean   : 6.549   Mean   :15.71   Mean   :1349   Mean   :1344
 3rd Qu.:2013   3rd Qu.:10.000   3rd Qu.:23.00   3rd Qu.:1744   3rd Qu.:1729
 Max.   :2013   Max.   :12.000   Max.   :31.00   Max.   :2400   Max.   :2359
                                                 NA's   :8255
   dep_delay          arr_time    sched_arr_time   arr_delay
 Min.   : -43.00   Min.   :   1   Min.   :   1   Min.   : -86.000
 1st Qu.:  -5.00   1st Qu.:1104   1st Qu.:1124   1st Qu.: -17.000
 Median :  -2.00   Median :1535   Median :1556   Median :  -5.000
 Mean   :  12.64   Mean   :1502   Mean   :1536   Mean   :   6.895
 3rd Qu.:  11.00   3rd Qu.:1940   3rd Qu.:1945   3rd Qu.:  14.000
 Max.   :1301.00   Max.   :2400   Max.   :2359   Max.   :1272.000
 NA's   :8255      NA's   :8713                  NA's   :9430
    carrier          flight       tailnum             origin
 UA     :58665   Min.   :   1   Length:336776      Length:336776
 B6     :54635   1st Qu.: 553   Class :character   Class :character
 EV     :54173   Median :1496   Mode  :character   Mode  :character
 DL     :48110   Mean   :1972
 AA     :32729   3rd Qu.:3465
 MQ     :26397   Max.   :8500
 (Other):62067
     dest              air_time        distance         hour
 Length:336776      Min.   : 20.0   Min.   :  17   Min.   : 1.00
 Class :character   1st Qu.: 82.0   1st Qu.: 502   1st Qu.: 9.00
 Mode  :character   Median :129.0   Median : 872   Median :13.00
                    Mean   :150.7   Mean   :1040   Mean   :13.18
                    3rd Qu.:192.0   3rd Qu.:1389   3rd Qu.:17.00
                    Max.   :695.0   Max.   :4983   Max.   :23.00
                    NA's   :9430
     minute       time_hour
 Min.   : 0.00   Length:336776
 1st Qu.: 8.00   Class :character
 Median :29.00   Mode  :character
 Mean   :26.23
 3rd Qu.:44.00
 Max.   :59.00

In [21]:
head(vuelos)

  year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     1   517      515             2         830      819
2 2013 1     1   533      529             4         850      830
3 2013 1     1   542      540             2         923      850
4 2013 1     1   544      545            -1        1004     1022
5 2013 1     1   554      600            -6         812      837
6 2013 1     1   554      558            -4         740      728
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  11       UA      1545   N14228  EWR    IAH  227      1400     5    15
2  20       UA      1714   N24211  LGA    IAH  227      1416     5    29
3  33       AA      1141   N619AA  JFK    MIA  160      1089     5    40
4 -18       B6       725   N804JB  JFK    BQN  183      1576     5    45
5 -25       DL       461   N668DN  LGA    ATL  116       762     6     0
6  12       UA      1696   N39463  EWR    ORD  150       719     5    58
  time_hour
1 2013-01-01 05:00:00
2 2013-01-01 05:00:00
3 2013-01-01 05:00:00
4 2013-01-01 05:00:00
5 2013-01-01 06:00:00
6 2013-01-01 05:00:00

In [22]:
vuelos$carrier <- as.character(vuelos$carrier)

In [23]:
summary(vuelos)

      year          month             day           dep_time    sched_dep_time
 Min.   :2013   Min.   : 1.000   Min.   : 1.00   Min.   :   1   Min.   : 106
 1st Qu.:2013   1st Qu.: 4.000   1st Qu.: 8.00   1st Qu.: 907   1st Qu.: 906
 Median :2013   Median : 7.000   Median :16.00   Median :1401   Median :1359
 Mean   :2013   Mean   : 6.549   Mean   :15.71   Mean   :1349   Mean   :1344
 3rd Qu.:2013   3rd Qu.:10.000   3rd Qu.:23.00   3rd Qu.:1744   3rd Qu.:1729
 Max.   :2013   Max.   :12.000   Max.   :31.00   Max.   :2400   Max.   :2359
                                                 NA's   :8255
   dep_delay          arr_time    sched_arr_time   arr_delay
 Min.   : -43.00   Min.   :   1   Min.   :   1   Min.   : -86.000
 1st Qu.:  -5.00   1st Qu.:1104   1st Qu.:1124   1st Qu.: -17.000
 Median :  -2.00   Median :1535   Median :1556   Median :  -5.000
 Mean   :  12.64   Mean   :1502   Mean   :1536   Mean   :   6.895
 3rd Qu.:  11.00   3rd Qu.:1940   3rd Qu.:1945   3rd Qu.:  14.000
 Max.   :1301.00   Max.   :2400   Max.   :2359   Max.   :1272.000
 NA's   :8255      NA's   :8713                  NA's   :9430
   carrier              flight       tailnum             origin
 Length:336776      Min.   :   1   Length:336776      Length:336776
 Class :character   1st Qu.: 553   Class :character   Class :character
 Mode  :character   Median :1496   Mode  :character   Mode  :character
                    Mean   :1972
                    3rd Qu.:3465
                    Max.   :8500

     dest              air_time        distance         hour
 Length:336776      Min.   : 20.0   Min.   :  17   Min.   : 1.00
 Class :character   1st Qu.: 82.0   1st Qu.: 502   1st Qu.: 9.00
 Mode  :character   Median :129.0   Median : 872   Median :13.00
                    Mean   :150.7   Mean   :1040   Mean   :13.18
                    3rd Qu.:192.0   3rd Qu.:1389   3rd Qu.:17.00
                    Max.   :695.0   Max.   :4983   Max.   :23.00
                    NA's   :9430
     minute       time_hour
 Min.   : 0.00   Length:336776
 1st Qu.: 8.00   Class :character
 Median :29.00   Mode  :character
 Mean   :26.23
 3rd Qu.:44.00
 Max.   :59.00

In [24]:
#glimpse() o str()
glimpse(vuelos)

Rows: 336,776
Columns: 19
$ year           <int> 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2…
$ month          <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ day            <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ dep_time       <int> 517, 533, 542, 544, 554, 554, 555, 557, 557, 558, 558, …
$ sched_dep_time <int> 515, 529, 540, 545, 600, 558, 600, 600, 600, 600, 600, …
$ dep_delay      <int> 2, 4, 2, -1, -6, -4, -5, -3, -3, -2, -2, -2, -2, -2, -1…
$ arr_time       <int> 830, 850, 923, 1004, 812, 740, 913, 709, 838, 753, 849,…
$ sched_arr_time <int> 819, 830, 850, 1022, 837, 728, 854, 723, 846, 745, 851,…
$ arr_delay      <int> 11, 20, 33, -18, -25, 12, 19, -14, -8, 8, -2, -3, 7, -1…
$ carrier        <chr> "UA", "UA", "AA", "B6", "DL", "UA", "B6", "EV", "B6", "…
$ flight         <int> 1545, 1714, 1141, 725, 461, 1696, 507, 5708, 79, 301, 4…
$ tailnum        <chr> "N14228", "N24211", "N619AA", "N804JB", "N668DN", "N394…
$ origin         <chr> "EWR", "LGA", "JFK", "JFK", "LGA", "EWR", "EWR", "LGA",…
$ dest           <chr> "IAH", "IAH", "MIA", "BQN", "ATL", "ORD", "FLL", "IAD",…
$ air_time       <int> 227, 227, 160, 183, 116, 150, 158, 53, 140, 138, 149, 1…
$ distance       <int> 1400, 1416, 1089, 1576, 762, 719, 1065, 229, 944, 733, …
$ hour           <int> 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6…
$ minute         <int> 15, 29, 40, 45, 0, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 59, 0…
$ time_hour      <chr> "2013-01-01 05:00:00", "2013-01-01 05:00:00", "2013-01-…

## 4. Funciones básicas de dplyr

A continuación exploraremos los datos de vuelos utilizando la librería dplyr.

### 4.1 Función filter()

La función filter() de dplyr es el equivalente a la sentencia where de sql.

In [27]:
# filter() # where de sql----------------------------------------------------------------
# Registros que tengan fecha 31 de diciembre
# Antes
vuelos[(vuelos$month == 12) & (vuelos$day == 31), ] #776 registros (vuelos) el 31 de diciembre

       year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
110521 2013 12    31   13      2359            14        439      437
110522 2013 12    31   18      2359            19        449      444
110523 2013 12    31   26      2245           101        129     2353
110524 2013 12    31  459       500            -1        655      651
110525 2013 12    31  514       515            -1        814      812
110526 2013 12    31  549       551            -2        925      900
110527 2013 12    31  550       600           -10        725      745
110528 2013 12    31  552       600            -8        811      826
110529 2013 12    31  553       600            -7        741      754
110530 2013 12    31  554       550             4       1024     1027
110531 2013 12    31  555       600            -5        901      849
110532 2013 12    31  555       600            -5        835      831
110533 2013 12    31  555       551             4        853      851
110534 2013 12    31  556       600            -4        909      846
110535 2013 12    31  556       605            -9        808      814
110536 2013 12    31  557       603            -6        719      719
110537 2013 12    31  558       600            -2        919      905
110538 2013 12    31  559       600            -1        917      855
110539 2013 12    31  600       540            20        928      850
110540 2013 12    31  602       605            -3        744      805
110541 2013 12    31  602       605            -3        708      723
110542 2013 12    31  603       611            -8       1045     1055
110543 2013 12    31  607       600             7        848      825
110544 2013 12    31  608       615            -7        812      818
110545 2013 12    31  609       610            -1        911      915
110546 2013 12    31  609       615            -6        848      850
110547 2013 12    31  609       614            -5        755      751
110548 2013 12    31  610       615            -5        828      849
110549 2013 12    31  616       611             5        933      912
110550 2013 12    31  616       630           -14        922      919
⋮      ⋮    ⋮     ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
111267 2013 12    31  2155     2039            76        253     2355
111268 2013 12    31  2155     2150             5        110       51
111269 2013 12    31  2159     2155             4         55       46
111270 2013 12    31  2206     2110            56         44     2339
111271 2013 12    31  2211     2159            12        100       45
111272 2013 12    31  2218     2219            -1        315      304
111273 2013 12    31  2235     2245           -10       2351     2355
111274 2013 12    31  2245     2250            -5       2359     2356
111275 2013 12    31  2310     2255            15          7     2356
111276 2013 12    31  2321     2250            31         46        8
111277 2013 12    31  2328     2330            -2        412      409
111278 2013 12    31  2332     2245            47         58        3
111279 2013 12    31  2355     2359            -4        430      440
111280 2013 12    31  2356     2359            -3        436      445
111281 2013 12    31    NA     1520            NA         NA     1705
111282 2013 12    31    NA     2025            NA         NA     2205
111283 2013 12    31    NA     1932            NA         NA     2305
111284 2013 12    31    NA     1505            NA         NA     1725
111285 2013 12    31    NA     1000            NA         NA     1252
111286 2013 12    31    NA      840            NA         NA     1205
111287 2013 12    31    NA      754            NA         NA     1118
111288 2013 12    31    NA     2000            NA         NA     2146
111289 2013 12    31    NA     1500            NA         NA     1817
111290 2013 12    31    NA     1430            NA         NA     1750
111291 2013 12    31    NA      855            NA         NA     1142
111292 2013 12    31    NA      705            NA         NA      931
111293 2013 12    31    NA      825            NA         NA     1029
111294 2013 12    31    NA     1615            NA         NA     1800
111295 2013 12    31    NA      600            NA         NA      735
111296 2013 12    31    NA      830            NA         NA     1154
       arr_delay carrier flight tailnum origin dest air_time distance hour
110521   2       B6       839   N566JB  JFK    BQN  189      1576     23
110522   5       DL       412   N713TW  JFK    SJU  192      1598     23
110523  96       B6       108   N374JB  JFK    PWM   50       273     22
110524   4       US      1895   N557UW  EWR    CLT   95       529      5
110525   2       UA       700   N470UA  EWR    IAH  223      1400      5
110526  25       UA       274   N577UA  EWR    LAX  346      2454      5
110527 -20       AA       301   N3CXAA  LGA    ORD  127       733      6
110528 -15       EV      3825   N14916  EWR    IND  118       645      6
110529 -13       DL       731   N333NB  LGA    DTW   86       502      6
110530  -3       B6       939   N552JB  JFK    BQN  195      1576      5
110531  12       B6       353   N746JB  JFK    PBI  167      1028      6
110532   4       DL       904   N3741S  LGA    ATL  137       762      6
110533   2       UA       566   N491UA  EWR    TPA  164       997      5
110534  23       B6       583   N715JB  JFK    MCO  162       944      6
110535  -6       DL      1919   N958DL  LGA    MSP  160      1020      6
110536   0       EV      4241   N15574  EWR    DCA   45       199      6
110537  14       AA      1175   N3JEAA  LGA    MIA  173      1096      6
110538  22       B6       605   N597JB  EWR    FLL  167      1065      6
110539  38       AA      2243   N5EMAA  JFK    MIA  171      1089      5
110540 -21       DL      2505   N358NB  EWR    DTW   87       488      6
110541 -15       EV      6177   N14543  EWR    IAD   45       212      6
110542 -10       B6      1403   N547JB  JFK    SJU  198      1598      6
110543  23       WN      1716   N7740A  LGA    ATL  137       762      6
110544  -6       US      1963   N192UW  EWR    CLT  106       529      6
110545  -4       AA      1205   N5DHAA  EWR    MIA  163      1085      6
110546  -2       DL       404   N392DA  JFK    ATL  133       760      6
110547   4       EV      3812   N13994  EWR    RDU   81       416      6
110548 -21       DL       479   N3766   JFK    ATL  119       760      6
110549  21       B6       601   N643JB  JFK    FLL  173      1069      6
110550   3       B6      1099   N563JB  LGA    MCO  159       950      6
⋮      ⋮         ⋮       ⋮      ⋮       ⋮      ⋮    ⋮        ⋮        ⋮
111267  NA       B6      1205   N627JB  JFK    PDX   NA      2454     20
111268  19       B6      1901   N729JB  JFK    FLL  164      1069     21
111269   9       B6      2053   N593JB  JFK    PBI  155      1028     21
111270  65       B6       775   N184JB  JFK    MSY  195      1182     21
111271  15       B6      1183   N715JB  JFK    MCO  148       944     21
111272  11       B6      1203   N625JB  JFK    SJU  202      1598     22
111273  -4       B6       234   N355JB  JFK    BTV   49       266     22
111274   3       B6      1816   N318JB  JFK    SYR   51       209     22
111275  11       B6       718   N279JB  JFK    BOS   40       187     22
111276  38       B6      2002   N179JB  JFK    BUF   66       301     22
111277   3       B6      1389   N651JB  EWR    SJU  198      1608     23
111278  55       B6       486   N334JB  JFK    ROC   60       264     22
111279 -10       B6      1503   N509JB  JFK    SJU  195      1598     23
111280  -9       B6       745   N665JB  JFK    PSE  200      1617     23
111281  NA       AA       341   N568AA  LGA    ORD   NA       733     15
111282  NA       AA       371   N482AA  LGA    ORD   NA       733     20
111283  NA       B6       161   N516JB  JFK    SMF   NA      2521     19
111284  NA       EV      4181   N24103  EWR    MCI   NA      1092     15
111285  NA       UA      1124   NA      EWR    EGE   NA      1725     10
111286  NA       UA      1151   NA      EWR    SEA   NA      2402      8
111287  NA       UA      1455   NA      EWR    LAX   NA      2454      7
111288  NA       UA      1482   NA      EWR    ORD   NA       719     20
111289  NA       UA      1483   NA      EWR    AUS   NA      1504     15
111290  NA       UA      1493   NA      EWR    LAX   NA      2454     14
111291  NA       UA      1506   NA      EWR    JAC   NA      1874      8
111292  NA       UA      1729   NA      EWR    DEN   NA      1605      7
111293  NA       US      1831   NA      JFK    CLT   NA       541      8
111294  NA       MQ      3301   N844MQ  LGA    RDU   NA       431     16
111295  NA       UA       219   NA      EWR    ORD   NA       719      6
111296  NA       UA       443   NA      JFK    LAX   NA      2475      8
       minute time_hour
110521 59     2013-12-31 23:00:00
110522 59     2013-12-31 23:00:00
110523 45     2013-12-31 22:00:00
110524  0     2013-12-31 05:00:00
110525 15     2013-12-31 05:00:00
110526 51     2013-12-31 05:00:00
110527  0     2013-12-31 06:00:00
110528  0     2013-12-31 06:00:00
110529  0     2013-12-31 06:00:00
110530 50     2013-12-31 05:00:00
110531  0     2013-12-31 06:00:00
110532  0     2013-12-31 06:00:00
110533 51     2013-12-31 05:00:00
110534  0     2013-12-31 06:00:00
110535  5     2013-12-31 06:00:00
110536  3     2013-12-31 06:00:00
110537  0     2013-12-31 06:00:00
110538  0     2013-12-31 06:00:00
110539 40     2013-12-31 05:00:00
110540  5     2013-12-31 06:00:00
110541  5     2013-12-31 06:00:00
110542 11     2013-12-31 06:00:00
110543  0     2013-12-31 06:00:00
110544 15     2013-12-31 06:00:00
110545 10     2013-12-31 06:00:00
110546 15     2013-12-31 06:00:00
110547 14     2013-12-31 06:00:00
110548 15     2013-12-31 06:00:00
110549 11     2013-12-31 06:00:00
110550 30     2013-12-31 06:00:00
⋮      ⋮      ⋮
111267 39     2013-12-31 20:00:00
111268 50     2013-12-31 21:00:00
111269 55     2013-12-31 21:00:00
111270 10     2013-12-31 21:00:00
111271 59     2013-12-31 21:00:00
111272 19     2013-12-31 22:00:00
111273 45     2013-12-31 22:00:00
111274 50     2013-12-31 22:00:00
111275 55     2013-12-31 22:00:00
111276 50     2013-12-31 22:00:00
111277 30     2013-12-31 23:00:00
111278 45     2013-12-31 22:00:00
111279 59     2013-12-31 23:00:00
111280 59     2013-12-31 23:00:00
111281 20     2013-12-31 15:00:00
111282 25     2013-12-31 20:00:00
111283 32     2013-12-31 19:00:00
111284  5     2013-12-31 15:00:00
111285  0     2013-12-31 10:00:00
111286 40     2013-12-31 08:00:00
111287 54     2013-12-31 07:00:00
111288  0     2013-12-31 20:00:00
111289  0     2013-12-31 15:00:00
111290 30     2013-12-31 14:00:00
111291 55     2013-12-31 08:00:00
111292  5     2013-12-31 07:00:00
111293 25     2013-12-31 08:00:00
111294 15     2013-12-31 16:00:00
111295  0     2013-12-31 06:00:00
111296 30     2013-12-31 08:00:00

In [28]:
# Ahora
filter(vuelos, month == 12 & day == 31)

    year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1   2013 12    31   13      2359            14        439      437
2   2013 12    31   18      2359            19        449      444
3   2013 12    31   26      2245           101        129     2353
4   2013 12    31  459       500            -1        655      651
5   2013 12    31  514       515            -1        814      812
6   2013 12    31  549       551            -2        925      900
7   2013 12    31  550       600           -10        725      745
8   2013 12    31  552       600            -8        811      826
9   2013 12    31  553       600            -7        741      754
10  2013 12    31  554       550             4       1024     1027
11  2013 12    31  555       600            -5        901      849
12  2013 12    31  555       600            -5        835      831
13  2013 12    31  555       551             4        853      851
14  2013 12    31  556       600            -4        909      846
15  2013 12    31  556       605            -9        808      814
16  2013 12    31  557       603            -6        719      719
17  2013 12    31  558       600            -2        919      905
18  2013 12    31  559       600            -1        917      855
19  2013 12    31  600       540            20        928      850
20  2013 12    31  602       605            -3        744      805
21  2013 12    31  602       605            -3        708      723
22  2013 12    31  603       611            -8       1045     1055
23  2013 12    31  607       600             7        848      825
24  2013 12    31  608       615            -7        812      818
25  2013 12    31  609       610            -1        911      915
26  2013 12    31  609       615            -6        848      850
27  2013 12    31  609       614            -5        755      751
28  2013 12    31  610       615            -5        828      849
29  2013 12    31  616       611             5        933      912
30  2013 12    31  616       630           -14        922      919
⋮   ⋮    ⋮     ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
747 2013 12    31  2155     2039            76        253     2355
748 2013 12    31  2155     2150             5        110       51
749 2013 12    31  2159     2155             4         55       46
750 2013 12    31  2206     2110            56         44     2339
751 2013 12    31  2211     2159            12        100       45
752 2013 12    31  2218     2219            -1        315      304
753 2013 12    31  2235     2245           -10       2351     2355
754 2013 12    31  2245     2250            -5       2359     2356
755 2013 12    31  2310     2255            15          7     2356
756 2013 12    31  2321     2250            31         46        8
757 2013 12    31  2328     2330            -2        412      409
758 2013 12    31  2332     2245            47         58        3
759 2013 12    31  2355     2359            -4        430      440
760 2013 12    31  2356     2359            -3        436      445
761 2013 12    31    NA     1520            NA         NA     1705
762 2013 12    31    NA     2025            NA         NA     2205
763 2013 12    31    NA     1932            NA         NA     2305
764 2013 12    31    NA     1505            NA         NA     1725
765 2013 12    31    NA     1000            NA         NA     1252
766 2013 12    31    NA      840            NA         NA     1205
767 2013 12    31    NA      754            NA         NA     1118
768 2013 12    31    NA     2000            NA         NA     2146
769 2013 12    31    NA     1500            NA         NA     1817
770 2013 12    31    NA     1430            NA         NA     1750
771 2013 12    31    NA      855            NA         NA     1142
772 2013 12    31    NA      705            NA         NA      931
773 2013 12    31    NA      825            NA         NA     1029
774 2013 12    31    NA     1615            NA         NA     1800
775 2013 12    31    NA      600            NA         NA      735
776 2013 12    31    NA      830            NA         NA     1154
    arr_delay carrier flight tailnum origin dest air_time distance hour minute
1     2       B6       839   N566JB  JFK    BQN  189      1576     23   59
2     5       DL       412   N713TW  JFK    SJU  192      1598     23   59
3    96       B6       108   N374JB  JFK    PWM   50       273     22   45
4     4       US      1895   N557UW  EWR    CLT   95       529      5    0
5     2       UA       700   N470UA  EWR    IAH  223      1400      5   15
6    25       UA       274   N577UA  EWR    LAX  346      2454      5   51
7   -20       AA       301   N3CXAA  LGA    ORD  127       733      6    0
8   -15       EV      3825   N14916  EWR    IND  118       645      6    0
9   -13       DL       731   N333NB  LGA    DTW   86       502      6    0
10   -3       B6       939   N552JB  JFK    BQN  195      1576      5   50
11   12       B6       353   N746JB  JFK    PBI  167      1028      6    0
12    4       DL       904   N3741S  LGA    ATL  137       762      6    0
13    2       UA       566   N491UA  EWR    TPA  164       997      5   51
14   23       B6       583   N715JB  JFK    MCO  162       944      6    0
15   -6       DL      1919   N958DL  LGA    MSP  160      1020      6    5
16    0       EV      4241   N15574  EWR    DCA   45       199      6    3
17   14       AA      1175   N3JEAA  LGA    MIA  173      1096      6    0
18   22       B6       605   N597JB  EWR    FLL  167      1065      6    0
19   38       AA      2243   N5EMAA  JFK    MIA  171      1089      5   40
20  -21       DL      2505   N358NB  EWR    DTW   87       488      6    5
21  -15       EV      6177   N14543  EWR    IAD   45       212      6    5
22  -10       B6      1403   N547JB  JFK    SJU  198      1598      6   11
23   23       WN      1716   N7740A  LGA    ATL  137       762      6    0
24   -6       US      1963   N192UW  EWR    CLT  106       529      6   15
25   -4       AA      1205   N5DHAA  EWR    MIA  163      1085      6   10
26   -2       DL       404   N392DA  JFK    ATL  133       760      6   15
27    4       EV      3812   N13994  EWR    RDU   81       416      6   14
28  -21       DL       479   N3766   JFK    ATL  119       760      6   15
29   21       B6       601   N643JB  JFK    FLL  173      1069      6   11
30    3       B6      1099   N563JB  LGA    MCO  159       950      6   30
⋮   ⋮         ⋮       ⋮      ⋮       ⋮      ⋮    ⋮        ⋮        ⋮    ⋮
747  NA       B6      1205   N627JB  JFK    PDX   NA      2454     20   39
748  19       B6      1901   N729JB  JFK    FLL  164      1069     21   50
749   9       B6      2053   N593JB  JFK    PBI  155      1028     21   55
750  65       B6       775   N184JB  JFK    MSY  195      1182     21   10
751  15       B6      1183   N715JB  JFK    MCO  148       944     21   59
752  11       B6      1203   N625JB  JFK    SJU  202      1598     22   19
753  -4       B6       234   N355JB  JFK    BTV   49       266     22   45
754   3       B6      1816   N318JB  JFK    SYR   51       209     22   50
755  11       B6       718   N279JB  JFK    BOS   40       187     22   55
756  38       B6      2002   N179JB  JFK    BUF   66       301     22   50
757   3       B6      1389   N651JB  EWR    SJU  198      1608     23   30
758  55       B6       486   N334JB  JFK    ROC   60       264     22   45
759 -10       B6      1503   N509JB  JFK    SJU  195      1598     23   59
760  -9       B6       745   N665JB  JFK    PSE  200      1617     23   59
761  NA       AA       341   N568AA  LGA    ORD   NA       733     15   20
762  NA       AA       371   N482AA  LGA    ORD   NA       733     20   25
763  NA       B6       161   N516JB  JFK    SMF   NA      2521     19   32
764  NA       EV      4181   N24103  EWR    MCI   NA      1092     15    5
765  NA       UA      1124   NA      EWR    EGE   NA      1725     10    0
766  NA       UA      1151   NA      EWR    SEA   NA      2402      8   40
767  NA       UA      1455   NA      EWR    LAX   NA      2454      7   54
768  NA       UA      1482   NA      EWR    ORD   NA       719     20    0
769  NA       UA      1483   NA      EWR    AUS   NA      1504     15    0
770  NA       UA      1493   NA      EWR    LAX   NA      2454     14   30
771  NA       UA      1506   NA      EWR    JAC   NA      1874      8   55
772  NA       UA      1729   NA      EWR    DEN   NA      1605      7    5
773  NA       US      1831   NA      JFK    CLT   NA       541      8   25
774  NA       MQ      3301   N844MQ  LGA    RDU   NA       431     16   15
775  NA       UA       219   NA      EWR    ORD   NA       719      6    0
776  NA       UA       443   NA      JFK    LAX   NA      2475      8   30
    time_hour
1   2013-12-31 23:00:00
2   2013-12-31 23:00:00
3   2013-12-31 22:00:00
4   2013-12-31 05:00:00
5   2013-12-31 05:00:00
6   2013-12-31 05:00:00
7   2013-12-31 06:00:00
8   2013-12-31 06:00:00
9   2013-12-31 06:00:00
10  2013-12-31 05:00:00
11  2013-12-31 06:00:00
12  2013-12-31 06:00:00
13  2013-12-31 05:00:00
14  2013-12-31 06:00:00
15  2013-12-31 06:00:00
16  2013-12-31 06:00:00
17  2013-12-31 06:00:00
18  2013-12-31 06:00:00
19  2013-12-31 05:00:00
20  2013-12-31 06:00:00
21  2013-12-31 06:00:00
22  2013-12-31 06:00:00
23  2013-12-31 06:00:00
24  2013-12-31 06:00:00
25  2013-12-31 06:00:00
26  2013-12-31 06:00:00
27  2013-12-31 06:00:00
28  2013-12-31 06:00:00
29  2013-12-31 06:00:00
30  2013-12-31 06:00:00
⋮   ⋮
747 2013-12-31 20:00:00
748 2013-12-31 21:00:00
749 2013-12-31 21:00:00
750 2013-12-31 21:00:00
751 2013-12-31 21:00:00
752 2013-12-31 22:00:00
753 2013-12-31 22:00:00
754 2013-12-31 22:00:00
755 2013-12-31 22:00:00
756 2013-12-31 22:00:00
757 2013-12-31 23:00:00
758 2013-12-31 22:00:00
759 2013-12-31 23:00:00
760 2013-12-31 23:00:00
761 2013-12-31 15:00:00
762 2013-12-31 20:00:00
763 2013-12-31 19:00:00
764 2013-12-31 15:00:00
765 2013-12-31 10:00:00
766 2013-12-31 08:00:00
767 2013-12-31 07:00:00
768 2013-12-31 20:00:00
769 2013-12-31 15:00:00
770 2013-12-31 14:00:00
771 2013-12-31 08:00:00
772 2013-12-31 07:00:00
773 2013-12-31 08:00:00
774 2013-12-31 16:00:00
775 2013-12-31 06:00:00
776 2013-12-31 08:00:00

### 4.2 Función count()

Como su nombre lo indica, esta función nos permite contar registros de una tabla. Es de suma utilidad cuando se utiliza dentro de agrupaciones de tablas. Estas últimas las veremos más adelante.

Alternativamente, en la librería _dplyr_, contamos con la función `N()` la cual también retorna el conteo de registros.

In [29]:
# Ej. Cuántos vuelos hay por aeropuerto de origen
count(vuelos, origin)

  origin n
1 EWR    120835
2 JFK    111279
3 LGA    104662

In [30]:
# Total de vuelos por (año) mes y día
count(vuelos, year, month, day)

    year month day n
1   2013 1      1  842
2   2013 1      2  943
3   2013 1      3  914
4   2013 1      4  915
5   2013 1      5  720
6   2013 1      6  832
7   2013 1      7  933
8   2013 1      8  899
9   2013 1      9  902
10  2013 1     10  932
11  2013 1     11  930
12  2013 1     12  690
13  2013 1     13  828
14  2013 1     14  928
15  2013 1     15  894
16  2013 1     16  901
17  2013 1     17  927
18  2013 1     18  924
19  2013 1     19  674
20  2013 1     20  786
21  2013 1     21  912
22  2013 1     22  890
23  2013 1     23  897
24  2013 1     24  925
25  2013 1     25  922
26  2013 1     26  680
27  2013 1     27  823
28  2013 1     28  923
29  2013 1     29  890
30  2013 1     30  900
⋮   ⋮    ⋮     ⋮   ⋮
336 2013 12     2  1004
337 2013 12     3   973
338 2013 12     4   958
339 2013 12     5   969
340 2013 12     6   970
341 2013 12     7   691
342 2013 12     8   875
343 2013 12     9   962
344 2013 12    10   943
345 2013 12    11   954
346 2013 12    12   968
347 2013 12    13   970
348 2013 12    14   692
349 2013 12    15   880
350 2013 12    16   964
351 2013 12    17   949
352 2013 12    18   956
353 2013 12    19   974
354 2013 12    20   980
355 2013 12    21   811
356 2013 12    22   895
357 2013 12    23   985
358 2013 12    24   761
359 2013 12    25   719
360 2013 12    26   936
361 2013 12    27   963
362 2013 12    28   814
363 2013 12    29   888
364 2013 12    30   968
365 2013 12    31   776

In [32]:
# count() y N() ----------------------------------------------------------------
# ¿Cuántos vuelos hay registrados para el 25 de dic?¿y el primero de enero?
filter(count(vuelos, year, month, day), (day == 25 & month == 12) | (day == 1 & month == 1) )
# El 25 de dic, se registraron 719 vuelos y 842 el 1 de enero.-

  year month day n
1 2013  1     1  842
2 2013 12    25  719

In [36]:
#si quisiéramos guardar resgidtros en el disco, una manera es usando write.csv()
resumen_diario <- count(vuelos, year, month, day)
write.csv(resumen_diario, file = "vuelos_diarios.csv", row.names = F)

In [ ]:
# ¿Cuántos vuelos hay registrados entre noviembre y diciembre?¿A qué porcentaje del total corresponde?

In [ ]:
# ¿Qué porcentaje de vuelos tienen un retraso  (de salida o llegada) mayor a una hora?

#columnas arr_delay o dep_delay

In [ ]:
# ¿Cuántos vuelos llegaron con al menos dos horas de retraso pero no se retrasaron al partir?

### 4.3 Función arrange()

Esta función nos permite ordernar registros basándose en la indexación de alguna columna. Es el equivalente a la sentencia `order by` en sql.
Esta función recibe como argumento principal un dataset a ordenar, y los nombres de las columnas por las cuales se quiere ordenar. Para más información consultar la ayuda de esta función (?arrange)

In [ ]:
# arrange() ----------------------------------------------------------------
# Ejemplo, podemos ordenar la data flights por mes y arr_delay

### 4.3 Funciones select() y rename()

La con la función `select` podemos seleccionar un subconjunto de columas de la tabla original. A difernecia de SQL en esta sentencia no podremos crear nuevas columnas, sólo renombrarlas en algunos casos. Notar que (obviamente) no se mantienen las columnas que no ingresan como argumento a la función.

La función rename() permite renombrar columnas existentes, manteniendo las columnas que no se están renombrando.

In [ ]:
# select() y rename() ----------------------------------------------------------------
# Ejemplo: Podemos seleccionar las columnas year, month, day, origin, dest

# Cómo lo haríamos con la sintaxis básica? (recorr como acceder a través del nombre a un vector, matrix, lista, o data.frame)

In [ ]:
# podemos renombrar la columna year
)

# NOTA: esto no modifica el dataset original

In [ ]:
#Existe gran variedad (pueden consultar la documentación respectiva)  de otras funciones dentro del package dplyr, por ejemplo: Seleccionar solo las variables que comiencen con "d"
# para su estudio

### 4.4 Función mutate()

Una de las funciones más útiles de dplyr es la función mutate(), la cual permite crear nuevas columnas, o modificar las existentes.

In [ ]:
# mutate() ----------------------------------------------------------------
# Crear una nueva columna llamada retraso_neto, que contenga la suma de arr_delay y dep_delay

#antes

#ahora

# Recordar que esta nueva columna solo existe en la ejecución y no se ha modificado el dataset original.

In [ ]:
# Primero defina una nueva data llamada muestra_fl que contenga la fecha, los retrasos, la distancia, y el tiempo de vuelo
# Cree una columna llamada gain que contenga la diferenecia entre arr_delay y dep_delay, y otra llamada speed que mida la velocidad en horas (distancia / tiempo de vuelo * 60)

### Operador %>%

El operador estrella de dplyr. Funciona como una composición de funciones, y nos permite generar _pipe-lines_, permitiendo  que la generación  del código sea más ordenada, y con ello, su lectura más sencilla.

Este operdaor actua de la sifuiente manera, <br>

    x %>% f(y) , es equivalente a,  f(x,y)

In [ ]:
# Operador %>% ----------------------------------------------------------------
# Ejemplo sencillo

# head(vuelos)


# Utilizando %>%

In [ ]:
# Genere el conteo de vuelos por mes y día,
# luego filtre por aquellos registros donde el día es 1,
# ordene de manera descendiente por n,
# finalmente muestra la cabecera del dataset resultante.

## ANTES

In [ ]:
# Genere el conteo de vuelos por mes y día,
# luego filtre por aquellos registros donde el día es 1,
# ordene de manera descendiente por n,
# finalmente muestra la cabecera del dataset resultante.

## AHORA

In [ ]:
# A la onsulta anterior podríamos agregar una nueva columna indicando si el totalde vuelos es mayor a 970

In [ ]:
# Genere una nueva variable llamada day2 que pegue un "0"
# a la variable day si es que esta contiene un dígito del 1 al 9.
# Para pegar cadena de caracteres sin espacios puede utilizar
# la función paste0

#?paste0, ?nchar

In [ ]:
# Con esta variable genere un entero llamado fecha, que concatena year,month y day 2.

### 4.5 Función group_by() y summarise()

La función `summarise()` calcula medidas agregadas sobre columnas, mientras que la función `group_by`, genera un data.frame "en bloques" dados por la(s) columna(s) ingresadas como parámetros en la función.

In [ ]:
# group_by() y summarise() ----------------------------------------------------------------
# Ejemplo sencillo
exam2 <- data.frame(
  x = c(1:5),
  y = c(7:11),
  z = c("A", "B", "A", "B", "C")
)
exam2

In [ ]:
# Podemos generar un número de fila por cada grupo

In [ ]:
# 1) Aplicar la función summarise a la columna 'y' y calcular su promedio


# 2) Generar grupos según la variable z. (a diferencia de sql, el comando group_by() no requiere de una medida agregada para que este funcione.)
# select z, avg(x) mean_x, sum(x) tot_x from exam2 group by z

In [ ]:
# 3) Calcular media de x e y en cada valor de z.
# podemos calcular máximos y mínimos

In [ ]:
# promedio de retraso de llegada por origen-destino

In [ ]:
# ¿Cuáles son los aeropuertos de destino con mayor retraso medio en su llegada?

In [ ]:
# los podemos remover mediante el argumento na.rm de la función mean()

In [ ]:
# si quisiéramos ratar los NA's, podemos hacerlo de la sgte. manera

#consultamos los NA en arr_delay

# Recordar que NA == NA retorna NA . is.na(NA) retorna TRUE

In [ ]:
# Si queremos reemplazar los NA's por el promedio de arr_delay (?)

In [ ]:
# ¿Cuál es el promedio de arr_delay y distance por cada aeropuerto de destino?¿Cuántos vuelos llegaron acada uno de los destinos?. Ayuda: Recuerde que el conteo se puede determinar de dos maneras: con la función count() o con la función n().

)

### 4.6 Función sample_n() y sample_frac()

Estas funciones nos permitirán extraer muestras aleatorias de nuestros conjuntos de datos. Esto será de suma importancia cuando trabajemos con modelos de ML.

In [ ]:
# sample_n() y sample_frac()-------------------------------------------------------------

# muestra aleatoria de 100 registros de vuelos