<a href="https://colab.research.google.com/github/majorquev/DBDC_202604_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/Clase2/Clase_2_01_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com



### 3.2 Matrices

En R, así como en otros lenguajes de programación, una matriz es básicamente un arreglo bi-dimensional, donde las entradas horizontales se entienden como filas y las verticales como columnas. Es posible imaginar una matriz como un arreglo de vectores como columnas (o filas) del mismo largo.

 * ¿Qué se guarda en una matriz?<br>
    Sólo datos de un mismo tipo.
     
 * ¿Cómo se declara una matriz?<br>
    Se puede definir de varias maneras, indicando los elementos que la componen, o combinando vectores como filas o columnas.

 * ¿Cómo se accede a sus elementos?<br>
    Indicando la posición del vector fila, seguido de la posición del vector columna (como es usual).

In [1]:
# 3.2 Matrices ------------
#?matrix de dos filas y 3 columnas, parametros ncol, nrow y byrow
# recibe un vector de elementos
A <- matrix(c(1,1,2,3,5,8), ncol = 3, nrow = 2)
A

     [,1] [,2] [,3]
[1,] 1    2    5
[2,] 1    3    8

In [2]:
B <- matrix(c(1,1,2,3,5,8), ncol = 3, nrow = 2, byrow = T)
B

     [,1] [,2] [,3]
[1,] 1    1    2
[2,] 3    5    8

In [3]:
# clase y atributo dim
class(A)

[1] "matrix" "array"

In [4]:
# Genere dos vectores del mismo largo y forme una matriz.
v1 <- c(1,1,2,3)
v2 <- c(10,20,30,40)

In [7]:
# funciones cbind() [une vectores como columnas]
# y rbind() [une vectores como filas] (pensadas para matrices)
#?cbind
C <- cbind(v1,v2)
D <- rbind(v1,v2)

In [9]:
C
D

     v1 v2
[1,] 1  10
[2,] 1  20
[3,] 2  30
[4,] 3  40

   [,1] [,2] [,3] [,4]
v1  1    1    2    3
v2 10   20   30   40

In [10]:
# NOTA: Podemos añadir una fila/columna a una matriz existente
v3 <- c(-1,-2,-3,-4)

In [12]:
cbind(C,v3)
rbind(D,v3)

     v1 v2 v3
[1,] 1  10 -1
[2,] 1  20 -2
[3,] 2  30 -3
[4,] 3  40 -4

   [,1] [,2] [,3] [,4]
v1  1    1    2    3
v2 10   20   30   40
v3 -1   -2   -3   -4

In [13]:
D

   [,1] [,2] [,3] [,4]
v1  1    1    2    3
v2 10   20   30   40

In [14]:
# si combinamos vectores de distinto largo?
# R recicla valores (recordar explicación)
v4 <- c(-1,-2,-3)
rbind(D,v4)

Warning message in rbind(D, v4):
“number of columns of result is not a multiple of vector length (arg 2)”

   [,1] [,2] [,3] [,4]
v1  1    1    2    3
v2 10   20   30   40
v4 -1   -2   -3   -1

In [15]:
# función diag para la definición de matrices diagonales
#?diag
diag(c(1,1,4,6))

     [,1] [,2] [,3] [,4]
[1,] 1    0    0    0
[2,] 0    1    0    0
[3,] 0    0    4    0
[4,] 0    0    0    6

In [17]:
# Podemos acceder a los elementos de una matriz
# indicando la posición de la fila y la columna de la casilla correspondiente.
# Ejemplo: Rescatar el elemtno de posición 2,3 de la matriz D.
D
D[2,3]

   [,1] [,2] [,3] [,4]
v1  1    1    2    3
v2 10   20   30   40

v2
30

In [18]:
# CUIDADO:No es lo mismo que
D[c(2,3)] # No lo hagan!!

[1] 10  1

In [21]:
C

     v1 v2
[1,] 1  10
[2,] 1  20
[3,] 2  30
[4,] 3  40

In [22]:
# Para acceder a una fila completa
C[3,]

# Para acceder a una columna completa
C[,2]

v1 v2
 2 30

[1] 10 20 30 40

In [23]:
C

     v1 v2
[1,] 1  10
[2,] 1  20
[3,] 2  30
[4,] 3  40

In [25]:
#Recordemos que podemos actualizar elementos de un vector como:

# quiero cambiar el 40 por un -99 (el 40 de la pos 4,2)

C[4,2] <- -99

In [26]:
C

     v1 v2
[1,] 1   10
[2,] 1   20
[3,] 2   30
[4,] 3  -99

In [29]:
#Nombres de columnas y filas en una matriz
colnames(C)
rownames(C)

[1] "v1" "v2"

NULL

In [30]:
rownames(C) <- c("f1","f2","f3","f4")

In [31]:
C

   v1 v2
f1 1   10
f2 1   20
f3 2   30
f4 3  -99

In [ ]:
# Acceso mediante nombres
C

In [33]:
# Acceso mediante nomnbres
# Elemento de la tercera fila y segunda columna (3,2) de la matrix C

C["f3","v2"]
C[3,2]

[1] 30

[1] 30

In [35]:
C["f3",]# Tercera fila completa
C[,"v2"]# Segunda columna completa

v1 v2
 2 30

 f1  f2  f3  f4
 10  20  30 -99

In [37]:
# Acceso mediante "indicatrices" lógicas
#Quiero obtener los elementos (2,2) y (3,2) de C
# 1: Crear una matriz de 4x2 con TRUE en dichas posiciones y FALSE en las restantes.
ind <- matrix(c(F,F,F,F,F,T,T,F), ncol = 2, nrow = 4, byrow = F)

In [38]:
ind

     [,1]  [,2]
[1,] FALSE FALSE
[2,] FALSE  TRUE
[3,] FALSE  TRUE
[4,] FALSE FALSE

In [36]:
C

   v1 v2
f1 1   10
f2 1   20
f3 2   30
f4 3  -99

In [39]:
C[ind]

[1] 20 30

In [42]:
# Podemos evaluar las casillas de una matriz mediante sentencias lógicas
C[C <=2 ]

[1]   1   1   2 -99

**Álgebra de matrices**

Las operaciones suma (resta) y ponderación por escalar se llevan cabo mediante los mismos operadores utilizados para valores numéricos y vectores (+,-,*, /). Para multiplicar matrices en cambio, se utiliza el operador %*%, mientras que para invertirlas se utiliza la función solve(), t() para transponer y det() para el cálculo del determinante en el caso de matrices cuadradas.

In [ ]:
# transponer una matriz

In [ ]:
# 3.2 Álgbra de matrices  ------------
# Ejemplo simple de álgebra de matrices

In [ ]:
# Multiplicación de matrices
M2 * M1 # multiplicación componente a componente

In [ ]:
# podemos calcular determinantes
# ?det

In [ ]:
# Podemos invertir matrices
# ?solve