<a href="https://colab.research.google.com/github/majorquev/DBDC_202604_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/Clase2/Clase_2_02_listas_y_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com


## 5. Listas y Dataframes

### 5.1 Listas

Hasta aquí contamos con dos tipos de objetos para almacenar datos; vectores y matrices. Sin embargo, en ambos casos se tiene la limitante de que no es posible combinar distintos tipos de datos en diferentes entradas. Un objeto que permite una mayor flexibilidad son las listas. En R, una lista es básicamente un arreglo unidimensional, donde en cada entrada es posible almacenar distintos **objetos** (los cuales a su vez pueden almacenar distintos tipos de datos (u otros objetos).
En resumen,

   * ¿Qué son?<br>
    Arreglos unidimensionales que guardan distintos tipos de datos u objetos.<br>

   * ¿Cómo se declaran?<br>
    Se pueden declarar mediante el comando list() o combinando listas existentes. <br>
    
   * ¿Cómo se accede a sus elementos?<br>
    Usando [ ] (retorna lista), o bien usando [ [ ] ] (retorna el objeto).
    En cada caso se puede indicar la posición o nombre del objeto que se quiere rescatar.<br>
    Otra manera es mediante el símbolo $ seguido del nombre del objeto.

In [1]:
LETTERS

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [7]:
# 5. Listas y dataframes ------------
# 5.1 Listas  ------------
# Cómo declarar una lista (comando list() )
#num,letra, pl, mat, lista
l1 <- list(num = 1:10,
           letra = "Hola team",
           pl = c("A", "B", "C"),
           mat = matrix(c(3,5,7,11), nrow = 2, ncol = 2),
           lista = list(e1 = 3.4,
                        e2 = LETTERS))
l2 <- list(c(1,3), "Otra frase")

In [3]:
# estructura
l1

$num
 [1]  1  2  3  4  5  6  7  8  9 10

$letra
[1] "Hola team"

$pl
[1] "A" "B" "C"

$mat
     [,1] [,2]
[1,]    3    7
[2,]    5   11

$lista
$lista$e1
[1] 3.4

$lista$e2
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [15]:
# class()
class(l1)

[1] "list"

In [4]:
str(l1)

List of 5
 $ num  : int [1:10] 1 2 3 4 5 6 7 8 9 10
 $ letra: chr "Hola team"
 $ pl   : chr [1:3] "A" "B" "C"
 $ mat  : num [1:2, 1:2] 3 5 7 11
 $ lista:List of 2
  ..$ e1: num 3.4
  ..$ e2: chr [1:26] "A" "B" "C" "D" ...

In [5]:
length(l1)

[1] 5

In [6]:
names(l1)

[1] "num"   "letra" "pl"    "mat"   "lista"

In [8]:
l2

[[1]]
[1] 1 3

[[2]]
[1] "Otra frase"

In [9]:
length(l2)
names(l2)

[1] 2

NULL

In [11]:
# Podemos combinar listas
l3 <- c(l1,l2)
l3

$num
 [1]  1  2  3  4  5  6  7  8  9 10

$letra
[1] "Hola team"

$pl
[1] "A" "B" "C"

$mat
     [,1] [,2]
[1,]    3    7
[2,]    5   11

$lista
$lista$e1
[1] 3.4

$lista$e2
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"


[[6]]
[1] 1 3

[[7]]
[1] "Otra frase"

In [13]:
l1

$num
 [1]  1  2  3  4  5  6  7  8  9 10

$letra
[1] "Hola team"

$pl
[1] "A" "B" "C"

$mat
     [,1] [,2]
[1,]    3    7
[2,]    5   11

$lista
$lista$e1
[1] 3.4

$lista$e2
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [16]:
# Acceso mediante posición
l1[3] # Retorna una lista con el vector
class(l1[3]) # Es una lista!

$pl
[1] "A" "B" "C"

[1] "list"

In [17]:
l1[2:4]

$letra
[1] "Hola team"

$pl
[1] "A" "B" "C"

$mat
     [,1] [,2]
[1,]    3    7
[2,]    5   11

In [19]:
# NOTA lista[.] retorna un lista con un elemento,
# lista[[.]] retorna el elmento de la lista lista[.]
l1[[3]]  # Retorna el vector
class(l1[[3]]) # Es un vector!

[1] "A" "B" "C"

[1] "character"

In [21]:
# Quiero rescatar el "B" del vector de la casilla 3 de l1.
l1[[3]][2]

[1] "B"

In [23]:
str(l1)

List of 5
 $ num  : int [1:10] 1 2 3 4 5 6 7 8 9 10
 $ letra: chr "Hola team"
 $ pl   : chr [1:3] "A" "B" "C"
 $ mat  : num [1:2, 1:2] 3 5 7 11
 $ lista:List of 2
  ..$ e1: num 3.4
  ..$ e2: chr [1:26] "A" "B" "C" "D" ...

In [35]:
# de la lista l1[[5]], quieo el vector que está en el slot llamado "e2" (segundo elemento)
l1[[5]][[2]]

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [31]:
# Acceso mediante nombre
l1[["pl"]]

[1] "A" "B" "C"

In [33]:
l1[["lista"]][["e2"]]

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [37]:
# acceso vía "$". Es un acceso directo al elemento de una entrada.
l1$pl
l1[["pl"]]
l1[[3]]

[1] "A" "B" "C"

[1] "A" "B" "C"

[1] "A" "B" "C"

In [38]:
#l1[["lista"]][["e2"]]
l1$lista$e2

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [41]:
# para saber el largo de la lista/vector
length(l1)
# Para obtener los nombres de la lista
names(l1)
# si quisiéramos renombrar los slots:
# Ej: Quiero cambiar el nombre de la casiila 4
names(l1)[4] <- "otra_cosa"

[1] 5

[1] "num"   "letra" "pl"    "mat"   "lista"

In [42]:
l1

$num
 [1]  1  2  3  4  5  6  7  8  9 10

$letra
[1] "Hola team"

$pl
[1] "A" "B" "C"

$otra_cosa
     [,1] [,2]
[1,]    3    7
[2,]    5   11

$lista
$lista$e1
[1] 3.4

$lista$e2
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [44]:
# También podemos crear nuevos "slots"
## Indicando nombre en [[]] y luego asignando
l1[["nuevo"]] <- diag(c(3,5,7))

In [45]:
l1

$num
 [1]  1  2  3  4  5  6  7  8  9 10

$letra
[1] "Hola team"

$pl
[1] "A" "B" "C"

$otra_cosa
     [,1] [,2]
[1,]    3    7
[2,]    5   11

$lista
$lista$e1
[1] 3.4

$lista$e2
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"


$nuevo
     [,1] [,2] [,3]
[1,]    3    0    0
[2,]    0    5    0
[3,]    0    0    7

In [47]:
l1$nuevo2 <- letters

In [48]:
l1

$num
 [1]  1  2  3  4  5  6  7  8  9 10

$letra
[1] "Hola team"

$pl
[1] "A" "B" "C"

$otra_cosa
     [,1] [,2]
[1,]    3    7
[2,]    5   11

$lista
$lista$e1
[1] 3.4

$lista$e2
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"


$nuevo
     [,1] [,2] [,3]
[1,]    3    0    0
[2,]    0    5    0
[3,]    0    0    7

$nuevo2
 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [51]:
# podemos modificar elementos dentro de un slot
#Ej: Cambiar el "0" de la posición 2,3 de la matriz "nuevo", por un -1
l1$nuevo[2,3] <- -1
#o equivalentemenete:
#l1[["nuevo"]][2,3] <- -1
#l1[[6]][2,3] <- -1

In [52]:
l1

$num
 [1]  1  2  3  4  5  6  7  8  9 10

$letra
[1] "Hola team"

$pl
[1] "A" "B" "C"

$otra_cosa
     [,1] [,2]
[1,]    3    7
[2,]    5   11

$lista
$lista$e1
[1] 3.4

$lista$e2
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"


$nuevo
     [,1] [,2] [,3]
[1,]    3    0    0
[2,]    0    5   -1
[3,]    0    0    7

$nuevo2
 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

### 5.2 Dataframes

Un dataframe es un caso particular de una lista, donde los objetos de cada entrada corresponden a vectores de datos del mismo largo. E este caso cada vector corresponde a una columna del data.frame, mientras que la cantidad de filas corresponde al largo común de los vectores de cada entrada. El objeto resultante es una *tabla*, de ahora en adelante *data.frame*, cuyas columnas poseen distintos tipos de datos entre sí.

 * ¿Cómo se declara un dataframe?<br>
     Mediante la función data.frame(), indicando los vectores que conformarán las columnas.

 * ¿Cómo se accede a los datos de un data.frame?<br>
    Al ser una lista, se puede acceder de la misma manera. Sin embargo también es posible acceder del modo en que se accede a los elementos de una matriz.

In [ ]:
# 5.2 Dataframes ----------
# Ejemplo sencillo de definición de un data.frame
# recordar que 1:3 es lo mismo que c(1,2,3)

In [ ]:
# Acceso a columnas de un data.frame
## Igual que en una lista

In [ ]:
##  Ganamos acceso como matriz
# segundafila de df


# segunda columna y segunda fila

In [ ]:
#Podemos crear nuevas columnas , del mismmo modo que creamos "slots" en una lista

In [ ]:
# podemos seleccionar más de una columna a la vez. Ej: seleccionar col1y col3

# Referenciando el nombre de las columnas

In [ ]:
# Referenciando las posiciones de las columnas

In [ ]:
# Se mantiene la lógica de acceso a los sots de una lista.